// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";

function ensureIsObject(val, path) {
  if (!(!(val && typeof val === 'object' && !Array.isArray(val)))) {
    return;
  }
  throw Stdlib_Exn.raiseError(`tiers.json: ` + path + ` must be an object`);
}

function validateTierCaps(obj) {
  let json = Js_dict.get(obj, "tierCaps");
  if (json === undefined) {
    return;
  }
  ensureIsObject(json, "'tierCaps'");
  let caps = Js_json.decodeObject(json);
  if (caps !== undefined) {
    let keys = Object.keys(caps);
    let _keys = Stdlib_List.fromArray(keys);
    while (true) {
      let keys$1 = _keys;
      if (keys$1 === 0) {
        return;
      }
      let rest = keys$1.tl;
      let k = keys$1.hd;
      let capJson = Js_dict.get(caps, k);
      if (capJson !== undefined) {
        let cap = Js_json.decodeNumber(capJson);
        if (cap !== undefined) {
          if ((!(Number.isFinite(cap) && cap >= 1))) {
            throw Stdlib_Exn.raiseError(`tiers.json: tierCaps.'` + k + `' must be a positive integer`);
          }
          _keys = rest;
          continue;
        }
        throw Stdlib_Exn.raiseError(`tiers.json: tierCaps.'` + k + `' must be a positive integer`);
      }
      _keys = rest;
      continue;
    };
  }
  throw Stdlib_Exn.raiseError("tiers.json: 'tierCaps' must be a non-null object");
}

function validateTierPrompts(obj) {
  let json = Js_dict.get(obj, "tierPrompts");
  if (json === undefined) {
    return;
  }
  ensureIsObject(json, "'tierPrompts'");
  let prompts = Js_json.decodeObject(json);
  if (prompts !== undefined) {
    let keys = Object.keys(prompts);
    let _keys = Stdlib_List.fromArray(keys);
    while (true) {
      let keys$1 = _keys;
      if (keys$1 === 0) {
        return;
      }
      let rest = keys$1.tl;
      let k = keys$1.hd;
      let promptJson = Js_dict.get(prompts, k);
      if (promptJson !== undefined) {
        let match = Js_json.decodeString(promptJson);
        if (match !== undefined) {
          _keys = rest;
          continue;
        }
        throw Stdlib_Exn.raiseError(`tiers.json: tierPrompts.'` + k + `' must be a string`);
      }
      _keys = rest;
      continue;
    };
  }
  throw Stdlib_Exn.raiseError("tiers.json: 'tierPrompts' must be a non-null object");
}

function validateTaskPatterns(obj) {
  let json = Js_dict.get(obj, "taskPatterns");
  if (json === undefined) {
    return;
  }
  ensureIsObject(json, "'taskPatterns'");
  let patterns = Js_json.decodeObject(json);
  if (patterns !== undefined) {
    let keys = Object.keys(patterns);
    let _keys = Stdlib_List.fromArray(keys);
    while (true) {
      let keys$1 = _keys;
      if (keys$1 === 0) {
        return;
      }
      let rest = keys$1.tl;
      let k = keys$1.hd;
      let patternsJson = Js_dict.get(patterns, k);
      if (patternsJson !== undefined) {
        let match = Js_json.decodeArray(patternsJson);
        if (match !== undefined) {
          _keys = rest;
          continue;
        }
        throw Stdlib_Exn.raiseError(`tiers.json: taskPatterns.'` + k + `' must be an array of strings`);
      }
      _keys = rest;
      continue;
    };
  }
  throw Stdlib_Exn.raiseError("tiers.json: 'taskPatterns' must be a non-null object");
}

export {
  validateTierCaps,
  validateTierPrompts,
  validateTaskPatterns,
}
/* No side effect */
