// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function getStringField(dict, key) {
  let json = dict[key];
  if (json === undefined) {
    return "";
  }
  let s = Stdlib_JSON.Decode.string(json);
  if (s !== undefined) {
    return s;
  } else {
    return "";
  }
}

function _isPlainObject(d) {
  try {
    let keys = Object.keys(d);
    if (Array.isArray(d)) {
      return false;
    } else if (keys.length === 0) {
      return true;
    } else {
      return Belt_Array.some(keys, key => {
        let n = Stdlib_Int.fromString(key, undefined);
        if (n !== undefined && n >= 0) {
          return String(n) !== key;
        } else {
          return true;
        }
      });
    }
  } catch (exn) {
    return false;
  }
}

function ensureIsObject(tier, presetName, tierName) {
  if (_isPlainObject(tier)) {
    return;
  }
  throw Stdlib_JsError.throwWithMessage(`tiers.json: tier '` + presetName + `.` + tierName + `' must be an object`);
}

function validateTier(presetName, tierName, tier) {
  ensureIsObject(tier, presetName, tierName);
  let modelVal = getStringField(tier, "model");
  if (modelVal === "") {
    throw Stdlib_JsError.throwWithMessage(`tiers.json: '` + presetName + `.` + tierName + `.model' must be a non-empty string`);
  }
  let slashIdx = modelVal.indexOf("/");
  if (slashIdx <= 0 || slashIdx >= (modelVal.length - 1 | 0)) {
    throw Stdlib_JsError.throwWithMessage(`tiers.json: '` + presetName + `.` + tierName + `.model' must be provider/model (got ` + modelVal + `)`);
  }
  let descVal = getStringField(tier, "description");
  if (descVal === "") {
    throw Stdlib_JsError.throwWithMessage(`tiers.json: '` + presetName + `.` + tierName + `.description' must be a string`);
  }
  let json = tier["whenToUse"];
  if (json !== undefined) {
    let match = Stdlib_JSON.Decode.array(json);
    if (match !== undefined) {
      return;
    }
    throw Stdlib_JsError.throwWithMessage(`tiers.json: '` + presetName + `.` + tierName + `.whenToUse' must be an array`);
  }
  throw Stdlib_JsError.throwWithMessage(`tiers.json: '` + presetName + `.` + tierName + `.whenToUse' must be an array`);
}

function ensurePresetIsObject(preset, presetName) {
  if (_isPlainObject(preset)) {
    return;
  }
  throw Stdlib_JsError.throwWithMessage(`tiers.json: preset '` + presetName + `' must be an object`);
}

function validatePreset(presetName, preset) {
  ensurePresetIsObject(preset, presetName);
  let keys = Stdlib_List.fromArray(Object.keys(preset));
  let _keys = keys;
  while (true) {
    let keys$1 = _keys;
    if (keys$1 === 0) {
      return;
    }
    let rest = keys$1.tl;
    let k = keys$1.hd;
    let tierJson = preset[k];
    if (tierJson !== undefined) {
      let tier = Stdlib_JSON.Decode.object(tierJson);
      if (tier !== undefined) {
        validateTier(presetName, k, tier);
        _keys = rest;
        continue;
      }
      throw Stdlib_JsError.throwWithMessage(`tiers.json: tier '` + presetName + `.` + k + `' must be an object`);
    }
    _keys = rest;
    continue;
  };
}

function ensureIsConfigObject(obj) {
  if (_isPlainObject(obj)) {
    return;
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: expected a JSON object at root");
}

function validatePresets(obj) {
  ensureIsConfigObject(obj);
  let json = obj["presets"];
  if (json !== undefined) {
    let presets = Stdlib_JSON.Decode.object(json);
    if (presets !== undefined) {
      let keys = Object.keys(presets);
      let match = keys.length;
      if (match !== 0) {
        let _keys = Stdlib_List.fromArray(keys);
        while (true) {
          let keys$1 = _keys;
          if (keys$1 === 0) {
            return;
          }
          let rest = keys$1.tl;
          let k = keys$1.hd;
          let presetJson = presets[k];
          if (presetJson !== undefined) {
            let preset = Stdlib_JSON.Decode.object(presetJson);
            if (preset !== undefined) {
              validatePreset(k, preset);
              _keys = rest;
              continue;
            }
            throw Stdlib_JsError.throwWithMessage(`tiers.json: preset '` + k + `' must be an object`);
          }
          _keys = rest;
          continue;
        };
      }
      throw Stdlib_JsError.throwWithMessage("tiers.json: 'presets' must have at least one preset");
    }
    throw Stdlib_JsError.throwWithMessage("tiers.json: 'presets' must be a non-null object");
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: 'presets' must be a non-null object");
}

export {
  validatePresets,
  validatePreset,
  validateTier,
}
/* No side effect */
