// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as ValidateModes from "./ValidateModes.res.mjs";

function assertionNoThrow(operator, fn) {
  Test.assertion(undefined, operator, (_a, _b) => true, (fn(), 0), 0);
}

Test.test("validateModes: accepts a modes object with one valid mode", () => {
  let dict = {modes: {auto: {defaultTier: "fast", description: "Auto mode"}}};
  assertionNoThrow("valid single mode", () => ValidateModes.validateModes(dict));
});

Test.test("validateModes: accepts a modes object with multiple valid modes", () => {
  let dict = {modes: {auto: {defaultTier: "fast", description: "Auto"}, careful: {defaultTier: "heavy", description: "Careful"}}};
  assertionNoThrow("valid multi mode", () => ValidateModes.validateModes(dict));
});

Test.test("validateModes: accepts empty modes object", () => {
  let dict = {modes: {}};
  assertionNoThrow("empty modes", () => ValidateModes.validateModes(dict));
});

Test.test("validateMode: accepts a fully-specified valid mode", () => {
  let mode = {defaultTier: "fast", description: "Fast auto mode"};
  assertionNoThrow("valid full mode", () => ValidateModes.validateMode("myMode", mode));
});

Test.test("validateMode: accepts mode with minimal required fields", () => {
  let mode = {defaultTier: "tier1", description: "Minimal mode"};
  assertionNoThrow("minimal mode", () => ValidateModes.validateMode("modeA", mode));
});

export {
  assertionNoThrow,
}
/*  Not a pure module */
