// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";

let enforcementModes = [
  "off",
  "advisory",
  "enforced"
];

let verifyRequireModes = [
  "never",
  "whenDoDPresent",
  "always"
];

function ensureIsObjectVal(val, path) {
  if (!(!(val && typeof val === 'object' && !Array.isArray(val)))) {
    return;
  }
  throw Stdlib_Exn.raiseError(`tiers.json: ` + path + ` must be an object`);
}

function stringInArray(s, arr) {
  let _i = 0;
  while (true) {
    let i = _i;
    if (i >= arr.length) {
      return false;
    }
    if (arr[i] === s) {
      return true;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function validateEscalateCostCeiling(escalate) {
  let ccJson = Js_dict.get(escalate, "costCeiling");
  if (ccJson === undefined) {
    return;
  }
  if ((!(ccJson && typeof ccJson === 'object' && !Array.isArray(ccJson)))) {
    return;
  }
  let cc = Js_json.decodeObject(ccJson);
  if (cc === undefined) {
    return;
  }
  let multJson = Js_dict.get(cc, "multiple");
  if (multJson === undefined) {
    return;
  }
  let mult = Js_json.decodeNumber(multJson);
  if (mult !== undefined) {
    if (mult > 0.0) {
      return;
    }
    throw Stdlib_Exn.raiseError("tiers.json: enforcement.escalate.costCeiling.multiple must be a number > 0");
  }
  throw Stdlib_Exn.raiseError("tiers.json: enforcement.escalate.costCeiling.multiple must be a number > 0");
}

function validateEnforcementMode(enf) {
  let modeJson = Js_dict.get(enf, "mode");
  if (modeJson === undefined) {
    return;
  }
  let mode = Js_json.decodeString(modeJson);
  if (mode !== undefined) {
    if (stringInArray(mode, enforcementModes)) {
      return;
    }
    throw Stdlib_Exn.raiseError(`tiers.json: enforcement.mode must be one of off|advisory|enforced`);
  }
  throw Stdlib_Exn.raiseError(`tiers.json: enforcement.mode must be one of off|advisory|enforced`);
}

function validateEnforcementPerTier(enf) {
  let json = Js_dict.get(enf, "perTier");
  if (json === undefined) {
    return;
  }
  if ((!(json && typeof json === 'object' && !Array.isArray(json)))) {
    return;
  }
  let perTier = Js_json.decodeObject(json);
  if (perTier === undefined) {
    return;
  }
  let keys = Object.keys(perTier);
  let _i = 0;
  while (true) {
    let i = _i;
    if (i >= keys.length) {
      return;
    }
    let k = keys[i];
    let tierModeJson = Js_dict.get(perTier, k);
    if (tierModeJson !== undefined) {
      let tierMode = Js_json.decodeString(tierModeJson);
      if (tierMode !== undefined) {
        if (!stringInArray(tierMode, enforcementModes)) {
          throw Stdlib_Exn.raiseError(`tiers.json: enforcement.perTier.` + k + ` must be one of off|advisory|enforced`);
        }
      } else {
        throw Stdlib_Exn.raiseError(`tiers.json: enforcement.perTier.` + k + ` must be one of off|advisory|enforced`);
      }
    }
    _i = i + 1 | 0;
    continue;
  };
}

function validateEnforcementEscalate(enf) {
  let json = Js_dict.get(enf, "escalate");
  if (json === undefined) {
    return;
  }
  if ((!(json && typeof json === 'object' && !Array.isArray(json)))) {
    return;
  }
  let escalate = Js_json.decodeObject(json);
  if (escalate === undefined) {
    return;
  }
  validateEscalateCostCeiling(escalate);
  let ladderJson = Js_dict.get(escalate, "ladder");
  if (ladderJson !== undefined) {
    let ladder = Js_json.decodeArray(ladderJson);
    if (ladder !== undefined) {
      let goLadder = _i => {
        while (true) {
          let i = _i;
          if (i >= ladder.length) {
            return;
          }
          let item = ladder[i];
          let match = Js_json.decodeString(item);
          if (match !== undefined) {
            _i = i + 1 | 0;
            continue;
          }
          throw Stdlib_Exn.raiseError("tiers.json: enforcement.escalate.ladder must be an array of strings");
        };
      };
      goLadder(0);
    } else {
      throw Stdlib_Exn.raiseError("tiers.json: enforcement.escalate.ladder must be an array of strings");
    }
  }
  let matJson = Js_dict.get(escalate, "maxAttemptsPerTier");
  if (matJson !== undefined) {
    let mat = Js_json.decodeNumber(matJson);
    if (mat !== undefined && (!(Number.isInteger(mat) && mat >= 0))) {
      throw Stdlib_Exn.raiseError("tiers.json: enforcement.escalate.maxAttemptsPerTier must be an integer >= 0");
    }
  }
  let mtaJson = Js_dict.get(escalate, "maxTotalAttempts");
  if (mtaJson !== undefined) {
    let mta = Js_json.decodeNumber(mtaJson);
    if (mta !== undefined && (!(Number.isInteger(mta) && mta >= 1))) {
      throw Stdlib_Exn.raiseError("tiers.json: enforcement.escalate.maxTotalAttempts must be an integer >= 1");
    }
  }
  let ftJson = Js_dict.get(escalate, "floorTier");
  if (ftJson === undefined) {
    return;
  }
  if ((ftJson === null)) {
    return;
  }
  let match = Js_json.decodeString(ftJson);
  if (match !== undefined) {
    return;
  }
  throw Stdlib_Exn.raiseError("tiers.json: enforcement.escalate.floorTier must be a string or null");
}

function validateEnforcementGuard(enf) {
  let json = Js_dict.get(enf, "guard");
  if (json === undefined) {
    return;
  }
  if ((!(json && typeof json === 'object' && !Array.isArray(json)))) {
    return;
  }
  let guard = Js_json.decodeObject(json);
  if (guard === undefined) {
    return;
  }
  let budgetJson = Js_dict.get(guard, "budget");
  if (budgetJson !== undefined) {
    let budget = Js_json.decodeNumber(budgetJson);
    if (budget !== undefined) {
      if ((!(Number.isFinite(budget) && budget >= 1))) {
        throw Stdlib_Exn.raiseError("enforcement.guard.budget must be a number >= 1");
      }
    } else {
      throw Stdlib_Exn.raiseError("enforcement.guard.budget must be a number >= 1");
    }
  }
  let bswJson = Js_dict.get(guard, "blockScriptWrites");
  if (bswJson === undefined) {
    return;
  }
  let match = Js_json.decodeBoolean(bswJson);
  if (match !== undefined) {
    return;
  }
  throw Stdlib_Exn.raiseError("enforcement.guard.blockScriptWrites must be a boolean");
}

function validateEnforcementVerify(enf) {
  let json = Js_dict.get(enf, "verify");
  if (json === undefined) {
    return;
  }
  if ((!(json && typeof json === 'object' && !Array.isArray(json)))) {
    return;
  }
  let verify = Js_json.decodeObject(json);
  if (verify === undefined) {
    return;
  }
  let gpJson = Js_dict.get(verify, "graderPolicy");
  if (gpJson !== undefined) {
    let gp = Js_json.decodeString(gpJson);
    if (gp !== undefined) {
      if (gp !== "atLeastProducerTier") {
        throw Stdlib_Exn.raiseError(`tiers.json: enforcement.verify.graderPolicy must be "atLeastProducerTier"`);
      }
    } else {
      throw Stdlib_Exn.raiseError(`tiers.json: enforcement.verify.graderPolicy must be "atLeastProducerTier"`);
    }
  }
  let reqJson = Js_dict.get(verify, "require");
  if (reqJson === undefined) {
    return;
  }
  let req = Js_json.decodeString(reqJson);
  if (req !== undefined) {
    if (stringInArray(req, verifyRequireModes)) {
      return;
    }
    throw Stdlib_Exn.raiseError(`tiers.json: enforcement.verify.require must be one of never|whenDoDPresent|always`);
  }
  throw Stdlib_Exn.raiseError(`tiers.json: enforcement.verify.require must be one of never|whenDoDPresent|always (got ` + JSON.stringify(reqJson) + `)`);
}

function validateEnforcement(obj) {
  let json = Js_dict.get(obj, "enforcement");
  if (json === undefined) {
    return;
  }
  ensureIsObjectVal(json, "enforcement");
  let enf = Js_json.decodeObject(json);
  if (enf !== undefined) {
    validateEnforcementMode(enf);
    validateEnforcementVerify(enf);
    validateEnforcementEscalate(enf);
    validateEnforcementPerTier(enf);
    return validateEnforcementGuard(enf);
  }
  throw Stdlib_Exn.raiseError("tiers.json: enforcement must be a non-null object");
}

export {
  validateEnforcement,
  validateEnforcementMode,
  validateEnforcementVerify,
  validateEnforcementEscalate,
  validateEnforcementPerTier,
  validateEnforcementGuard,
  validateEscalateCostCeiling,
}
/* No side effect */
