// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

let enforcementModes = [
  "off",
  "advisory",
  "enforced"
];

let verifyRequireModes = [
  "never",
  "whenDoDPresent",
  "always"
];

function ensureIsObjectVal(_val, path) {
  if (!(!(val && typeof val === 'object' && !Array.isArray(val)))) {
    return;
  }
  throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + path + ` must be an object`);
}

function stringInArray(s, arr) {
  let _i = 0;
  while (true) {
    let i = _i;
    if (i >= arr.length) {
      return false;
    }
    if (arr[i] === s) {
      return true;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function validateEscalateCostCeiling(escalate) {
  let ccJson = escalate["costCeiling"];
  if (ccJson === undefined) {
    return;
  }
  if ((!(ccJson && typeof ccJson === 'object' && !Array.isArray(ccJson)))) {
    return;
  }
  let cc = Stdlib_JSON.Decode.object(ccJson);
  if (cc === undefined) {
    return;
  }
  let multJson = cc["multiple"];
  if (multJson === undefined) {
    return;
  }
  let mult = Stdlib_JSON.Decode.float(multJson);
  if (mult !== undefined) {
    if (mult > 0.0) {
      return;
    }
    throw Stdlib_JsError.throwWithMessage("tiers.json: enforcement.escalate.costCeiling.multiple must be a number > 0");
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: enforcement.escalate.costCeiling.multiple must be a number > 0");
}

function validateEnforcementEscalate(enf) {
  let json = enf["escalate"];
  if (json === undefined) {
    return;
  }
  if ((!(json && typeof json === 'object' && !Array.isArray(json)))) {
    return;
  }
  let escalate = Stdlib_JSON.Decode.object(json);
  if (escalate === undefined) {
    return;
  }
  validateEscalateCostCeiling(escalate);
  let ladderJson = escalate["ladder"];
  if (ladderJson !== undefined) {
    let ladder = Stdlib_JSON.Decode.array(ladderJson);
    if (ladder !== undefined) {
      let goLadder = _i => {
        while (true) {
          let i = _i;
          if (i >= ladder.length) {
            return;
          }
          let item = ladder[i];
          let match = Stdlib_JSON.Decode.string(item);
          if (match !== undefined) {
            _i = i + 1 | 0;
            continue;
          }
          throw Stdlib_JsError.throwWithMessage("tiers.json: enforcement.escalate.ladder must be an array of strings");
        };
      };
      goLadder(0);
    } else {
      throw Stdlib_JsError.throwWithMessage("tiers.json: enforcement.escalate.ladder must be an array of strings");
    }
  }
  let matJson = escalate["maxAttemptsPerTier"];
  if (matJson !== undefined) {
    let _mat = Stdlib_JSON.Decode.float(matJson);
    if (_mat !== undefined && (!(Number.isInteger(mat) && mat >= 0))) {
      throw Stdlib_JsError.throwWithMessage("tiers.json: enforcement.escalate.maxAttemptsPerTier must be an integer >= 0");
    }
  }
  let mtaJson = escalate["maxTotalAttempts"];
  if (mtaJson !== undefined) {
    let _mta = Stdlib_JSON.Decode.float(mtaJson);
    if (_mta !== undefined && (!(Number.isInteger(mta) && mta >= 1))) {
      throw Stdlib_JsError.throwWithMessage("tiers.json: enforcement.escalate.maxTotalAttempts must be an integer >= 1");
    }
  }
  let ftJson = escalate["floorTier"];
  if (ftJson === undefined) {
    return;
  }
  if ((ftJson === null)) {
    return;
  }
  let match = Stdlib_JSON.Decode.string(ftJson);
  if (match !== undefined) {
    return;
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: enforcement.escalate.floorTier must be a string or null");
}

function validateEnforcementPerTier(enf) {
  let json = enf["perTier"];
  if (json === undefined) {
    return;
  }
  if ((!(json && typeof json === 'object' && !Array.isArray(json)))) {
    return;
  }
  let perTier = Stdlib_JSON.Decode.object(json);
  if (perTier === undefined) {
    return;
  }
  let keys = Object.keys(perTier);
  let _i = 0;
  while (true) {
    let i = _i;
    if (i >= keys.length) {
      return;
    }
    let k = keys[i];
    let tierModeJson = perTier[k];
    if (tierModeJson !== undefined) {
      let tierMode = Stdlib_JSON.Decode.string(tierModeJson);
      if (tierMode !== undefined) {
        if (!stringInArray(tierMode, enforcementModes)) {
          throw Stdlib_JsError.throwWithMessage(`tiers.json: enforcement.perTier.` + k + ` must be one of off|advisory|enforced`);
        }
      } else {
        throw Stdlib_JsError.throwWithMessage(`tiers.json: enforcement.perTier.` + k + ` must be one of off|advisory|enforced`);
      }
    }
    _i = i + 1 | 0;
    continue;
  };
}

function validateEnforcementVerify(enf) {
  let json = enf["verify"];
  if (json === undefined) {
    return;
  }
  if ((!(json && typeof json === 'object' && !Array.isArray(json)))) {
    return;
  }
  let verify = Stdlib_JSON.Decode.object(json);
  if (verify === undefined) {
    return;
  }
  let gpJson = verify["graderPolicy"];
  if (gpJson !== undefined) {
    let gp = Stdlib_JSON.Decode.string(gpJson);
    if (gp !== undefined) {
      if (gp !== "atLeastProducerTier") {
        throw Stdlib_JsError.throwWithMessage(`tiers.json: enforcement.verify.graderPolicy must be "atLeastProducerTier"`);
      }
    } else {
      throw Stdlib_JsError.throwWithMessage(`tiers.json: enforcement.verify.graderPolicy must be "atLeastProducerTier"`);
    }
  }
  let reqJson = verify["require"];
  if (reqJson === undefined) {
    return;
  }
  let req = Stdlib_JSON.Decode.string(reqJson);
  if (req !== undefined) {
    if (stringInArray(req, verifyRequireModes)) {
      return;
    }
    throw Stdlib_JsError.throwWithMessage(`tiers.json: enforcement.verify.require must be one of never|whenDoDPresent|always`);
  }
  throw Stdlib_JsError.throwWithMessage(`tiers.json: enforcement.verify.require must be one of never|whenDoDPresent|always (got ` + JSON.stringify(reqJson) + `)`);
}

function validateEnforcementMode(enf) {
  let modeJson = enf["mode"];
  if (modeJson === undefined) {
    return;
  }
  let mode = Stdlib_JSON.Decode.string(modeJson);
  if (mode !== undefined) {
    if (stringInArray(mode, enforcementModes)) {
      return;
    }
    throw Stdlib_JsError.throwWithMessage(`tiers.json: enforcement.mode must be one of off|advisory|enforced`);
  }
  throw Stdlib_JsError.throwWithMessage(`tiers.json: enforcement.mode must be one of off|advisory|enforced`);
}

function validateEnforcementGuard(enf) {
  let json = enf["guard"];
  if (json === undefined) {
    return;
  }
  if ((!(json && typeof json === 'object' && !Array.isArray(json)))) {
    return;
  }
  let guard = Stdlib_JSON.Decode.object(json);
  if (guard === undefined) {
    return;
  }
  let budgetJson = guard["budget"];
  if (budgetJson !== undefined) {
    let _budget = Stdlib_JSON.Decode.float(budgetJson);
    if (_budget !== undefined) {
      if ((!(Number.isFinite(budget) && budget >= 1))) {
        throw Stdlib_JsError.throwWithMessage("enforcement.guard.budget must be a number >= 1");
      }
    } else {
      throw Stdlib_JsError.throwWithMessage("enforcement.guard.budget must be a number >= 1");
    }
  }
  let bswJson = guard["blockScriptWrites"];
  if (bswJson === undefined) {
    return;
  }
  let match = Stdlib_JSON.Decode.bool(bswJson);
  if (match !== undefined) {
    return;
  }
  throw Stdlib_JsError.throwWithMessage("enforcement.guard.blockScriptWrites must be a boolean");
}

function validateEnforcement(obj) {
  let json = obj["enforcement"];
  if (json === undefined) {
    return;
  }
  ensureIsObjectVal(json, "enforcement");
  let enf = Stdlib_JSON.Decode.object(json);
  if (enf !== undefined) {
    validateEnforcementMode(enf);
    validateEnforcementVerify(enf);
    validateEnforcementEscalate(enf);
    validateEnforcementPerTier(enf);
    return validateEnforcementGuard(enf);
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: enforcement must be a non-null object");
}

export {
  validateEnforcement,
  validateEnforcementMode,
  validateEnforcementVerify,
  validateEnforcementEscalate,
  validateEnforcementPerTier,
  validateEnforcementGuard,
  validateEscalateCostCeiling,
}
/* No side effect */
