// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function validateRootFields(obj) {
  let json = obj["activePreset"];
  if (json !== undefined) {
    let s = Stdlib_JSON.Decode.string(json);
    if (s !== undefined) {
      if (s !== "") {
        return;
      }
      throw Stdlib_JsError.throwWithMessage("tiers.json: 'activePreset' must be a non-empty string");
    }
    throw Stdlib_JsError.throwWithMessage("tiers.json: 'activePreset' must be a non-empty string");
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: 'activePreset' must be a non-empty string");
}

function checkStringArray(_arr) {
  while (true) {
    let arr = _arr;
    if (arr === 0) {
      return;
    }
    let match = Stdlib_JSON.Decode.string(arr.hd);
    if (match !== undefined) {
      _arr = arr.tl;
      continue;
    }
    throw Stdlib_JsError.throwWithMessage("tiers.json: 'rules' must be an array of strings");
  };
}

function validateRulesAndDefaultTier(obj) {
  let json = obj["rules"];
  if (json !== undefined) {
    let arr = Stdlib_JSON.Decode.array(json);
    if (arr !== undefined) {
      checkStringArray(Stdlib_List.fromArray(arr));
    } else {
      throw Stdlib_JsError.throwWithMessage("tiers.json: 'rules' must be an array of strings");
    }
  } else {
    throw Stdlib_JsError.throwWithMessage("tiers.json: 'rules' must be an array of strings");
  }
  let json$1 = obj["defaultTier"];
  if (json$1 !== undefined) {
    let s = Stdlib_JSON.Decode.string(json$1);
    if (s !== undefined) {
      if (s !== "") {
        return;
      }
      throw Stdlib_JsError.throwWithMessage("tiers.json: 'defaultTier' must be a string");
    }
    throw Stdlib_JsError.throwWithMessage("tiers.json: 'defaultTier' must be a string");
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: 'defaultTier' must be a string");
}

export {
  validateRootFields,
  validateRulesAndDefaultTier,
}
/* No side effect */
