// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ValidateRoot from "./ValidateRoot.res.mjs";
import * as ValidateModes from "./ValidateModes.res.mjs";
import * as ValidateSimple from "./ValidateSimple.res.mjs";
import * as ValidatePresets from "./ValidatePresets.res.mjs";
import * as ValidateReasoning from "./ValidateReasoning.res.mjs";
import * as ValidateEnforcement from "./ValidateEnforcement.res.mjs";

function validateConfig(obj) {
  ValidateRoot.validateRootFields(obj);
  ValidateRoot.validateRulesAndDefaultTier(obj);
  ValidatePresets.validatePresets(obj);
  ValidateModes.validateModes(obj);
  ValidateSimple.validateTierCaps(obj);
  ValidateSimple.validateTierPrompts(obj);
  ValidateSimple.validateTaskPatterns(obj);
  ValidateEnforcement.validateEnforcement(obj);
  ValidateReasoning.validateReasoningPolicy(obj);
  return obj;
}

let validateRootFields = ValidateRoot.validateRootFields;

let validateRulesAndDefaultTier = ValidateRoot.validateRulesAndDefaultTier;

let validatePresets = ValidatePresets.validatePresets;

let validatePreset = ValidatePresets.validatePreset;

let validateTier = ValidatePresets.validateTier;

let validateModes = ValidateModes.validateModes;

let validateMode = ValidateModes.validateMode;

let validateTierCaps = ValidateSimple.validateTierCaps;

let validateTierPrompts = ValidateSimple.validateTierPrompts;

let validateTaskPatterns = ValidateSimple.validateTaskPatterns;

let validateEnforcement = ValidateEnforcement.validateEnforcement;

let validateEnforcementMode = ValidateEnforcement.validateEnforcementMode;

let validateEnforcementVerify = ValidateEnforcement.validateEnforcementVerify;

let validateEnforcementEscalate = ValidateEnforcement.validateEnforcementEscalate;

let validateEnforcementPerTier = ValidateEnforcement.validateEnforcementPerTier;

let validateEnforcementGuard = ValidateEnforcement.validateEnforcementGuard;

let validateEscalateCostCeiling = ValidateEnforcement.validateEscalateCostCeiling;

let validateReasoningPolicy = ValidateReasoning.validateReasoningPolicy;

let validateReasoningPolicyMode = ValidateReasoning.validateReasoningPolicyMode;

let validateAdaptivePolicy = ValidateReasoning.validateAdaptivePolicy;

let validateKeywordRules = ValidateReasoning.validateKeywordRules;

let validateKeywordRule = ValidateReasoning.validateKeywordRule;

let validateAdaptiveTierDefaults = ValidateReasoning.validateAdaptiveTierDefaults;

let validateAdaptiveSurfaceDecision = ValidateReasoning.validateAdaptiveSurfaceDecision;

export {
  validateRootFields,
  validateRulesAndDefaultTier,
  validatePresets,
  validatePreset,
  validateTier,
  validateModes,
  validateMode,
  validateTierCaps,
  validateTierPrompts,
  validateTaskPatterns,
  validateEnforcement,
  validateEnforcementMode,
  validateEnforcementVerify,
  validateEnforcementEscalate,
  validateEnforcementPerTier,
  validateEnforcementGuard,
  validateEscalateCostCeiling,
  validateReasoningPolicy,
  validateReasoningPolicyMode,
  validateAdaptivePolicy,
  validateKeywordRules,
  validateKeywordRule,
  validateAdaptiveTierDefaults,
  validateAdaptiveSurfaceDecision,
  validateConfig,
}
/* No side effect */
