// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function ensureIsObject(_val, path) {
  if (!(!(val && typeof val === 'object' && !Array.isArray(val)))) {
    return;
  }
  throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + path + ` must be an object`);
}

function validateTierCaps(obj) {
  let json = obj["tierCaps"];
  if (json === undefined) {
    return;
  }
  ensureIsObject(json, "'tierCaps'");
  let caps = Stdlib_JSON.Decode.object(json);
  if (caps !== undefined) {
    let keys = Object.keys(caps);
    let _keys = Stdlib_List.fromArray(keys);
    while (true) {
      let keys$1 = _keys;
      if (keys$1 === 0) {
        return;
      }
      let rest = keys$1.tl;
      let k = keys$1.hd;
      let capJson = caps[k];
      if (capJson !== undefined) {
        let _cap = Stdlib_JSON.Decode.float(capJson);
        if (_cap !== undefined) {
          if ((!(Number.isFinite(cap) && cap >= 1))) {
            throw Stdlib_JsError.throwWithMessage(`tiers.json: tierCaps.'` + k + `' must be a positive integer`);
          }
          _keys = rest;
          continue;
        }
        throw Stdlib_JsError.throwWithMessage(`tiers.json: tierCaps.'` + k + `' must be a positive integer`);
      }
      _keys = rest;
      continue;
    };
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: 'tierCaps' must be a non-null object");
}

function validateTierPrompts(obj) {
  let json = obj["tierPrompts"];
  if (json === undefined) {
    return;
  }
  ensureIsObject(json, "'tierPrompts'");
  let prompts = Stdlib_JSON.Decode.object(json);
  if (prompts !== undefined) {
    let keys = Object.keys(prompts);
    let _keys = Stdlib_List.fromArray(keys);
    while (true) {
      let keys$1 = _keys;
      if (keys$1 === 0) {
        return;
      }
      let rest = keys$1.tl;
      let k = keys$1.hd;
      let promptJson = prompts[k];
      if (promptJson !== undefined) {
        let match = Stdlib_JSON.Decode.string(promptJson);
        if (match !== undefined) {
          _keys = rest;
          continue;
        }
        throw Stdlib_JsError.throwWithMessage(`tiers.json: tierPrompts.'` + k + `' must be a string`);
      }
      _keys = rest;
      continue;
    };
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: 'tierPrompts' must be a non-null object");
}

function validateTaskPatterns(obj) {
  let json = obj["taskPatterns"];
  if (json === undefined) {
    return;
  }
  ensureIsObject(json, "'taskPatterns'");
  let patterns = Stdlib_JSON.Decode.object(json);
  if (patterns !== undefined) {
    let keys = Object.keys(patterns);
    let _keys = Stdlib_List.fromArray(keys);
    while (true) {
      let keys$1 = _keys;
      if (keys$1 === 0) {
        return;
      }
      let rest = keys$1.tl;
      let k = keys$1.hd;
      let patternsJson = patterns[k];
      if (patternsJson !== undefined) {
        let match = Stdlib_JSON.Decode.array(patternsJson);
        if (match !== undefined) {
          _keys = rest;
          continue;
        }
        throw Stdlib_JsError.throwWithMessage(`tiers.json: taskPatterns.'` + k + `' must be an array of strings`);
      }
      _keys = rest;
      continue;
    };
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: 'taskPatterns' must be a non-null object");
}

export {
  validateTierCaps,
  validateTierPrompts,
  validateTaskPatterns,
}
/* No side effect */
