// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as ValidateEnforcement from "./ValidateEnforcement.res.mjs";

function assertionNoThrow(operator, fn) {
  Test.assertion(undefined, operator, (_a, _b) => true, (fn(), 0), 0);
}

Test.test("validateEnforcement: accepts a valid enforcement object", () => {
  let dict = {enforcement: {mode: "advisory"}};
  assertionNoThrow("valid enforcement", () => ValidateEnforcement.validateEnforcement(dict));
});

Test.test("validateEnforcement: passes silently when enforcement is absent", () => {
  let dict = {activePreset: "default"};
  assertionNoThrow("absent enforcement", () => ValidateEnforcement.validateEnforcement(dict));
});

Test.test("validateEnforcementMode: accepts mode 'off'", () => {
  let dict = {mode: "off"};
  assertionNoThrow("mode off", () => ValidateEnforcement.validateEnforcementMode(dict));
});

Test.test("validateEnforcementMode: accepts mode 'advisory'", () => {
  let dict = {mode: "advisory"};
  assertionNoThrow("mode advisory", () => ValidateEnforcement.validateEnforcementMode(dict));
});

Test.test("validateEnforcementMode: accepts mode 'enforced'", () => {
  let dict = {mode: "enforced"};
  assertionNoThrow("mode enforced", () => ValidateEnforcement.validateEnforcementMode(dict));
});

Test.test("validateEnforcementMode: passes silently when mode is absent", () => {
  let dict = {otherField: "value"};
  assertionNoThrow("absent mode", () => ValidateEnforcement.validateEnforcementMode(dict));
});

Test.test("validateEnforcementVerify: accepts a valid verify block", () => {
  let dict = {verify: {require: "whenDoDPresent"}};
  assertionNoThrow("valid verify", () => ValidateEnforcement.validateEnforcementVerify(dict));
});

Test.test("validateEnforcementVerify: accepts verify with all optional fields", () => {
  let dict = {verify: {require: "always", preferDeterministic: true, graderPolicy: "atLeastProducerTier"}};
  assertionNoThrow("full verify", () => ValidateEnforcement.validateEnforcementVerify(dict));
});

Test.test("validateEnforcementVerify: passes silently when verify is absent", () => {
  let dict = {mode: "off"};
  assertionNoThrow("absent verify", () => ValidateEnforcement.validateEnforcementVerify(dict));
});

Test.test("validateEnforcementEscalate: accepts a valid escalate block with ladder", () => {
  let dict = {escalate: {ladder: ["tier1", "tier2"]}};
  assertionNoThrow("valid escalate", () => ValidateEnforcement.validateEnforcementEscalate(dict));
});

Test.test("validateEnforcementEscalate: accepts floorTier as string", () => {
  let dict = {escalate: {floorTier: "fast"}};
  assertionNoThrow("floorTier string", () => ValidateEnforcement.validateEnforcementEscalate(dict));
});

Test.test("validateEnforcementEscalate: accepts floorTier as null", () => {
  let dict = {escalate: {floorTier: null}};
  assertionNoThrow("floorTier null", () => ValidateEnforcement.validateEnforcementEscalate(dict));
});

Test.test("validateEnforcementEscalate: passes silently when escalate is absent", () => {
  let dict = {mode: "off"};
  assertionNoThrow("absent escalate", () => ValidateEnforcement.validateEnforcementEscalate(dict));
});

Test.test("validateEnforcementEscalate: accepts zero maxAttemptsPerTier", () => {
  let dict = {escalate: {maxAttemptsPerTier: 0}};
  assertionNoThrow("zero maxAttemptsPerTier", () => ValidateEnforcement.validateEnforcementEscalate(dict));
});

Test.test("validateEnforcementPerTier: accepts a valid perTier object", () => {
  let dict = {perTier: {fast: "off", heavy: "enforced"}};
  assertionNoThrow("valid perTier", () => ValidateEnforcement.validateEnforcementPerTier(dict));
});

Test.test("validateEnforcementPerTier: passes silently when perTier is absent", () => {
  let dict = {mode: "off"};
  assertionNoThrow("absent perTier", () => ValidateEnforcement.validateEnforcementPerTier(dict));
});

Test.test("validateEnforcementGuard: accepts a valid guard block", () => {
  let dict = {guard: {budget: 100, blockScriptWrites: true}};
  assertionNoThrow("valid guard", () => ValidateEnforcement.validateEnforcementGuard(dict));
});

Test.test("validateEnforcementGuard: accepts guard with all optional fields", () => {
  let dict = {guard: {readDraftCap: 5, sameOpRetryCap: 3, blockSelfScript: true, deliverableFirst: false, budget: 500, blockScriptWrites: false}};
  assertionNoThrow("full guard", () => ValidateEnforcement.validateEnforcementGuard(dict));
});

Test.test("validateEnforcementGuard: passes silently when guard is absent", () => {
  let dict = {mode: "off"};
  assertionNoThrow("absent guard", () => ValidateEnforcement.validateEnforcementGuard(dict));
});

export {
  assertionNoThrow,
}
/*  Not a pure module */
