// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";

function getStringField(dict, key) {
  let json = Js_dict.get(dict, key);
  if (json === undefined) {
    return "";
  }
  let s = Js_json.decodeString(json);
  if (s !== undefined) {
    return s;
  } else {
    return "";
  }
}

function ensureIsObject(tier, presetName, tierName) {
  if (!(!(tier && typeof tier === 'object' && !Array.isArray(tier)))) {
    return;
  }
  throw Stdlib_Exn.raiseError(`tiers.json: tier '` + presetName + `.` + tierName + `' must be an object`);
}

function validateTier(presetName, tierName, tier) {
  ensureIsObject(tier, presetName, tierName);
  let modelVal = getStringField(tier, "model");
  if (modelVal === "") {
    throw Stdlib_Exn.raiseError(`tiers.json: '` + presetName + `.` + tierName + `.model' must be a non-empty string`);
  }
  let slashIdx = modelVal.indexOf("/");
  if (slashIdx <= 0 || slashIdx >= (modelVal.length - 1 | 0)) {
    throw Stdlib_Exn.raiseError(`tiers.json: '` + presetName + `.` + tierName + `.model' must be provider/model (got ` + modelVal + `)`);
  }
  let descVal = getStringField(tier, "description");
  if (descVal === "") {
    throw Stdlib_Exn.raiseError(`tiers.json: '` + presetName + `.` + tierName + `.description' must be a string`);
  }
  let json = Js_dict.get(tier, "whenToUse");
  if (json !== undefined) {
    let match = Js_json.decodeArray(json);
    if (match !== undefined) {
      return;
    }
    throw Stdlib_Exn.raiseError(`tiers.json: '` + presetName + `.` + tierName + `.whenToUse' must be an array`);
  }
  throw Stdlib_Exn.raiseError(`tiers.json: '` + presetName + `.` + tierName + `.whenToUse' must be an array`);
}

function ensurePresetIsObject(preset, presetName) {
  if (!(!(preset && typeof preset === 'object' && !Array.isArray(preset)))) {
    return;
  }
  throw Stdlib_Exn.raiseError(`tiers.json: preset '` + presetName + `' must be an object`);
}

function validatePreset(presetName, preset) {
  ensurePresetIsObject(preset, presetName);
  let keys = Stdlib_List.fromArray(Object.keys(preset));
  let _keys = keys;
  while (true) {
    let keys$1 = _keys;
    if (keys$1 === 0) {
      return;
    }
    let rest = keys$1.tl;
    let k = keys$1.hd;
    let tierJson = Js_dict.get(preset, k);
    if (tierJson !== undefined) {
      let tier = Js_json.decodeObject(tierJson);
      if (tier !== undefined) {
        validateTier(presetName, k, tier);
        _keys = rest;
        continue;
      }
      throw Stdlib_Exn.raiseError(`tiers.json: tier '` + presetName + `.` + k + `' must be an object`);
    }
    _keys = rest;
    continue;
  };
}

function ensureIsConfigObject(obj) {
  if (!(!(obj && typeof obj === 'object' && !Array.isArray(obj)))) {
    return;
  }
  throw Stdlib_Exn.raiseError("tiers.json: expected a JSON object at root");
}

function validatePresets(obj) {
  ensureIsConfigObject(obj);
  let json = Js_dict.get(obj, "presets");
  if (json !== undefined) {
    let presets = Js_json.decodeObject(json);
    if (presets !== undefined) {
      let keys = Object.keys(presets);
      let match = keys.length;
      if (match !== 0) {
        let _keys = Stdlib_List.fromArray(keys);
        while (true) {
          let keys$1 = _keys;
          if (keys$1 === 0) {
            return;
          }
          let rest = keys$1.tl;
          let k = keys$1.hd;
          let presetJson = Js_dict.get(presets, k);
          if (presetJson !== undefined) {
            let preset = Js_json.decodeObject(presetJson);
            if (preset !== undefined) {
              validatePreset(k, preset);
              _keys = rest;
              continue;
            }
            throw Stdlib_Exn.raiseError(`tiers.json: preset '` + k + `' must be an object`);
          }
          _keys = rest;
          continue;
        };
      }
      throw Stdlib_Exn.raiseError("tiers.json: 'presets' must have at least one preset");
    }
    throw Stdlib_Exn.raiseError("tiers.json: 'presets' must be a non-null object");
  }
  throw Stdlib_Exn.raiseError("tiers.json: 'presets' must be a non-null object");
}

export {
  validatePresets,
  validatePreset,
  validateTier,
}
/* No side effect */
