// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";

function ensureIsObject(val, path) {
  if (!(!(val && typeof val === 'object' && !Array.isArray(val)))) {
    return;
  }
  throw Stdlib_Exn.raiseError(`tiers.json: ` + path + ` must be an object`);
}

function validateMode(modeName, mode) {
  if ((!(mode && typeof mode === 'object' && !Array.isArray(mode)))) {
    throw Stdlib_Exn.raiseError(`tiers.json: mode '` + modeName + `' must be an object`);
  }
  let json = Js_dict.get(mode, "defaultTier");
  if (json !== undefined) {
    let match = Js_json.decodeString(json);
    if (match === undefined) {
      throw Stdlib_Exn.raiseError(`tiers.json: mode '` + modeName + `.defaultTier' must be a string`);
    }
  } else {
    throw Stdlib_Exn.raiseError(`tiers.json: mode '` + modeName + `.defaultTier' must be a string`);
  }
  let json$1 = Js_dict.get(mode, "description");
  if (json$1 !== undefined) {
    let match$1 = Js_json.decodeString(json$1);
    if (match$1 !== undefined) {
      return;
    }
    throw Stdlib_Exn.raiseError(`tiers.json: mode '` + modeName + `.description' must be a string`);
  }
  throw Stdlib_Exn.raiseError(`tiers.json: mode '` + modeName + `.description' must be a string`);
}

function validateModes(obj) {
  let json = Js_dict.get(obj, "modes");
  if (json === undefined) {
    return;
  }
  ensureIsObject(json, "'modes'");
  let modes = Js_json.decodeObject(json);
  if (modes !== undefined) {
    let keys = Object.keys(modes);
    let _keys = Stdlib_List.fromArray(keys);
    while (true) {
      let keys$1 = _keys;
      if (keys$1 === 0) {
        return;
      }
      let rest = keys$1.tl;
      let k = keys$1.hd;
      let modeJson = Js_dict.get(modes, k);
      if (modeJson !== undefined) {
        let mode = Js_json.decodeObject(modeJson);
        if (mode !== undefined) {
          validateMode(k, mode);
          _keys = rest;
          continue;
        }
        throw Stdlib_Exn.raiseError(`tiers.json: mode '` + k + `' must be an object`);
      }
      _keys = rest;
      continue;
    };
  }
  throw Stdlib_Exn.raiseError("tiers.json: 'modes' must be a non-null object");
}

export {
  validateModes,
  validateMode,
}
/* No side effect */
