// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function ensureIsObject(_val, path) {
  if (!(!(val && typeof val === 'object' && !Array.isArray(val)))) {
    return;
  }
  throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + path + ` must be an object`);
}

function validateMode(modeName, mode) {
  if ((!(mode && typeof mode === 'object' && !Array.isArray(mode)))) {
    throw Stdlib_JsError.throwWithMessage(`tiers.json: mode '` + modeName + `' must be an object`);
  }
  let json = mode["defaultTier"];
  if (json !== undefined) {
    let match = Stdlib_JSON.Decode.string(json);
    if (match === undefined) {
      throw Stdlib_JsError.throwWithMessage(`tiers.json: mode '` + modeName + `.defaultTier' must be a string`);
    }
  } else {
    throw Stdlib_JsError.throwWithMessage(`tiers.json: mode '` + modeName + `.defaultTier' must be a string`);
  }
  let json$1 = mode["description"];
  if (json$1 !== undefined) {
    let match$1 = Stdlib_JSON.Decode.string(json$1);
    if (match$1 !== undefined) {
      return;
    }
    throw Stdlib_JsError.throwWithMessage(`tiers.json: mode '` + modeName + `.description' must be a string`);
  }
  throw Stdlib_JsError.throwWithMessage(`tiers.json: mode '` + modeName + `.description' must be a string`);
}

function validateModes(obj) {
  let json = obj["modes"];
  if (json === undefined) {
    return;
  }
  ensureIsObject(json, "'modes'");
  let modes = Stdlib_JSON.Decode.object(json);
  if (modes !== undefined) {
    let keys = Object.keys(modes);
    let _keys = Stdlib_List.fromArray(keys);
    while (true) {
      let keys$1 = _keys;
      if (keys$1 === 0) {
        return;
      }
      let rest = keys$1.tl;
      let k = keys$1.hd;
      let modeJson = modes[k];
      if (modeJson !== undefined) {
        let mode = Stdlib_JSON.Decode.object(modeJson);
        if (mode !== undefined) {
          validateMode(k, mode);
          _keys = rest;
          continue;
        }
        throw Stdlib_JsError.throwWithMessage(`tiers.json: mode '` + k + `' must be an object`);
      }
      _keys = rest;
      continue;
    };
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: 'modes' must be a non-null object");
}

export {
  validateModes,
  validateMode,
}
/* No side effect */
