// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as ValidateReasoning from "./ValidateReasoning.res.mjs";

function assertionNoThrow(operator, fn) {
  Test.assertion(undefined, operator, (_a, _b) => true, (fn(), 0), 0);
}

Test.test("validateReasoningPolicy: accepts a valid reasoningPolicy object", () => {
  let dict = {reasoningPolicy: {mode: "static"}};
  assertionNoThrow("valid reasoningPolicy", () => ValidateReasoning.validateReasoningPolicy(dict));
});

Test.test("validateReasoningPolicy: passes silently when reasoningPolicy is absent", () => {
  let dict = {activePreset: "default"};
  assertionNoThrow("absent reasoningPolicy", () => ValidateReasoning.validateReasoningPolicy(dict));
});

Test.test("validateReasoningPolicyMode: accepts mode 'static'", () => {
  let dict = {mode: "static"};
  assertionNoThrow("mode static", () => ValidateReasoning.validateReasoningPolicyMode(dict));
});

Test.test("validateReasoningPolicyMode: accepts mode 'manual'", () => {
  let dict = {mode: "manual"};
  assertionNoThrow("mode manual", () => ValidateReasoning.validateReasoningPolicyMode(dict));
});

Test.test("validateReasoningPolicyMode: accepts mode 'adaptive'", () => {
  let dict = {mode: "adaptive"};
  assertionNoThrow("mode adaptive", () => ValidateReasoning.validateReasoningPolicyMode(dict));
});

Test.test("validateReasoningPolicyMode: passes silently when mode is absent", () => {
  let dict = {otherField: "value"};
  assertionNoThrow("absent mode", () => ValidateReasoning.validateReasoningPolicyMode(dict));
});

Test.test("validateAdaptivePolicy: accepts a valid adaptive object", () => {
  let dict = {adaptive: {defaultLevel: "normal"}};
  assertionNoThrow("valid adaptive", () => ValidateReasoning.validateAdaptivePolicy(dict));
});

Test.test("validateAdaptivePolicy: passes silently when adaptive is absent", () => {
  let dict = {mode: "static"};
  assertionNoThrow("absent adaptive", () => ValidateReasoning.validateAdaptivePolicy(dict));
});

Test.test("validateAdaptivePolicy: accepts trivialLevel as null", () => {
  let dict = {adaptive: {trivialLevel: null}};
  assertionNoThrow("trivialLevel null", () => ValidateReasoning.validateAdaptivePolicy(dict));
});

Test.test("validateAdaptivePolicy: accepts defaultLevel as null", () => {
  let dict = {adaptive: {defaultLevel: null}};
  assertionNoThrow("defaultLevel null", () => ValidateReasoning.validateAdaptivePolicy(dict));
});

Test.test("validateAdaptivePolicy: accepts valid keywordRules", () => {
  let dict = {adaptive: {keywordRules: [{keywords: ["bug"], level: "minimal"}]}};
  assertionNoThrow("valid keywordRules", () => ValidateReasoning.validateAdaptivePolicy(dict));
});

Test.test("validateAdaptivePolicy: accepts valid tierDefaults", () => {
  let dict = {adaptive: {tierDefaults: {fast: "minimal", heavy: "max"}}};
  assertionNoThrow("valid tierDefaults", () => ValidateReasoning.validateAdaptivePolicy(dict));
});

Test.test("validateAdaptivePolicy: accepts surfaceDecision as true", () => {
  let dict = {adaptive: {surfaceDecision: true}};
  assertionNoThrow("surfaceDecision true", () => ValidateReasoning.validateAdaptivePolicy(dict));
});

Test.test("validateAdaptivePolicy: accepts surfaceDecision as false", () => {
  let dict = {adaptive: {surfaceDecision: false}};
  assertionNoThrow("surfaceDecision false", () => ValidateReasoning.validateAdaptivePolicy(dict));
});

Test.test("validateKeywordRules: accepts empty keywordRules array", () => {
  let dict = {keywordRules: []};
  assertionNoThrow("empty keywordRules", () => ValidateReasoning.validateKeywordRules(dict));
});

Test.test("validateKeywordRule: accepts valid rule with level", () => {
  let rule = {keywords: ["bug", "error"], level: "minimal"};
  assertionNoThrow("valid rule", () => ValidateReasoning.validateKeywordRule(rule, 0));
});

Test.test("validateKeywordRule: accepts rule with match field", () => {
  let rule = {keywords: ["crash"], level: "minimal", match: "word"};
  assertionNoThrow("rule with match", () => ValidateReasoning.validateKeywordRule(rule, 0));
});

Test.test("validateKeywordRule: accepts rule with excludeKeywords", () => {
  let rule = {keywords: ["slow"], level: "normal", excludeKeywords: ["fast"]};
  assertionNoThrow("rule with excludeKeywords", () => ValidateReasoning.validateKeywordRule(rule, 0));
});

Test.test("validateKeywordRule: accepts rule with match=stem (default)", () => {
  let rule = {keywords: ["analyzing"], level: "elevated", match: "stem"};
  assertionNoThrow("rule with stem match", () => ValidateReasoning.validateKeywordRule(rule, 0));
});

Test.test("validateKeywordRule: accepts rule with match=substring", () => {
  let rule = {keywords: ["analyze"], level: "elevated", match: "substring"};
  assertionNoThrow("rule with substring match", () => ValidateReasoning.validateKeywordRule(rule, 0));
});

Test.test("validateKeywordRule: accepts rule with match=regex (valid pattern)", () => {
  let rule = {keywords: ["bug[0-9]+"], level: "minimal", match: "regex"};
  assertionNoThrow("valid regex", () => ValidateReasoning.validateKeywordRule(rule, 0));
});

Test.test("validateAdaptiveTierDefaults: accepts empty tierDefaults", () => {
  let dict = {tierDefaults: {}};
  assertionNoThrow("empty tierDefaults", () => ValidateReasoning.validateAdaptiveTierDefaults(dict));
});

Test.test("validateAdaptiveTierDefaults: accepts single tierDefault", () => {
  let dict = {tierDefaults: {fast: "minimal"}};
  assertionNoThrow("single tierDefault", () => ValidateReasoning.validateAdaptiveTierDefaults(dict));
});

Test.test("validateAdaptiveTierDefaults: passes silently when tierDefaults is absent", () => {
  let dict = {otherField: "value"};
  assertionNoThrow("absent tierDefaults", () => ValidateReasoning.validateAdaptiveTierDefaults(dict));
});

Test.test("validateAdaptiveSurfaceDecision: passes silently when surfaceDecision is absent", () => {
  let dict = {otherField: "value"};
  assertionNoThrow("absent surfaceDecision", () => ValidateReasoning.validateAdaptiveSurfaceDecision(dict));
});

export {
  assertionNoThrow,
}
/*  Not a pure module */
