// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as ValidateSimple from "./ValidateSimple.res.mjs";

function assertionNoThrow(operator, fn) {
  Test.assertion(undefined, operator, (_a, _b) => true, (fn(), 0), 0);
}

Test.test("validateTierCaps: accepts a valid tierCaps object with one cap", () => {
  let dict = {tierCaps: {fast: 100, heavy: 50}};
  assertionNoThrow("valid caps", () => ValidateSimple.validateTierCaps(dict));
});

Test.test("validateTierCaps: accepts tierCaps with various positive integers", () => {
  let dict = {tierCaps: {tier1: 1, tier2: 10, tier3: 1000}};
  assertionNoThrow("various positive ints", () => ValidateSimple.validateTierCaps(dict));
});

Test.test("validateTierCaps: passes silently when tierCaps is absent", () => {
  let dict = {activePreset: "default"};
  assertionNoThrow("absent tierCaps", () => ValidateSimple.validateTierCaps(dict));
});

Test.test("validateTierCaps: accepts tierCaps with large positive integers", () => {
  let dict = {tierCaps: {big: 999999999}};
  assertionNoThrow("large positive int", () => ValidateSimple.validateTierCaps(dict));
});

Test.test("validateTierPrompts: accepts a valid tierPrompts object with one prompt", () => {
  let dict = {tierPrompts: {fast: "Use fast model", heavy: "Use heavy model"}};
  assertionNoThrow("valid prompts", () => ValidateSimple.validateTierPrompts(dict));
});

Test.test("validateTierPrompts: accepts tierPrompts with various string values", () => {
  let dict = {tierPrompts: {tier1: "", tier2: "Hello", tier3: "Multi-word prompt"}};
  assertionNoThrow("various string prompts", () => ValidateSimple.validateTierPrompts(dict));
});

Test.test("validateTierPrompts: passes silently when tierPrompts is absent", () => {
  let dict = {activePreset: "default"};
  assertionNoThrow("absent tierPrompts", () => ValidateSimple.validateTierPrompts(dict));
});

Test.test("validateTierPrompts: accepts tierPrompts with empty string values", () => {
  let dict = {tierPrompts: {empty: ""}};
  assertionNoThrow("empty string prompt", () => ValidateSimple.validateTierPrompts(dict));
});

Test.test("validateTaskPatterns: accepts a valid taskPatterns object with one pattern array", () => {
  let dict = {taskPatterns: {read: ["*.md", "*.txt"], write: ["*.ts"]}};
  assertionNoThrow("valid patterns", () => ValidateSimple.validateTaskPatterns(dict));
});

Test.test("validateTaskPatterns: accepts taskPatterns with empty arrays", () => {
  let dict = {taskPatterns: {empty: []}};
  assertionNoThrow("empty pattern arrays", () => ValidateSimple.validateTaskPatterns(dict));
});

Test.test("validateTaskPatterns: passes silently when taskPatterns is absent", () => {
  let dict = {activePreset: "default"};
  assertionNoThrow("absent taskPatterns", () => ValidateSimple.validateTaskPatterns(dict));
});

Test.test("validateTaskPatterns: accepts taskPatterns with multiple patterns", () => {
  let dict = {taskPatterns: {docs: ["*.md", "*.rst", "*.adoc"]}};
  assertionNoThrow("multi-pattern array", () => ValidateSimple.validateTaskPatterns(dict));
});

export {
  assertionNoThrow,
}
/*  Not a pure module */
