// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as ValidateRoot from "./ValidateRoot.res.mjs";

function assertionNoThrow(operator, fn) {
  Test.assertion(undefined, operator, (_a, _b) => true, (fn(), 0), 0);
}

Test.test("validateRootFields: accepts non-empty string activePreset", () => {
  let dict = {};
  dict["activePreset"] = "anthropic";
  assertionNoThrow("valid activePreset", () => ValidateRoot.validateRootFields(dict));
});

Test.test("validateRootFields: accepts any non-empty string preset name", () => {
  let dict = {};
  dict["activePreset"] = "my-preset";
  assertionNoThrow("non-empty string", () => ValidateRoot.validateRootFields(dict));
});

Test.test("validateRulesAndDefaultTier: accepts rules array + string defaultTier", () => {
  let dict = {};
  dict["rules"] = [
    "rule1",
    "rule2"
  ];
  dict["defaultTier"] = "fast";
  assertionNoThrow("valid rules+defaultTier", () => ValidateRoot.validateRulesAndDefaultTier(dict));
});

Test.test("validateRulesAndDefaultTier: accepts empty rules array", () => {
  let dict = {};
  dict["rules"] = [];
  dict["defaultTier"] = "medium";
  assertionNoThrow("empty rules array", () => ValidateRoot.validateRulesAndDefaultTier(dict));
});

Test.test("validateRulesAndDefaultTier: accepts single-rule array", () => {
  let dict = {};
  dict["rules"] = ["only-rule"];
  dict["defaultTier"] = "heavy";
  assertionNoThrow("single rule", () => ValidateRoot.validateRulesAndDefaultTier(dict));
});

export {
  assertionNoThrow,
}
/*  Not a pure module */
