// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as ValidatePresets from "./ValidatePresets.res.mjs";

function assertionNoThrow(operator, fn) {
  Test.assertion(undefined, operator, (_a, _b) => true, (fn(), 0), 0);
}

Test.test("validatePresets: accepts a valid presets object with one preset", () => {
  let dict = {presets: {fast: {tier1: {model: "anthropic/claude-3-5-sonnet", description: "Fast tier", whenToUse: ["quick tasks"]}}}};
  assertionNoThrow("valid single-preset", () => ValidatePresets.validatePresets(dict));
});

Test.test("validatePresets: accepts multiple presets", () => {
  let dict = {presets: {fast: {tier1: {model: "anthropic/claude-3-5-sonnet", description: "Fast", whenToUse: ["quick"]}}, heavy: {tier1: {model: "anthropic/claude-3-5-opus", description: "Heavy", whenToUse: ["complex"]}}}};
  assertionNoThrow("valid multi-preset", () => ValidatePresets.validatePresets(dict));
});

Test.test("validatePreset: accepts a preset with a single tier", () => {
  let preset = {standard: {model: "openai/gpt-4o", description: "Standard tier", whenToUse: ["general"]}};
  assertionNoThrow("preset single tier", () => ValidatePresets.validatePreset("myPreset", preset));
});

Test.test("validatePreset: accepts a preset with multiple tiers", () => {
  let preset = {tier1: {model: "openai/gpt-4o", description: "Standard", whenToUse: ["general"]}, tier2: {model: "anthropic/claude-3-5-opus", description: "Premium", whenToUse: ["complex"]}};
  assertionNoThrow("preset multi tier", () => ValidatePresets.validatePreset("myPreset", preset));
});

Test.test("validateTier: accepts a fully-specified valid tier", () => {
  let tier = {model: "anthropic/claude-3-5-sonnet-20241022", description: "Fast and capable", whenToUse: ["quick tasks", "simple queries"]};
  assertionNoThrow("valid full tier", () => ValidatePresets.validateTier("myPreset", "fast", tier));
});

Test.test("validateTier: accepts model with provider/model slash format", () => {
  let tier = {model: "x/x", description: "Minimal", whenToUse: ["test"]};
  assertionNoThrow("valid slash model", () => ValidatePresets.validateTier("myPreset", "x", tier));
});

Test.test("validateTier: accepts whenToUse array with single element", () => {
  let tier = {model: "anthropic/claude-3-5-sonnet", description: "Desc", whenToUse: ["only"]};
  assertionNoThrow("single whenToUse", () => ValidatePresets.validateTier("myPreset", "t1", tier));
});

export {
  assertionNoThrow,
}
/*  Not a pure module */
