// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

let reasoningModes = [
  "static",
  "manual",
  "adaptive"
];

let reasoningLevels = [
  "minimal",
  "normal",
  "elevated",
  "max"
];

let matchModes = [
  "word",
  "stem",
  "substring",
  "regex"
];

function stringInArray(s, arr) {
  let _i = 0;
  while (true) {
    let i = _i;
    if (i >= arr.length) {
      return false;
    }
    if (arr[i] === s) {
      return true;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function isReasoningLevel(v) {
  let s = Stdlib_JSON.Decode.string(v);
  if (s !== undefined) {
    return stringInArray(s, reasoningLevels);
  } else {
    return false;
  }
}

function _testRegex(s) {
  try {
    new RegExp(s);
    return true;
  } catch (exn) {
    return false;
  }
}

function validateKeywordRule(ruleJson, index) {
  let prefix = `reasoningPolicy.adaptive.keywordRules[` + String(index) + `]`;
  if (Stdlib_Option.isNone(Stdlib_JSON.Decode.object(ruleJson))) {
    throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + prefix + ` must be an object`);
  }
  let rule = Stdlib_JSON.Decode.object(ruleJson);
  if (rule !== undefined) {
    let kwJson = rule["keywords"];
    if (kwJson !== undefined) {
      let kws = Stdlib_JSON.Decode.array(kwJson);
      if (kws !== undefined) {
        if (kws.length === 0) {
          throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + prefix + `.keywords must be a non-empty array of strings`);
        }
        let goKw = _i => {
          while (true) {
            let i = _i;
            if (i >= kws.length) {
              return;
            }
            let kw = kws[i];
            let match = Stdlib_JSON.Decode.string(kw);
            if (match !== undefined) {
              _i = i + 1 | 0;
              continue;
            }
            throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + prefix + `.keywords must be an array of strings`);
          };
        };
        goKw(0);
      } else {
        throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + prefix + `.keywords must be an array of strings`);
      }
    } else {
      throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + prefix + `.keywords must be an array of strings`);
    }
    let lvlJson = rule["level"];
    if (lvlJson !== undefined) {
      if (!isReasoningLevel(lvlJson)) {
        throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + prefix + `.level must be one of minimal|normal|elevated|max (got ` + JSON.stringify(lvlJson) + `)`);
      }
    } else {
      throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + prefix + `.level must be one of minimal|normal|elevated|max`);
    }
    let matchJson = rule["match"];
    if (matchJson !== undefined) {
      let m = Stdlib_JSON.Decode.string(matchJson);
      if (m !== undefined) {
        if (!stringInArray(m, matchModes)) {
          throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + prefix + `.match must be one of word|stem|substring|regex (got ` + JSON.stringify(matchJson) + `)`);
        }
      } else {
        throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + prefix + `.match must be one of word|stem|substring|regex (got ` + JSON.stringify(matchJson) + `)`);
      }
    }
    let exJson = rule["excludeKeywords"];
    if (exJson !== undefined) {
      let exs = Stdlib_JSON.Decode.array(exJson);
      if (exs !== undefined) {
        let goEx = _i => {
          while (true) {
            let i = _i;
            if (i >= exs.length) {
              return;
            }
            let ex = exs[i];
            let match = Stdlib_JSON.Decode.string(ex);
            if (match !== undefined) {
              _i = i + 1 | 0;
              continue;
            }
            throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + prefix + `.excludeKeywords must be an array of strings`);
          };
        };
        goEx(0);
      } else {
        throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + prefix + `.excludeKeywords must be an array of strings`);
      }
    }
    let matchJson$1 = rule["match"];
    if (matchJson$1 === undefined) {
      return;
    }
    let match = Stdlib_JSON.Decode.string(matchJson$1);
    if (match === undefined) {
      return;
    }
    if (match !== "regex") {
      return;
    }
    let kwJson$1 = rule["keywords"];
    if (kwJson$1 === undefined) {
      return;
    }
    let kws$1 = Stdlib_JSON.Decode.array(kwJson$1);
    if (kws$1 === undefined) {
      return;
    }
    let _i = 0;
    while (true) {
      let i = _i;
      if (i >= kws$1.length) {
        return;
      }
      let kw = kws$1[i];
      let kwStr = Stdlib_JSON.Decode.string(kw);
      if (kwStr !== undefined) {
        let valid = _testRegex(kwStr);
        if (!valid) {
          throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + prefix + ` has invalid regex '` + kwStr + `'`);
        }
        _i = i + 1 | 0;
        continue;
      }
      _i = i + 1 | 0;
      continue;
    };
  }
  throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + prefix + ` must be an object`);
}

function validateAdaptiveSurfaceDecision(adaptive) {
  let sdJson = adaptive["surfaceDecision"];
  if (sdJson === undefined) {
    return;
  }
  let match = Stdlib_JSON.Decode.bool(sdJson);
  if (match !== undefined) {
    return;
  }
  throw Stdlib_JsError.throwWithMessage(`tiers.json: reasoningPolicy.adaptive.surfaceDecision must be a boolean (got ` + JSON.stringify(sdJson) + `)`);
}

function validateAdaptiveTierDefaults(adaptive) {
  let json = adaptive["tierDefaults"];
  if (json === undefined) {
    return;
  }
  if (Stdlib_Option.isNone(Stdlib_JSON.Decode.object(json))) {
    throw Stdlib_JsError.throwWithMessage("tiers.json: reasoningPolicy.adaptive.tierDefaults must be an object");
  }
  let td = Stdlib_JSON.Decode.object(json);
  if (td !== undefined) {
    let keys = Object.keys(td);
    let _i = 0;
    while (true) {
      let i = _i;
      if (i >= keys.length) {
        return;
      }
      let k = keys[i];
      let lvlJson = td[k];
      if (lvlJson !== undefined && !isReasoningLevel(lvlJson)) {
        throw Stdlib_JsError.throwWithMessage(`tiers.json: reasoningPolicy.adaptive.tierDefaults.` + k + ` must be one of minimal|normal|elevated|max (got ` + JSON.stringify(lvlJson) + `)`);
      }
      _i = i + 1 | 0;
      continue;
    };
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: reasoningPolicy.adaptive.tierDefaults must be an object");
}

function validateLevelOrNull(obj, key, path) {
  let json = obj[key];
  if (json === undefined) {
    return;
  }
  let match = Stdlib_JSON.Decode.$$null(json);
  if (match !== undefined) {
    return;
  }
  if (isReasoningLevel(json)) {
    return;
  }
  throw Stdlib_JsError.throwWithMessage(`tiers.json: ` + path + ` must be one of minimal|normal|elevated|max or null (got ` + JSON.stringify(json) + `)`);
}

function validateKeywordRules(adaptive) {
  let json = adaptive["keywordRules"];
  if (json === undefined) {
    return;
  }
  let rules = Stdlib_JSON.Decode.array(json);
  if (rules !== undefined) {
    let _i = 0;
    while (true) {
      let i = _i;
      if (i >= rules.length) {
        return;
      }
      let ruleJson = rules[i];
      validateKeywordRule(ruleJson, i);
      _i = i + 1 | 0;
      continue;
    };
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: reasoningPolicy.adaptive.keywordRules must be an array");
}

function validateAdaptivePolicy(policy) {
  let json = policy["adaptive"];
  if (json === undefined) {
    return;
  }
  if (Stdlib_Option.isNone(Stdlib_JSON.Decode.object(json))) {
    throw Stdlib_JsError.throwWithMessage("tiers.json: reasoningPolicy.adaptive must be an object");
  }
  let adaptive = Stdlib_JSON.Decode.object(json);
  if (adaptive !== undefined) {
    validateLevelOrNull(adaptive, "trivialLevel", "reasoningPolicy.adaptive.trivialLevel");
    validateLevelOrNull(adaptive, "defaultLevel", "reasoningPolicy.adaptive.defaultLevel");
    validateKeywordRules(adaptive);
    validateAdaptiveTierDefaults(adaptive);
    return validateAdaptiveSurfaceDecision(adaptive);
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: reasoningPolicy.adaptive must be an object");
}

function validateReasoningPolicyMode(policy) {
  let modeJson = policy["mode"];
  if (modeJson === undefined) {
    return;
  }
  let mode = Stdlib_JSON.Decode.string(modeJson);
  if (mode !== undefined) {
    if (stringInArray(mode, reasoningModes)) {
      return;
    }
    throw Stdlib_JsError.throwWithMessage(`tiers.json: reasoningPolicy.mode must be one of static|manual|adaptive (got ` + JSON.stringify(modeJson) + `)`);
  }
  throw Stdlib_JsError.throwWithMessage(`tiers.json: reasoningPolicy.mode must be one of static|manual|adaptive (got ` + JSON.stringify(modeJson) + `)`);
}

function validateReasoningPolicy(obj) {
  let json = obj["reasoningPolicy"];
  if (json === undefined) {
    return;
  }
  if (Stdlib_Option.isNone(Stdlib_JSON.Decode.object(json))) {
    throw Stdlib_JsError.throwWithMessage("tiers.json: 'reasoningPolicy' must be an object");
  }
  let policy = Stdlib_JSON.Decode.object(json);
  if (policy !== undefined) {
    validateReasoningPolicyMode(policy);
    return validateAdaptivePolicy(policy);
  }
  throw Stdlib_JsError.throwWithMessage("tiers.json: 'reasoningPolicy' must be an object");
}

export {
  validateReasoningPolicy,
  validateReasoningPolicyMode,
  validateAdaptivePolicy,
  validateKeywordRules,
  validateKeywordRule,
  validateAdaptiveTierDefaults,
  validateAdaptiveSurfaceDecision,
}
/* No side effect */
