// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";

let reasoningModes = [
  "static",
  "manual",
  "adaptive"
];

let reasoningLevels = [
  "minimal",
  "normal",
  "elevated",
  "max"
];

let matchModes = [
  "word",
  "stem",
  "substring",
  "regex"
];

function stringInArray(s, arr) {
  let _i = 0;
  while (true) {
    let i = _i;
    if (i >= arr.length) {
      return false;
    }
    if (arr[i] === s) {
      return true;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function isReasoningLevel(v) {
  let s = Js_json.decodeString(v);
  if (s !== undefined) {
    return stringInArray(s, reasoningLevels);
  } else {
    return false;
  }
}

function _testRegex(s) {
  return ((function(s) { try { new RegExp(s); return true; } catch(e) { return false; } })(arguments[0]));
}

function validateKeywordRule(ruleJson, index) {
  let prefix = `reasoningPolicy.adaptive.keywordRules[` + String(index) + `]`;
  if ((!(ruleJson && typeof ruleJson === 'object' && !Array.isArray(ruleJson)))) {
    throw Stdlib_Exn.raiseError(`tiers.json: ` + prefix + ` must be an object`);
  }
  let rule = Js_json.decodeObject(ruleJson);
  if (rule !== undefined) {
    let kwJson = Js_dict.get(rule, "keywords");
    if (kwJson !== undefined) {
      let kws = Js_json.decodeArray(kwJson);
      if (kws !== undefined) {
        if (kws.length === 0) {
          throw Stdlib_Exn.raiseError(`tiers.json: ` + prefix + `.keywords must be a non-empty array of strings`);
        }
        let goKw = _i => {
          while (true) {
            let i = _i;
            if (i >= kws.length) {
              return;
            }
            let kw = kws[i];
            let match = Js_json.decodeString(kw);
            if (match !== undefined) {
              _i = i + 1 | 0;
              continue;
            }
            throw Stdlib_Exn.raiseError(`tiers.json: ` + prefix + `.keywords must be an array of strings`);
          };
        };
        goKw(0);
      } else {
        throw Stdlib_Exn.raiseError(`tiers.json: ` + prefix + `.keywords must be an array of strings`);
      }
    } else {
      throw Stdlib_Exn.raiseError(`tiers.json: ` + prefix + `.keywords must be an array of strings`);
    }
    let lvlJson = Js_dict.get(rule, "level");
    if (lvlJson !== undefined) {
      if (!isReasoningLevel(lvlJson)) {
        throw Stdlib_Exn.raiseError(`tiers.json: ` + prefix + `.level must be one of minimal|normal|elevated|max (got ` + JSON.stringify(lvlJson) + `)`);
      }
    } else {
      throw Stdlib_Exn.raiseError(`tiers.json: ` + prefix + `.level must be one of minimal|normal|elevated|max`);
    }
    let matchJson = Js_dict.get(rule, "match");
    if (matchJson !== undefined) {
      let m = Js_json.decodeString(matchJson);
      if (m !== undefined) {
        if (!stringInArray(m, matchModes)) {
          throw Stdlib_Exn.raiseError(`tiers.json: ` + prefix + `.match must be one of word|stem|substring|regex (got ` + JSON.stringify(matchJson) + `)`);
        }
      } else {
        throw Stdlib_Exn.raiseError(`tiers.json: ` + prefix + `.match must be one of word|stem|substring|regex (got ` + JSON.stringify(matchJson) + `)`);
      }
    }
    let exJson = Js_dict.get(rule, "excludeKeywords");
    if (exJson !== undefined) {
      let exs = Js_json.decodeArray(exJson);
      if (exs !== undefined) {
        let goEx = _i => {
          while (true) {
            let i = _i;
            if (i >= exs.length) {
              return;
            }
            let ex = exs[i];
            let match = Js_json.decodeString(ex);
            if (match !== undefined) {
              _i = i + 1 | 0;
              continue;
            }
            throw Stdlib_Exn.raiseError(`tiers.json: ` + prefix + `.excludeKeywords must be an array of strings`);
          };
        };
        goEx(0);
      } else {
        throw Stdlib_Exn.raiseError(`tiers.json: ` + prefix + `.excludeKeywords must be an array of strings`);
      }
    }
    let matchJson$1 = Js_dict.get(rule, "match");
    if (matchJson$1 === undefined) {
      return;
    }
    let match = Js_json.decodeString(matchJson$1);
    if (match === undefined) {
      return;
    }
    if (match !== "regex") {
      return;
    }
    let kwJson$1 = Js_dict.get(rule, "keywords");
    if (kwJson$1 === undefined) {
      return;
    }
    let kws$1 = Js_json.decodeArray(kwJson$1);
    if (kws$1 === undefined) {
      return;
    }
    let _i = 0;
    while (true) {
      let i = _i;
      if (i >= kws$1.length) {
        return;
      }
      let kw = kws$1[i];
      let kwStr = Js_json.decodeString(kw);
      if (kwStr !== undefined) {
        let valid = _testRegex(kwStr);
        if (!valid) {
          throw Stdlib_Exn.raiseError(`tiers.json: ` + prefix + ` has invalid regex '` + kwStr + `'`);
        }
        _i = i + 1 | 0;
        continue;
      }
      _i = i + 1 | 0;
      continue;
    };
  }
  throw Stdlib_Exn.raiseError(`tiers.json: ` + prefix + ` must be an object`);
}

function validateAdaptiveTierDefaults(adaptive) {
  let json = Js_dict.get(adaptive, "tierDefaults");
  if (json === undefined) {
    return;
  }
  if ((!(json && typeof json === 'object' && !Array.isArray(json)))) {
    throw Stdlib_Exn.raiseError("tiers.json: reasoningPolicy.adaptive.tierDefaults must be an object");
  }
  let td = Js_json.decodeObject(json);
  if (td !== undefined) {
    let keys = Object.keys(td);
    let _i = 0;
    while (true) {
      let i = _i;
      if (i >= keys.length) {
        return;
      }
      let k = keys[i];
      let lvlJson = Js_dict.get(td, k);
      if (lvlJson !== undefined && !isReasoningLevel(lvlJson)) {
        throw Stdlib_Exn.raiseError(`tiers.json: reasoningPolicy.adaptive.tierDefaults.` + k + ` must be one of minimal|normal|elevated|max (got ` + JSON.stringify(lvlJson) + `)`);
      }
      _i = i + 1 | 0;
      continue;
    };
  }
  throw Stdlib_Exn.raiseError("tiers.json: reasoningPolicy.adaptive.tierDefaults must be an object");
}

function validateKeywordRules(adaptive) {
  let json = Js_dict.get(adaptive, "keywordRules");
  if (json === undefined) {
    return;
  }
  let rules = Js_json.decodeArray(json);
  if (rules !== undefined) {
    let _i = 0;
    while (true) {
      let i = _i;
      if (i >= rules.length) {
        return;
      }
      let ruleJson = rules[i];
      validateKeywordRule(ruleJson, i);
      _i = i + 1 | 0;
      continue;
    };
  }
  throw Stdlib_Exn.raiseError("tiers.json: reasoningPolicy.adaptive.keywordRules must be an array");
}

function validateAdaptiveSurfaceDecision(adaptive) {
  let sdJson = Js_dict.get(adaptive, "surfaceDecision");
  if (sdJson === undefined) {
    return;
  }
  let match = Js_json.decodeBoolean(sdJson);
  if (match !== undefined) {
    return;
  }
  throw Stdlib_Exn.raiseError(`tiers.json: reasoningPolicy.adaptive.surfaceDecision must be a boolean (got ` + JSON.stringify(sdJson) + `)`);
}

function validateLevelOrNull(obj, key, path) {
  let json = Js_dict.get(obj, key);
  if (json === undefined) {
    return;
  }
  if ((json === null)) {
    return;
  }
  if (isReasoningLevel(json)) {
    return;
  }
  throw Stdlib_Exn.raiseError(`tiers.json: ` + path + ` must be one of minimal|normal|elevated|max or null (got ` + JSON.stringify(json) + `)`);
}

function validateReasoningPolicyMode(policy) {
  let modeJson = Js_dict.get(policy, "mode");
  if (modeJson === undefined) {
    return;
  }
  let mode = Js_json.decodeString(modeJson);
  if (mode !== undefined) {
    if (stringInArray(mode, reasoningModes)) {
      return;
    }
    throw Stdlib_Exn.raiseError(`tiers.json: reasoningPolicy.mode must be one of static|manual|adaptive (got ` + JSON.stringify(modeJson) + `)`);
  }
  throw Stdlib_Exn.raiseError(`tiers.json: reasoningPolicy.mode must be one of static|manual|adaptive (got ` + JSON.stringify(modeJson) + `)`);
}

function validateAdaptivePolicy(policy) {
  let json = Js_dict.get(policy, "adaptive");
  if (json === undefined) {
    return;
  }
  if ((!(json && typeof json === 'object' && !Array.isArray(json)))) {
    throw Stdlib_Exn.raiseError("tiers.json: reasoningPolicy.adaptive must be an object");
  }
  let adaptive = Js_json.decodeObject(json);
  if (adaptive !== undefined) {
    validateLevelOrNull(adaptive, "trivialLevel", "reasoningPolicy.adaptive.trivialLevel");
    validateLevelOrNull(adaptive, "defaultLevel", "reasoningPolicy.adaptive.defaultLevel");
    validateKeywordRules(adaptive);
    validateAdaptiveTierDefaults(adaptive);
    return validateAdaptiveSurfaceDecision(adaptive);
  }
  throw Stdlib_Exn.raiseError("tiers.json: reasoningPolicy.adaptive must be an object");
}

function validateReasoningPolicy(obj) {
  let json = Js_dict.get(obj, "reasoningPolicy");
  if (json === undefined) {
    return;
  }
  if ((!(json && typeof json === 'object' && !Array.isArray(json)))) {
    throw Stdlib_Exn.raiseError("tiers.json: 'reasoningPolicy' must be an object");
  }
  let policy = Js_json.decodeObject(json);
  if (policy !== undefined) {
    validateReasoningPolicyMode(policy);
    return validateAdaptivePolicy(policy);
  }
  throw Stdlib_Exn.raiseError("tiers.json: 'reasoningPolicy' must be an object");
}

export {
  validateReasoningPolicy,
  validateReasoningPolicyMode,
  validateAdaptivePolicy,
  validateKeywordRules,
  validateKeywordRule,
  validateAdaptiveTierDefaults,
  validateAdaptiveSurfaceDecision,
}
/* No side effect */
