// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";

function validateRootFields(obj) {
  let json = Js_dict.get(obj, "activePreset");
  if (json !== undefined) {
    let s = Js_json.decodeString(json);
    if (s !== undefined) {
      if (s !== "") {
        return;
      }
      throw Stdlib_Exn.raiseError("tiers.json: 'activePreset' must be a non-empty string");
    }
    throw Stdlib_Exn.raiseError("tiers.json: 'activePreset' must be a non-empty string");
  }
  throw Stdlib_Exn.raiseError("tiers.json: 'activePreset' must be a non-empty string");
}

function checkStringArray(_arr) {
  while (true) {
    let arr = _arr;
    if (arr === 0) {
      return;
    }
    let match = Js_json.decodeString(arr.hd);
    if (match !== undefined) {
      _arr = arr.tl;
      continue;
    }
    throw Stdlib_Exn.raiseError("tiers.json: 'rules' must be an array of strings");
  };
}

function validateRulesAndDefaultTier(obj) {
  let json = Js_dict.get(obj, "rules");
  if (json !== undefined) {
    let arr = Js_json.decodeArray(json);
    if (arr !== undefined) {
      checkStringArray(Stdlib_List.fromArray(arr));
    } else {
      throw Stdlib_Exn.raiseError("tiers.json: 'rules' must be an array of strings");
    }
  } else {
    throw Stdlib_Exn.raiseError("tiers.json: 'rules' must be an array of strings");
  }
  let json$1 = Js_dict.get(obj, "defaultTier");
  if (json$1 !== undefined) {
    let s = Js_json.decodeString(json$1);
    if (s !== undefined) {
      if (s !== "") {
        return;
      }
      throw Stdlib_Exn.raiseError("tiers.json: 'defaultTier' must be a string");
    }
    throw Stdlib_Exn.raiseError("tiers.json: 'defaultTier' must be a string");
  }
  throw Stdlib_Exn.raiseError("tiers.json: 'defaultTier' must be a string");
}

export {
  validateRootFields,
  validateRulesAndDefaultTier,
}
/* No side effect */
