// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Js_math from "@rescript/runtime/lib/es6/Js_math.js";
import * as Js_array from "@rescript/runtime/lib/es6/Js_array.js";
import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Stdlib_Float from "@rescript/runtime/lib/es6/Stdlib_Float.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let reasoningLevels = [
  "minimal",
  "normal",
  "elevated",
  "max"
];

function decodeLevel(s) {
  if (Js_array.includes(s, reasoningLevels)) {
    return s;
  }
}

function isValidRegex(s) {
  try {
    ((new RegExp(s)));
    return true;
  } catch (exn) {
    return false;
  }
}

function validateRegexKeywords(keywords) {
  let _arr = Stdlib_List.fromArray(keywords);
  while (true) {
    let arr = _arr;
    if (arr === 0) {
      return true;
    }
    if (!isValidRegex(arr.hd)) {
      return false;
    }
    _arr = arr.tl;
    continue;
  };
}

function optLevelField(obj, key) {
  let json = Js_dict.get(obj, key);
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeString(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let v = decodeLevel(match$1);
  if (v !== undefined) {
    return Primitive_option.some(v);
  }
}

function validateTierDefaultsDict(dictObj) {
  let _keys = Stdlib_List.fromArray(Object.keys(dictObj));
  let acc = {};
  while (true) {
    let keys = _keys;
    if (keys === 0) {
      return acc;
    }
    let ks = keys.tl;
    let k = keys.hd;
    let v = Js_dict.get(dictObj, k);
    if (v !== undefined) {
      let s = Js_json.decodeString(v);
      if (s === undefined) {
        return;
      }
      let valid = decodeLevel(s);
      if (valid === undefined) {
        return;
      }
      acc[k] = valid;
      _keys = ks;
      continue;
    }
    _keys = ks;
    continue;
  };
}

function decodeStringArray(arr) {
  let go = (_arr, _acc) => {
    while (true) {
      let acc = _acc;
      let arr = _arr;
      if (arr === 0) {
        return acc;
      }
      let s = Js_json.decodeString(arr.hd);
      if (s === undefined) {
        return;
      }
      _acc = {
        hd: s,
        tl: acc
      };
      _arr = arr.tl;
      continue;
    };
  };
  let l = go(Stdlib_List.fromArray(arr), /* [] */0);
  if (l !== undefined) {
    return Stdlib_List.toArray(Stdlib_List.reverse(l));
  }
}

function optStr(obj, key) {
  let json = Js_dict.get(obj, key);
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeString(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  } else if (match$1 !== undefined) {
    return Primitive_option.some(match$1);
  } else {
    return;
  }
}

function optNum(obj, key) {
  let json = Js_dict.get(obj, key);
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeNumber(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  } else if (match$1 !== undefined) {
    return Primitive_option.some(match$1);
  } else {
    return;
  }
}

function optBool(obj, key) {
  let json = Js_dict.get(obj, key);
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeBoolean(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  } else if (match$1 !== undefined) {
    return Primitive_option.some(match$1);
  } else {
    return;
  }
}

function optInt(obj, key) {
  let json = Js_dict.get(obj, key);
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeNumber(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  } else if (match$1 !== undefined) {
    return Primitive_option.some(match$1 | 0);
  } else {
    return;
  }
}

function reqStr(obj, key) {
  let json = Js_dict.get(obj, key);
  if (json !== undefined) {
    return Js_json.decodeString(json);
  }
}

function reqArr(obj, key) {
  let json = Js_dict.get(obj, key);
  if (json !== undefined) {
    return Js_json.decodeArray(json);
  }
}

function reqObj(obj, key) {
  let json = Js_dict.get(obj, key);
  if (json !== undefined) {
    return Js_json.decodeObject(json);
  }
}

function optStringArray(obj, key) {
  let json = Js_dict.get(obj, key);
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeArray(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let a = decodeStringArray(match$1);
  if (a !== undefined) {
    return Primitive_option.some(a);
  }
}

function optStringDict(obj, key) {
  let go = (_keys, dictObj, acc) => {
    while (true) {
      let keys = _keys;
      if (keys === 0) {
        return acc;
      }
      let ks = keys.tl;
      let k = keys.hd;
      let v = Js_dict.get(dictObj, k);
      if (v !== undefined) {
        let s = Js_json.decodeString(v);
        if (s === undefined) {
          return;
        }
        acc[k] = s;
        _keys = ks;
        continue;
      }
      _keys = ks;
      continue;
    };
  };
  let json = Js_dict.get(obj, key);
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let d = go(Stdlib_List.fromArray(Object.keys(match$1)), match$1, {});
  if (d !== undefined) {
    return Primitive_option.some(d);
  }
}

function optIntDict(obj, key) {
  let go = (_keys, dictObj, acc) => {
    while (true) {
      let keys = _keys;
      if (keys === 0) {
        return acc;
      }
      let ks = keys.tl;
      let k = keys.hd;
      let v = Js_dict.get(dictObj, k);
      if (v !== undefined) {
        let n = Js_json.decodeNumber(v);
        if (n === undefined) {
          return;
        }
        acc[k] = Js_math.floor(n);
        _keys = ks;
        continue;
      }
      _keys = ks;
      continue;
    };
  };
  let json = Js_dict.get(obj, key);
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let d = go(Stdlib_List.fromArray(Object.keys(match$1)), match$1, {});
  if (d !== undefined) {
    return Primitive_option.some(d);
  }
}

function optFloatDict(obj, key) {
  let go = (_keys, dictObj, acc) => {
    while (true) {
      let keys = _keys;
      if (keys === 0) {
        return acc;
      }
      let ks = keys.tl;
      let k = keys.hd;
      let v = Js_dict.get(dictObj, k);
      if (v !== undefined) {
        let n = Js_json.decodeNumber(v);
        if (n === undefined) {
          return;
        }
        acc[k] = n;
        _keys = ks;
        continue;
      }
      _keys = ks;
      continue;
    };
  };
  let json = Js_dict.get(obj, key);
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let d = go(Stdlib_List.fromArray(Object.keys(match$1)), match$1, {});
  if (d !== undefined) {
    return Primitive_option.some(d);
  }
}

function decodeMode(obj) {
  let json = Js_dict.get(obj, "mode");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeString(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  switch (match$1) {
    case "advisory" :
      return "advisory";
    case "enforced" :
      return "enforced";
    case "off" :
      return "off";
    default:
      return;
  }
}

function decodeCapability(obj) {
  let json = Js_dict.get(obj, "capability");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let match$2 = reqStr(match$1, "kind");
  if (match$2 === undefined) {
    return;
  }
  switch (match$2) {
    case "binary" :
      let match$3 = reqStr(match$1, "field");
      let match$4 = optStr(match$1, "baseline");
      let match$5 = reqStr(match$1, "elevated");
      if (match$3 !== undefined && match$4 !== undefined && match$5 !== undefined) {
        return Primitive_option.some({
          TAG: "Binary",
          field: match$3,
          baseline: Primitive_option.valFromOption(match$4),
          elevated: match$5
        });
      } else {
        return;
      }
    case "budgeted" :
      let match$6 = reqStr(match$1, "field");
      let match$7 = optFloatDict(match$1, "recommended");
      if (match$6 === undefined) {
        return;
      }
      if (match$7 === undefined) {
        return;
      }
      let recF = Primitive_option.valFromOption(match$7);
      if (recF !== undefined) {
        return Primitive_option.some({
          TAG: "Budgeted",
          field: match$6,
          recommended: recF
        });
      } else {
        return;
      }
    case "discrete" :
      let match$8 = reqStr(match$1, "field");
      let match$9 = reqArr(match$1, "levels");
      if (match$8 === undefined) {
        return;
      }
      if (match$9 === undefined) {
        return;
      }
      let levelsList = decodeStringArray(match$9);
      if (levelsList !== undefined) {
        return Primitive_option.some({
          TAG: "Discrete",
          field: match$8,
          levels: levelsList
        });
      } else {
        return;
      }
    case "none" :
      return "TC_None";
    default:
      return;
  }
}

function decodeThinking(obj) {
  let json = Js_dict.get(obj, "thinking");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let tokJson = Js_dict.get(match$1, "budgetTokens");
  if (tokJson === undefined) {
    return {
      budgetTokens: undefined
    };
  }
  let match$2 = Js_json.decodeNull(tokJson);
  let match$3 = Js_json.decodeString(tokJson);
  let match$4 = Js_json.decodeNumber(tokJson);
  if (match$2 !== undefined) {
    return {
      budgetTokens: undefined
    };
  }
  if (match$3 === undefined) {
    if (match$4 !== undefined) {
      return Primitive_option.some({
        budgetTokens: match$4 | 0
      });
    } else {
      return;
    }
  }
  let n = Stdlib_Float.fromString(match$3);
  if (n !== undefined) {
    return Primitive_option.some({
      budgetTokens: n | 0
    });
  } else {
    return {
      budgetTokens: undefined
    };
  }
}

function decodeReasoning(obj) {
  let json = Js_dict.get(obj, "reasoning");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let match$2 = optStr(match$1, "effort");
  let match$3 = optStr(match$1, "summary");
  if (match$2 !== undefined && match$3 !== undefined) {
    return Primitive_option.some({
      effort: Primitive_option.valFromOption(match$2),
      summary: Primitive_option.valFromOption(match$3)
    });
  }
}

function decodeTier(obj) {
  let model = reqStr(obj, "model");
  if (model === undefined) {
    return;
  }
  if (Js_string.indexOf("/", model) < 0) {
    return;
  }
  let match = reqStr(obj, "description");
  let match$1 = reqArr(obj, "whenToUse");
  if (match === undefined) {
    return;
  }
  if (match$1 === undefined) {
    return;
  }
  let whenToUse = decodeStringArray(match$1);
  if (whenToUse === undefined) {
    return;
  }
  let variant = optStr(obj, "variant");
  let costRatio = optNum(obj, "costRatio");
  let thinking = decodeThinking(obj);
  let reasoning = decodeReasoning(obj);
  let capability = decodeCapability(obj);
  if (variant !== undefined && costRatio !== undefined && thinking !== undefined && reasoning !== undefined && capability !== undefined) {
    return {
      model: model,
      variant: Primitive_option.valFromOption(variant),
      costRatio: Primitive_option.valFromOption(costRatio),
      description: match,
      whenToUse: whenToUse,
      thinking: Primitive_option.valFromOption(thinking),
      reasoning: Primitive_option.valFromOption(reasoning),
      capability: Primitive_option.valFromOption(capability)
    };
  }
}

function decodeKeywordRules(obj) {
  let go = (_arr, _acc) => {
    while (true) {
      let acc = _acc;
      let arr = _arr;
      if (arr === 0) {
        return acc;
      }
      let rest = arr.tl;
      let ruleObj = Js_json.decodeObject(arr.hd);
      if (ruleObj !== undefined) {
        let match = optStringArray(ruleObj, "keywords");
        let match$1 = reqStr(ruleObj, "level");
        if (match !== undefined) {
          let keywords = Primitive_option.valFromOption(match);
          if (keywords !== undefined && match$1 !== undefined) {
            let validLevel = decodeLevel(match$1);
            if (validLevel === undefined) {
              return;
            }
            if (keywords.length === 0) {
              return;
            }
            let match$2 = optStr(ruleObj, "match");
            let match$3 = optStringArray(ruleObj, "excludeKeywords");
            if (match$2 === undefined) {
              return;
            }
            if (match$3 === undefined) {
              return;
            }
            let excludeKeywords = Primitive_option.valFromOption(match$3);
            let match_ = Primitive_option.valFromOption(match$2);
            if (match_ !== undefined) {
              if (match_ === "regex" && !validateRegexKeywords(keywords)) {
                return;
              }
              let kr_match = match_;
              let kr = {
                keywords: keywords,
                level: validLevel,
                match: kr_match,
                excludeKeywords: excludeKeywords
              };
              _acc = {
                hd: kr,
                tl: acc
              };
              _arr = rest;
              continue;
            }
            let kr$1 = {
              keywords: keywords,
              level: validLevel,
              match: undefined,
              excludeKeywords: excludeKeywords
            };
            _acc = {
              hd: kr$1,
              tl: acc
            };
            _arr = rest;
            continue;
          }
        }
        throw {
          RE_EXN_ID: "Match_failure",
          _1: [
            "Config.res",
            559,
            8
          ],
          Error: new Error()
        };
      }
      throw {
        RE_EXN_ID: "Match_failure",
        _1: [
          "Config.res",
          557,
          6
        ],
        Error: new Error()
      };
    };
  };
  let json = Js_dict.get(obj, "keywordRules");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeArray(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let l = go(Stdlib_List.fromArray(match$1), /* [] */0);
  if (l !== undefined) {
    return Primitive_option.some(Stdlib_List.toArray(Stdlib_List.reverse(l)));
  }
}

function decodeAdaptive(obj) {
  let json = Js_dict.get(obj, "adaptive");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let match$2 = optLevelField(match$1, "trivialLevel");
  let match$3 = optLevelField(match$1, "defaultLevel");
  let match$4 = decodeKeywordRules(match$1);
  if (match$2 === undefined) {
    return;
  }
  if (match$3 === undefined) {
    return;
  }
  if (match$4 === undefined) {
    return;
  }
  let keywordRules = Primitive_option.valFromOption(match$4);
  let defaultLevel = Primitive_option.valFromOption(match$3);
  let trivialLevel = Primitive_option.valFromOption(match$2);
  let sd = optBool(match$1, "surfaceDecision");
  if (sd === undefined) {
    return;
  }
  let sd$1 = Primitive_option.valFromOption(sd);
  let json$1 = Js_dict.get(match$1, "tierDefaults");
  if (json$1 !== undefined) {
    let match$5 = Js_json.decodeNull(json$1);
    let match$6 = Js_json.decodeObject(json$1);
    if (match$5 !== undefined) {
      return Primitive_option.some(undefined);
    }
    if (match$6 === undefined) {
      return;
    }
    let tierDefaults = validateTierDefaultsDict(match$6);
    if (tierDefaults !== undefined) {
      return Primitive_option.some({
        trivialLevel: trivialLevel,
        defaultLevel: defaultLevel,
        keywordRules: keywordRules,
        tierDefaults: tierDefaults,
        surfaceDecision: sd$1
      });
    } else {
      return;
    }
  }
  let tierDefaults$1 = {};
  return Primitive_option.some({
    trivialLevel: trivialLevel,
    defaultLevel: defaultLevel,
    keywordRules: keywordRules,
    tierDefaults: tierDefaults$1,
    surfaceDecision: sd$1
  });
}

function decodeReasoningPolicy(obj) {
  let json = Js_dict.get(obj, "reasoningPolicy");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let match$2 = optStr(match$1, "mode");
  let match$3 = optLevelField(match$1, "defaultLevel");
  let match$4 = optBool(match$1, "surfaceLimits");
  let match$5 = decodeAdaptive(match$1);
  if (match$2 !== undefined && match$3 !== undefined && match$4 !== undefined && match$5 !== undefined) {
    return Primitive_option.some({
      mode: Primitive_option.valFromOption(match$2),
      defaultLevel: Primitive_option.valFromOption(match$3),
      surfaceLimits: Primitive_option.valFromOption(match$4),
      adaptive: Primitive_option.valFromOption(match$5)
    });
  }
}

function decodeModes(obj) {
  let go = (_keys, dictObj, acc) => {
    while (true) {
      let keys = _keys;
      if (keys === 0) {
        return acc;
      }
      let ks = keys.tl;
      let k = keys.hd;
      let v = Js_dict.get(dictObj, k);
      if (v !== undefined) {
        let entryObj = Js_json.decodeObject(v);
        if (entryObj !== undefined) {
          let match = reqStr(entryObj, "defaultTier");
          let match$1 = reqStr(entryObj, "description");
          if (match !== undefined) {
            if (match$1 !== undefined) {
              let overrideRules = optStringArray(entryObj, "overrideRules");
              if (overrideRules === undefined) {
                return;
              }
              let entry_overrideRules = Primitive_option.valFromOption(overrideRules);
              let entry = {
                defaultTier: match,
                description: match$1,
                overrideRules: entry_overrideRules
              };
              acc[k] = entry;
              _keys = ks;
              continue;
            }
            _keys = ks;
            continue;
          }
          _keys = ks;
          continue;
        }
        _keys = ks;
        continue;
      }
      _keys = ks;
      continue;
    };
  };
  let json = Js_dict.get(obj, "modes");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let d = go(Stdlib_List.fromArray(Object.keys(match$1)), match$1, {});
  if (d !== undefined) {
    return Primitive_option.some(d);
  }
}

function optPerTier(obj) {
  let go = (_keys, dictObj, acc) => {
    while (true) {
      let keys = _keys;
      if (keys === 0) {
        return acc;
      }
      let ks = keys.tl;
      let k = keys.hd;
      let v = Js_dict.get(dictObj, k);
      if (v !== undefined) {
        let s = Js_json.decodeString(v);
        if (s === undefined) {
          return;
        }
        acc[k] = s;
        _keys = ks;
        continue;
      }
      _keys = ks;
      continue;
    };
  };
  let json = Js_dict.get(obj, "perTier");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let d = go(Stdlib_List.fromArray(Object.keys(match$1)), match$1, {});
  if (d !== undefined) {
    return Primitive_option.some(d);
  }
}

function decodeCostCeiling(obj) {
  let json = Js_dict.get(obj, "costCeiling");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let match$2 = optStr(match$1, "base");
  let match$3 = optNum(match$1, "multiple");
  if (match$2 !== undefined && match$3 !== undefined) {
    return Primitive_option.some({
      base: Primitive_option.valFromOption(match$2),
      multiple: Primitive_option.valFromOption(match$3)
    });
  }
}

function decodeGuard(obj) {
  let json = Js_dict.get(obj, "guard");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let match$2 = optBool(match$1, "blockSelfScript");
  let match$3 = optInt(match$1, "budget");
  if (match$2 !== undefined && match$3 !== undefined) {
    return Primitive_option.some({
      readDraftCap: undefined,
      sameOpRetryCap: undefined,
      blockSelfScript: Primitive_option.valFromOption(match$2),
      deliverableFirst: undefined,
      budget: Primitive_option.valFromOption(match$3),
      blockScriptWrites: undefined
    });
  }
}

function decodeVerify(obj) {
  let json = Js_dict.get(obj, "verify");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let match$2 = optStr(match$1, "require");
  let match$3 = optStr(match$1, "graderPolicy");
  let match$4 = optBool(match$1, "skipFastTier");
  if (match$2 !== undefined && match$3 !== undefined && match$4 !== undefined) {
    return Primitive_option.some({
      require: Primitive_option.valFromOption(match$2),
      requireExplicitDoD: undefined,
      preferDeterministic: undefined,
      graderPolicy: Primitive_option.valFromOption(match$3),
      graderTemperature: undefined,
      minGraderTier: undefined,
      skipFastTier: Primitive_option.valFromOption(match$4),
      skipTiers: undefined,
      hookTimeoutMs: undefined
    });
  }
}

function decodeEscalate(obj) {
  let json = Js_dict.get(obj, "escalate");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let floorTierJson = Js_dict.get(match$1, "floorTier");
  if (floorTierJson !== undefined) {
    let match$2 = Js_json.decodeNull(floorTierJson);
    let match$3 = Js_json.decodeString(floorTierJson);
    if (match$2 !== undefined) {
      let costCeiling = decodeCostCeiling(match$1);
      if (costCeiling !== undefined) {
        return Primitive_option.some({
          floorTier: undefined,
          ladder: undefined,
          maxAttemptsPerTier: undefined,
          maxTotalAttempts: undefined,
          costCeiling: Primitive_option.valFromOption(costCeiling)
        });
      } else {
        return;
      }
    }
    if (match$3 === undefined) {
      return;
    }
    let costCeiling$1 = decodeCostCeiling(match$1);
    if (costCeiling$1 !== undefined) {
      return Primitive_option.some({
        floorTier: Primitive_option.some(match$3),
        ladder: undefined,
        maxAttemptsPerTier: undefined,
        maxTotalAttempts: undefined,
        costCeiling: Primitive_option.valFromOption(costCeiling$1)
      });
    } else {
      return;
    }
  }
  let costCeiling$2 = decodeCostCeiling(match$1);
  if (costCeiling$2 !== undefined) {
    return Primitive_option.some({
      floorTier: undefined,
      ladder: undefined,
      maxAttemptsPerTier: undefined,
      maxTotalAttempts: undefined,
      costCeiling: Primitive_option.valFromOption(costCeiling$2)
    });
  }
}

function decodeEnforcement(obj) {
  let json = Js_dict.get(obj, "enforcement");
  if (json === undefined) {
    return Primitive_option.some(undefined);
  }
  let match = Js_json.decodeNull(json);
  let match$1 = Js_json.decodeObject(json);
  if (match !== undefined) {
    return Primitive_option.some(undefined);
  }
  if (match$1 === undefined) {
    return;
  }
  let match$2 = decodeMode(match$1);
  let match$3 = decodeGuard(match$1);
  let match$4 = decodeVerify(match$1);
  let match$5 = decodeEscalate(match$1);
  if (match$2 === undefined) {
    return;
  }
  if (match$3 === undefined) {
    return;
  }
  if (match$4 === undefined) {
    return;
  }
  if (match$5 === undefined) {
    return;
  }
  let perTier = optPerTier(match$1);
  if (perTier !== undefined) {
    return Primitive_option.some({
      mode: Primitive_option.valFromOption(match$2),
      envGate: undefined,
      perTier: Primitive_option.valFromOption(perTier),
      guard: Primitive_option.valFromOption(match$3),
      verify: Primitive_option.valFromOption(match$4),
      escalate: Primitive_option.valFromOption(match$5),
      proportional: undefined
    });
  }
}

function buildAllTiers(presetObj) {
  let tierKeys = Stdlib_List.fromArray(Object.keys(presetObj));
  let _keys = tierKeys;
  let acc = {};
  while (true) {
    let keys = _keys;
    if (keys === 0) {
      return acc;
    }
    let ks = keys.tl;
    let tk = keys.hd;
    let tierJson = Js_dict.get(presetObj, tk);
    if (tierJson !== undefined) {
      let tierObj = Js_json.decodeObject(tierJson);
      if (tierObj !== undefined) {
        let tc = decodeTier(tierObj);
        if (tc === undefined) {
          return;
        }
        acc[tk] = tc;
        _keys = ks;
        continue;
      }
      _keys = ks;
      continue;
    }
    _keys = ks;
    continue;
  };
}

function buildAllPresets(presetsObj) {
  let presetKeys = Stdlib_List.fromArray(Object.keys(presetsObj));
  if (Stdlib_List.length(presetKeys) === 0) {
    return;
  }
  let _keys = presetKeys;
  let acc = {};
  while (true) {
    let keys = _keys;
    if (keys === 0) {
      return acc;
    }
    let ks = keys.tl;
    let pk = keys.hd;
    let presetJson = Js_dict.get(presetsObj, pk);
    if (presetJson !== undefined) {
      let presetObj = Js_json.decodeObject(presetJson);
      if (presetObj === undefined) {
        return;
      }
      let td = buildAllTiers(presetObj);
      if (td === undefined) {
        return;
      }
      acc[pk] = td;
      _keys = ks;
      continue;
    }
    _keys = ks;
    continue;
  };
}

function parse(json) {
  let root = Js_json.decodeObject(json);
  if (root === undefined) {
    return;
  }
  let match = reqStr(root, "activePreset");
  let match$1 = reqStr(root, "defaultTier");
  let match$2 = reqArr(root, "rules");
  let match$3 = reqObj(root, "presets");
  if (match === undefined) {
    return;
  }
  if (match$1 === undefined) {
    return;
  }
  if (match$2 === undefined) {
    return;
  }
  if (match$3 === undefined) {
    return;
  }
  let rules = decodeStringArray(match$2);
  if (rules === undefined) {
    return;
  }
  let presets = buildAllPresets(match$3);
  if (presets === undefined) {
    return;
  }
  let activeMode = optStr(root, "activeMode");
  let tierCaps = optIntDict(root, "tierCaps");
  let tierPrompts = optStringDict(root, "tierPrompts");
  let modes = decodeModes(root);
  let enforcement = decodeEnforcement(root);
  let reasoningPolicy = decodeReasoningPolicy(root);
  if (activeMode !== undefined && tierCaps !== undefined && tierPrompts !== undefined && modes !== undefined && enforcement !== undefined && reasoningPolicy !== undefined) {
    return {
      activePreset: match,
      activeMode: Primitive_option.valFromOption(activeMode),
      tierCaps: Primitive_option.valFromOption(tierCaps),
      tierPrompts: Primitive_option.valFromOption(tierPrompts),
      presets: presets,
      rules: rules,
      defaultTier: match$1,
      fallback: undefined,
      taskPatterns: undefined,
      modes: Primitive_option.valFromOption(modes),
      enforcement: Primitive_option.valFromOption(enforcement),
      reasoningPolicy: Primitive_option.valFromOption(reasoningPolicy)
    };
  }
}

export {
  reasoningLevels,
  parse,
}
/* No side effect */
