// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as Config from "./Config.res.mjs";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function stringEqual(message, a, b) {
  Test.assertion(message, "stringEqual", (a, b) => a === b, a, b);
}

function intEqual(message, a, b) {
  Test.assertion(message, "intEqual", (a, b) => a === b, a, b);
}

function floatEqual(message, a, b) {
  Test.assertion(message, "floatEqual", (a, b) => a === b, a, b);
}

function assertEqual(a, b) {
  Test.assertion(undefined, undefined, (x, y) => x === y, a, b);
}

function json(s) {
  return JSON.parse(s);
}

Test.test("Config.parse: valid minimal config returns Some", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "multi-provider",
    "presets": {
      "test": {
        "fast": {
          "model": "test/model",
          "description": "test",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast"
  }`));
  if (result !== undefined) {
    stringEqual(undefined, result.activePreset, "multi-provider");
    return stringEqual(undefined, result.defaultTier, "fast");
  } else {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
});

Test.test("Config.parse: missing activePreset returns None", () => {
  let result = Config.parse(JSON.parse(`{"presets": {},"rules":[],"defaultTier":"fast"}`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: missing presets returns None", () => {
  let result = Config.parse(JSON.parse(`{"activePreset":"test","rules":[],"defaultTier":"fast"}`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: missing rules returns None", () => {
  let result = Config.parse(JSON.parse(`{"activePreset":"test","presets":{},"defaultTier":"fast"}`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: missing defaultTier returns None", () => {
  let result = Config.parse(JSON.parse(`{"activePreset":"test","presets":{},"rules":[]}`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: activePreset not string returns None", () => {
  let result = Config.parse(JSON.parse(`{"activePreset":123,"presets":{},"rules":[],"defaultTier":"fast"}`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: empty presets object returns None", () => {
  let result = Config.parse(JSON.parse(`{"activePreset":"test","presets":{},"rules":[],"defaultTier":"fast"}`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: tier missing model returns None", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast"
  }`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: tier missing description returns None", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast"
  }`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: tier missing whenToUse returns None", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier"
        }
      }
    },
    "rules": [],
    "defaultTier": "fast"
  }`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: tier with optional variant and costRatio parses", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "variant": "high",
          "costRatio": 3,
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast"
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let preset = Js_dict.get(result.presets, "test");
  if (preset === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let tier = Js_dict.get(preset, "fast");
  if (tier === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let v = tier.variant;
  if (v !== undefined) {
    stringEqual(undefined, v, "high");
  } else {
    Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let r = tier.costRatio;
  if (r !== undefined) {
    return floatEqual(undefined, r, 3.0);
  } else {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
});

Test.test("Config.parse: model without slash returns None", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "invalidmodel",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast"
  }`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: tier with reasoning.effort parses", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "heavy": {
          "model": "provider/model",
          "description": "a tier",
          "reasoning": {
            "effort": "high",
            "summary": "detailed"
          },
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "heavy"
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let preset = Js_dict.get(result.presets, "test");
  if (preset === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let tier = Js_dict.get(preset, "heavy");
  if (tier === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let reas = tier.reasoning;
  if (reas === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let e = reas.effort;
  if (e !== undefined) {
    return stringEqual(undefined, e, "high");
  } else {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
});

Test.test("Config.parse: tier with thinking.budgetTokens parses", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "anthropic/model",
          "thinking": {
            "budgetTokens": 1024
          },
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast"
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let preset = Js_dict.get(result.presets, "test");
  if (preset === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let tier = Js_dict.get(preset, "fast");
  if (tier === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let th = tier.thinking;
  if (th === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let bt = th.budgetTokens;
  if (bt !== undefined) {
    return intEqual(undefined, bt, 1024);
  } else {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
});

Test.test("Config.parse: modes.overrideRules parses", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "modes": {
      "budget": {
        "defaultTier": "fast",
        "description": "Budget mode",
        "overrideRules": ["default->fast"]
      }
    }
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let mode = Belt_Option.flatMap(result.modes, modesDict => Js_dict.get(modesDict, "budget"));
  if (mode === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  stringEqual(undefined, mode.defaultTier, "fast");
  let rules = mode.overrideRules;
  if (rules !== undefined) {
    return intEqual(undefined, rules.length, 1);
  } else {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
});

Test.test("Config.parse: enforcement mode enforced parses", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "enforcement": {
      "mode": "enforced"
    }
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let enf = result.enforcement;
  if (enf === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let match = enf.mode;
  if (match === "enforced") {
    return Test.pass(undefined, undefined);
  }
  Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
});

Test.test("Config.parse: enforcement mode invalid returns None", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "enforcement": {
      "mode": "invalid-mode"
    }
  }`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: enforcement perTier parsing", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "enforcement": {
      "perTier": {
        "fast": "off"
      }
    }
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let enf = result.enforcement;
  if (enf === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let pt = enf.perTier;
  if (pt === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let match = Js_dict.get(pt, "fast");
  if (match === "off") {
    return Test.pass(undefined, undefined);
  }
  Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
});

Test.test("Config.parse: enforcement guard block parsing", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "enforcement": {
      "guard": {
        "blockSelfScript": true,
        "budget": 5000
      }
    }
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let enf = result.enforcement;
  if (enf === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let guard = enf.guard;
  if (guard === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let match = guard.blockSelfScript;
  if (match !== undefined) {
    if (match) {
      return Test.pass(undefined, undefined);
    } else {
      return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
    }
  } else {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
});

Test.test("Config.parse: enforcement verify block parsing", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "enforcement": {
      "verify": {
        "require": "always",
        "graderPolicy": "atLeastProducerTier",
        "skipFastTier": false
      }
    }
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let enf = result.enforcement;
  if (enf === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let verify = enf.verify;
  if (verify === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let match = verify.require;
  if (match === "always") {
    return Test.pass(undefined, undefined);
  }
  Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
});

Test.test("Config.parse: enforcement escalate.floorTier null parses", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "enforcement": {
      "escalate": {
        "floorTier": null
      }
    }
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let enf = result.enforcement;
  if (enf === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let esc = enf.escalate;
  if (esc === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let match = esc.floorTier;
  if (match !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: enforcement escalate.costCeiling parses", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "enforcement": {
      "escalate": {
        "costCeiling": {
          "base": "medium",
          "multiple": 3.0
        }
      }
    }
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let enf = result.enforcement;
  if (enf === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let esc = enf.escalate;
  if (esc === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let cc = esc.costCeiling;
  if (cc === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let b = cc.base;
  if (b !== undefined) {
    stringEqual(undefined, b, "medium");
  } else {
    Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let m = cc.multiple;
  if (m !== undefined) {
    return floatEqual(undefined, m, 3.0);
  } else {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
});

Test.test("Config.parse: reasoningPolicy.trivialLevel null is valid", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "reasoningPolicy": {
      "mode": "adaptive",
      "adaptive": {
        "trivialLevel": null,
        "defaultLevel": "normal"
      }
    }
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let rp = result.reasoningPolicy;
  if (rp === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let adapt = rp.adaptive;
  if (adapt === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let match = adapt.trivialLevel;
  if (match !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: reasoningPolicy.keywordRules parses", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "reasoningPolicy": {
      "adaptive": {
        "keywordRules": [
          {
            "keywords": ["format", "lint"],
            "level": "minimal"
          },
          {
            "keywords": ["debug", "security"],
            "level": "elevated",
            "match": "substring"
          }
        ]
      }
    }
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let rp = result.reasoningPolicy;
  if (rp === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let adapt = rp.adaptive;
  if (adapt === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let rules = adapt.keywordRules;
  if (rules !== undefined) {
    return intEqual(undefined, rules.length, 2);
  } else {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
});

Test.test("Config.parse: reasoningPolicy.keywordRules level = minimal returns Some", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "reasoningPolicy": {
      "adaptive": {
        "keywordRules": [
          {
            "keywords": ["format", "lint"],
            "level": "minimal"
          }
        ]
      }
    }
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let rp = result.reasoningPolicy;
  if (rp === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let adapt = rp.adaptive;
  if (adapt === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let rules = adapt.keywordRules;
  if (rules === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  if (rules.length !== 1) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let kr = rules[0];
  if (kr === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let match = kr.level;
  if (match === "minimal") {
    return Test.pass(undefined, undefined);
  } else {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
});

Test.test("Config.parse: reasoningPolicy.keywordRules level = max returns Some", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "reasoningPolicy": {
      "adaptive": {
        "keywordRules": [
          {
            "keywords": ["security"],
            "level": "max"
          }
        ]
      }
    }
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let rp = result.reasoningPolicy;
  if (rp === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let adapt = rp.adaptive;
  if (adapt === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let rules = adapt.keywordRules;
  if (rules === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  if (rules.length !== 1) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let kr = rules[0];
  if (kr === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let match = kr.level;
  if (match === "max") {
    return Test.pass(undefined, undefined);
  } else {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
});

Test.test("Config.parse: reasoningPolicy.adaptive.tierDefaults fast = elevated returns Some", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "reasoningPolicy": {
      "adaptive": {
        "defaultLevel": "normal",
        "tierDefaults": {
          "fast": "elevated"
        }
      }
    }
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let rp = result.reasoningPolicy;
  if (rp === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let adapt = rp.adaptive;
  if (adapt === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let td = adapt.tierDefaults;
  if (td === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let match = Js_dict.get(td, "fast");
  if (match === "elevated") {
    return Test.pass(undefined, undefined);
  }
  Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
});

Test.test("Config.parse: reasoningPolicy.keywordRules level invalid returns None", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "reasoningPolicy": {
      "adaptive": {
        "keywordRules": [
          {
            "keywords": ["test"],
            "level": "invalid-level"
          }
        ]
      }
    }
  }`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: reasoningPolicy.keywordRules empty keywords returns None", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "reasoningPolicy": {
      "adaptive": {
        "keywordRules": [
          {
            "keywords": [],
            "level": "minimal"
          }
        ]
      }
    }
  }`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: reasoningPolicy.keywordRules regex compile-fail returns None", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"]
        }
      }
    },
    "rules": [],
    "defaultTier": "fast",
    "reasoningPolicy": {
      "adaptive": {
        "keywordRules": [
          {
            "keywords": ["[invalid"],
            "level": "minimal",
            "match": "regex"
          }
        ]
      }
    }
  }`));
  if (result !== undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  } else {
    return Test.pass(undefined, undefined);
  }
});

Test.test("Config.parse: tier capability kind none parses", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "fast": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"],
          "capability": {
            "kind": "none"
          }
        }
      }
    },
    "rules": [],
    "defaultTier": "fast"
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let preset = Js_dict.get(result.presets, "test");
  if (preset === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let tier = Js_dict.get(preset, "fast");
  if (tier === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let cap = tier.capability;
  if (cap !== undefined) {
    if (typeof cap !== "object") {
      return Test.pass(undefined, undefined);
    } else {
      return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
    }
  } else {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
});

Test.test("Config.parse: tier capability kind binary parses", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "medium": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"],
          "capability": {
            "kind": "binary",
            "field": "variant",
            "elevated": "max"
          }
        }
      }
    },
    "rules": [],
    "defaultTier": "medium"
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let preset = Js_dict.get(result.presets, "test");
  if (preset === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let tier = Js_dict.get(preset, "medium");
  if (tier === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let cap = tier.capability;
  if (cap === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  if (typeof cap === "object" && cap.TAG === "Binary" && cap.field === "variant") {
    return stringEqual(undefined, cap.elevated, "max");
  }
  Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
});

Test.test("Config.parse: tier capability kind discrete parses", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "light": {
          "model": "provider/model",
          "description": "a tier",
          "whenToUse": ["test"],
          "capability": {
            "kind": "discrete",
            "field": "variant",
            "levels": ["low", "medium", "high"]
          }
        }
      }
    },
    "rules": [],
    "defaultTier": "light"
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let preset = Js_dict.get(result.presets, "test");
  if (preset === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let tier = Js_dict.get(preset, "light");
  if (tier === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let cap = tier.capability;
  if (cap === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  if (typeof cap === "object" && cap.TAG === "Discrete") {
    return intEqual(undefined, cap.levels.length, 3);
  }
  Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
});

Test.test("Config.parse: tier capability kind budgeted parses", () => {
  let result = Config.parse(JSON.parse(`{
    "activePreset": "test",
    "presets": {
      "test": {
        "heavy": {
          "model": "anthropic/model",
          "description": "a tier",
          "whenToUse": ["test"],
          "capability": {
            "kind": "budgeted",
            "field": "thinking.budgetTokens",
            "recommended": {
              "minimal": 1024,
              "normal": 4096,
              "elevated": 8192,
              "max": 16384
            }
          }
        }
      }
    },
    "rules": [],
    "defaultTier": "heavy"
  }`));
  if (result === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let preset = Js_dict.get(result.presets, "test");
  if (preset === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let tier = Js_dict.get(preset, "heavy");
  if (tier === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  let cap = tier.capability;
  if (cap === undefined) {
    return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
  }
  if (typeof cap === "object" && cap.TAG === "Budgeted") {
    let v = Js_dict.get(cap.recommended, "normal");
    if (v !== undefined) {
      return intEqual(undefined, v | 0, 4096);
    } else {
      return Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
    }
  }
  Test.assertion(undefined, undefined, (param, param$1) => false, true, false);
});

export {
  stringEqual,
  intEqual,
  floatEqual,
  assertEqual,
  json,
}
/*  Not a pure module */
