// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Protocol from "./Protocol.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function assertionEqual(operator, expected, actual) {
  Test.assertion(undefined, operator, (a, b) => a === b, actual, expected);
}

function assertionTrue(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === true, actual, true);
}

function assertionFalse(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === false, actual, false);
}

function assertionContains(operator, needle, haystack) {
  let contains = haystack.indexOf(needle) >= 0;
  Test.assertion(undefined, operator, (_a, b) => b === true, contains, true);
}

function tier(model) {
  return Js_dict.fromArray([
    [
      "model",
      model
    ],
    [
      "description",
      "d"
    ],
    [
      "whenToUse",
      ["x"]
    ]
  ]);
}

let minimalCfg = {
  activePreset: "p",
  presets: { p: { only: { model: "prov/model-x", description: "d", whenToUse: ["x"] } } },
  rules: ["alpha", "beta"],
  defaultTier: "only"
};

let richCfg = {
  activePreset: "anthropic",
  activeMode: "budget",
  presets: {
    anthropic: {
      fast: { model: "anthropic/claude-haiku-4-5", costRatio: 1, description: "d", whenToUse: ["x"] },
      medium: { model: "anthropic/claude-sonnet-4-6", costRatio: 5, variant: "max", description: "d", whenToUse: ["x"] },
    },
    openai: { fast: { model: "openai/gpt-x", costRatio: 1, description: "d", whenToUse: ["x"] } },
  },
  rules: ["base1"],
  defaultTier: "fast",
  modes: { budget: { defaultTier: "fast", description: "cheap", overrideRules: ["o1", "o2"] } },
  taskPatterns: { fast: ["recon", "lookup"], medium: ["impl"] },
  fallback: { global: { anthropic: ["openai"] } },
};

Test.test("getActiveTiers: returns the active preset's tiers", () => {
  let tiers = Protocol.getActiveTiers(Protocol.tierConfigFromDict(minimalCfg));
  assertionEqual("key count", "only", Object.keys(tiers)[0]);
});

Test.test("getActiveTiers: falls back to first preset when activePreset unknown", () => {
  let cfg = {
    activePreset: "missing",
    presets: { p: { only: { model: "prov/model-x", description: "d", whenToUse: ["x"] } } },
    rules: [],
    defaultTier: "only"
  };
  let tiers = Protocol.getActiveTiers(Protocol.tierConfigFromDict(cfg));
  assertionTrue("tiers defined", Object.keys(tiers).length !== 0);
});

Test.test("getActiveMode: returns undefined when modes absent", () => {
  let result = Protocol.getActiveMode(Protocol.tierConfigFromDict(minimalCfg));
  if (result !== undefined) {
    return assertionTrue("result should be None", false);
  } else {
    return assertionTrue("result is None", true);
  }
});

Test.test("getActiveMode: returns undefined when activeMode absent", () => {
  let cfg = {
    activePreset: "p",
    presets: { p: { only: { model: "prov/model-x", description: "d", whenToUse: ["x"] } } },
    rules: [],
    defaultTier: "only"
  };
  let result = Protocol.getActiveMode(Protocol.tierConfigFromDict(cfg));
  if (result !== undefined) {
    return assertionTrue("result should be None", false);
  } else {
    return assertionTrue("result is None", true);
  }
});

Test.test("getActiveMode: returns active mode when present", () => {
  let result = Protocol.getActiveMode(Protocol.tierConfigFromDict(richCfg));
  if (result !== undefined) {
    return assertionEqual("defaultTier", "fast", Protocol.modeDefaultTier(result));
  } else {
    return assertionTrue("should not be None", false);
  }
});

Test.test("buildTaskTaxonomy: returns empty string when taskPatterns absent", () => assertionEqual("empty", "", Protocol.buildTaskTaxonomy(Protocol.tierConfigFromDict(minimalCfg))));

Test.test("buildTaskTaxonomy: builds R: line when taskPatterns present", () => {
  let out = Protocol.buildTaskTaxonomy(Protocol.tierConfigFromDict(richCfg));
  assertionContains("R:", "R:", out);
  assertionContains("fast pattern", "@fast→recon/lookup", out);
});

Test.test("buildTaskTaxonomy: skips empty pattern arrays", () => {
  let cfg = {
    activePreset: "p",
    presets: { p: { only: { model: "prov/model-x", description: "d", whenToUse: ["x"] } } },
    rules: [],
    defaultTier: "only",
    taskPatterns: { fast: [] }
  };
  assertionEqual("R:", "R:", Protocol.buildTaskTaxonomy(Protocol.tierConfigFromDict(cfg)));
});

Test.test("buildDecomposeHint: returns empty when active mode has overrideRules", () => assertionEqual("overrideRules present", "", Protocol.buildDecomposeHint(Protocol.tierConfigFromDict(richCfg))));

Test.test("buildDecomposeHint: returns empty when fewer than 2 tiers", () => assertionEqual("only one tier", "", Protocol.buildDecomposeHint(Protocol.tierConfigFromDict(minimalCfg))));

Test.test("buildDecomposeHint: returns explore→execute hint for 2+ tiers in normal mode", () => {
  let cfg = {
    activePreset: "anthropic",
    presets: {
      anthropic: {
        fast: { model: "anthropic/claude-haiku-4-5", costRatio: 1, description: "d", whenToUse: ["x"] },
        medium: { model: "anthropic/claude-sonnet-4-6", costRatio: 5, description: "d", whenToUse: ["x"] },
      },
    },
    rules: [],
    defaultTier: "fast",
  };
  let out = Protocol.buildDecomposeHint(Protocol.tierConfigFromDict(cfg));
  assertionContains("explore hint", "explore(@fast)→execute(@medium)", out);
});

Test.test("buildFallbackInstructions: returns empty when no fallback configured", () => assertionEqual("no fallback", "", Protocol.buildFallbackInstructions(Protocol.tierConfigFromDict(minimalCfg))));

Test.test("buildFallbackInstructions: uses fb.global when no preset-specific map", () => {
  let out = Protocol.buildFallbackInstructions(Protocol.tierConfigFromDict(richCfg));
  assertionContains("anthropic chain", "anthropic→openai", out);
});

Test.test("buildFallbackInstructions: prefers non-empty preset-specific map over global", () => {
  let cfg = {
    activePreset: "anthropic",
    activeMode: "budget",
    presets: {
      anthropic: {
        fast: { model: "anthropic/claude-haiku-4-5", costRatio: 1, description: "d", whenToUse: ["x"] },
        medium: { model: "anthropic/claude-sonnet-4-6", costRatio: 5, description: "d", whenToUse: ["x"] },
      },
    },
    rules: [],
    defaultTier: "fast",
    modes: { budget: { defaultTier: "fast", description: "cheap", overrideRules: ["o1", "o2"] } },
    fallback: { presets: { anthropic: { x: ["openai"] } }, global: { y: ["openai"] } },
  };
  let out = Protocol.buildFallbackInstructions(Protocol.tierConfigFromDict(cfg));
  assertionContains("preset chain", "x→openai", out);
});

Test.test("buildFallbackInstructions: returns empty when chain map yields no valid targets", () => {
  let cfg = {
    activePreset: "anthropic",
    activeMode: "budget",
    presets: {
      anthropic: {
        fast: { model: "anthropic/claude-haiku-4-5", costRatio: 1, description: "d", whenToUse: ["x"] },
        medium: { model: "anthropic/claude-sonnet-4-6", costRatio: 5, description: "d", whenToUse: ["x"] },
      },
    },
    rules: [],
    defaultTier: "fast",
    modes: { budget: { defaultTier: "fast", description: "cheap", overrideRules: ["o1", "o2"] } },
    fallback: { global: { anthropic: ["nonexistent"] } },
  };
  assertionEqual("no valid targets", "", Protocol.buildFallbackInstructions(Protocol.tierConfigFromDict(cfg)));
});

Test.test("buildFallbackInstructions: skips non-array chain entries", () => {
  let cfg = {
    activePreset: "anthropic",
    activeMode: "budget",
    presets: {
      anthropic: {
        fast: { model: "anthropic/claude-haiku-4-5", costRatio: 1, description: "d", whenToUse: ["x"] },
        medium: { model: "anthropic/claude-sonnet-4-6", costRatio: 5, description: "d", whenToUse: ["x"] },
      },
    },
    rules: [],
    defaultTier: "fast",
    modes: { budget: { defaultTier: "fast", description: "cheap", overrideRules: ["o1", "o2"] } },
    fallback: { global: { anthropic: "openai" } },
  };
  assertionEqual("non-array", "", Protocol.buildFallbackInstructions(Protocol.tierConfigFromDict(cfg)));
});

Test.test("buildDelegationProtocol: renders minimal config without optional sections", () => {
  let out = Protocol.buildDelegationProtocol(Protocol.tierConfigFromDict(minimalCfg));
  assertionContains("Preset line", "Preset: p.", out);
  assertionContains("tier line", "@only=model-x", out);
  assertionContains("no mode", "mode:", out);
  assertionFalse("no mode suffix", out.indexOf("mode:") >= 0);
  assertionContains("rules", "1.alpha 2.beta", out);
});

Test.test("buildDelegationProtocol: renders rich config with variant, costRatio, mode suffix", () => {
  let out = Protocol.buildDelegationProtocol(Protocol.tierConfigFromDict(richCfg));
  assertionContains("variant/costRatio", "@medium=claude-sonnet-4-6/max(5x)", out);
  assertionContains("mode suffix", "mode:budget", out);
  assertionContains("overrideRules", "1.o1 2.o2", out);
  assertionContains("taxonomy", "R:", out);
  assertionContains("fallback chain", "Chain:", out);
});

Test.test("isClaudeModel: undefined returns false", () => assertionFalse("undefined", Protocol.isClaudeModel(null)));

Test.test("isClaudeModel: anthropic/ prefix returns true", () => assertionTrue("anthropic/", Protocol.isClaudeModel("anthropic/claude-haiku-4-5")));

Test.test("isClaudeModel: claude- in path returns true", () => assertionTrue("bedrock/claude-3-sonnet", Protocol.isClaudeModel("bedrock/claude-3-sonnet")));

Test.test("isClaudeModel: leading claude- returns true", () => assertionTrue("claude-3-opus", Protocol.isClaudeModel("claude-3-opus")));

Test.test("isClaudeModel: non-claude returns false", () => assertionFalse("openai/gpt-5", Protocol.isClaudeModel("openai/gpt-5")));

Test.test("CLAUDE_TIER_PREFIX: has fast key", () => assertionTrue("has fast", Stdlib_Option.isSome(Js_dict.get(Protocol.claudeTierPrefix, "fast"))));

Test.test("CLAUDE_TIER_PREFIX: has medium key", () => assertionTrue("has medium", Stdlib_Option.isSome(Js_dict.get(Protocol.claudeTierPrefix, "medium"))));

Test.test("CLAUDE_TIER_PREFIX: has heavy key", () => assertionTrue("has heavy", Stdlib_Option.isSome(Js_dict.get(Protocol.claudeTierPrefix, "heavy"))));

Test.test("CLAUDE_TIER_PREFIX: has light key", () => assertionTrue("has light", Stdlib_Option.isSome(Js_dict.get(Protocol.claudeTierPrefix, "light"))));

Test.test("CLAUDE_TIER_PREFIX: has focused key", () => assertionTrue("has focused", Stdlib_Option.isSome(Js_dict.get(Protocol.claudeTierPrefix, "focused"))));

Test.test("CLAUDE_TIER_PREFIX: fast prefix is non-empty string", () => {
  let v = Js_dict.get(Protocol.claudeTierPrefix, "fast");
  if (v !== undefined) {
    return assertionTrue("non-empty", v.length > 0);
  } else {
    return Test.assertion(undefined, "should exist", (_a, _b) => false, true, false);
  }
});

Test.test("CLAUDE_TIER_PREFIX: light prefix is non-empty string", () => {
  let v = Js_dict.get(Protocol.claudeTierPrefix, "light");
  if (v !== undefined) {
    return assertionTrue("non-empty", v.length > 0);
  } else {
    return Test.assertion(undefined, "should exist", (_a, _b) => false, true, false);
  }
});

Test.test("assembleSystemPrompt: prepends Claude override for Claude orchestrators", () => {
  let out = Protocol.assembleSystemPrompt(Protocol.tierConfigFromDict(minimalCfg), "anthropic/claude-haiku-4-5", false);
  assertionContains("authority override", "AUTHORITY OVERRIDE", out);
  assertionContains("anti-narration", "ANTI-NARRATION", out);
  assertionContains("delegation protocol", "## Model Delegation Protocol", out);
});

Test.test("assembleSystemPrompt: returns bare protocol for non-Claude orchestrators", () => {
  let out = Protocol.assembleSystemPrompt(Protocol.tierConfigFromDict(minimalCfg), "openai/gpt-5", false);
  assertionTrue("starts with delegation", out.startsWith("## Model Delegation Protocol"));
  assertionFalse("no authority override", out.indexOf("AUTHORITY OVERRIDE") >= 0);
});

Test.test("assembleSystemPrompt: appends DoD section when enforcementOn is true", () => {
  let out = Protocol.assembleSystemPrompt(Protocol.tierConfigFromDict(minimalCfg), null, true);
  assertionContains("acceptance block", "[acceptance]", out);
  assertionContains("check kinds", "check kinds:", out);
});

Test.test("assembleSystemPrompt: no DoD section when enforcementOn is false", () => {
  let out = Protocol.assembleSystemPrompt(Protocol.tierConfigFromDict(minimalCfg), null, false);
  assertionFalse("no acceptance block", out.indexOf("[acceptance]") >= 0);
});

Test.test("buildDoDProtocolSection: contains acceptance block and check examples", () => {
  let out = Protocol.buildDoDProtocolSection(Protocol.tierConfigFromDict(minimalCfg));
  assertionContains("acceptance block", "[acceptance]", out);
  assertionContains("testsPass", "check: testsPass", out);
  assertionContains("schemaMatch", "schemaMatch", out);
});

Test.test("buildDoDProtocolSection: auto-inferred wording by default", () => {
  let out = Protocol.buildDoDProtocolSection(Protocol.tierConfigFromDict(minimalCfg));
  assertionContains("auto-inferred", "auto-inferred", out);
  assertionFalse("no REQUIRED", out.indexOf("REQUIRED") >= 0);
});

Test.test("buildDoDProtocolSection: REQUIRED wording when requireExplicitDoD is true", () => {
  let cfg = {
    activePreset: "p",
    presets: { p: { only: { model: "prov/model-x", description: "d", whenToUse: ["x"] } } },
    rules: [],
    defaultTier: "only",
    enforcement: { verify: { requireExplicitDoD: true } }
  };
  let out = Protocol.buildDoDProtocolSection(Protocol.tierConfigFromDict(cfg));
  assertionContains("REQUIRED", "REQUIRED", out);
  assertionFalse("no auto-inferred", out.indexOf("auto-inferred") >= 0);
});

Test.test("buildDelegationProtocol: minimal prompt exact snapshot", () => {
  let out = Protocol.buildDelegationProtocol(Protocol.tierConfigFromDict(minimalCfg));
  assertionTrue("starts with header", out.startsWith("## Model Delegation Protocol"));
  assertionContains("HARD ROUTING section", "### HARD ROUTING (non-negotiable)", out);
  assertionContains("ROLE CONTRACT section", "### ROLE CONTRACT", out);
  assertionContains("@fast contract", "### @fast contract", out);
  assertionContains("@medium contract", "### @medium contract", out);
  assertionContains("@light contract", "### @light contract", out);
  assertionContains("@focused contract", "### @focused contract", out);
  assertionContains("@heavy contract", "### @heavy contract", out);
  assertionContains("CONFLICT section", "### CONFLICT WITH CLAUDE.md", out);
  assertionContains("Compact rules section", "### Compact rules", out);
  assertionContains("Delegate with Task", "Delegate with", out);
  assertionContains("Invalid Targets section", "### Invalid Targets", out);
  assertionContains("build is invalid", "build", out);
});

Test.test("buildTaskTaxonomy: includes light and focused patterns in five-tier config", () => {
  let cfg = {
    activePreset: "multi-provider",
    activeMode: "normal",
    presets: {
      "multi-provider": {
        fast: { model: "opencode-go/mimo-v2.5", costRatio: 1, description: "d", whenToUse: ["x"] },
        light: { model: "opencode-go/mimo-v2.5", costRatio: 2, variant: "high", description: "d", whenToUse: ["x"] },
        medium: { model: "minimax-coding-plan/MiniMax-M3", costRatio: 5, description: "d", whenToUse: ["x"] },
        focused: { model: "minimax-coding-plan/MiniMax-M3", costRatio: 10, variant: "thinking", description: "d", whenToUse: ["x"] },
        heavy: { model: "openai/gpt-5.4", costRatio: 20, description: "d", whenToUse: ["x"] },
      },
    },
    rules: ["r1"],
    defaultTier: "medium",
    modes: { normal: { defaultTier: "medium", description: "d" } },
    taskPatterns: {
      fast: ["search"],
      light: ["simple-edit"],
      medium: ["impl-feature"],
      focused: ["deep-debug"],
      heavy: ["arch-design"],
    },
  };
  let out = Protocol.buildTaskTaxonomy(Protocol.tierConfigFromDict(cfg));
  assertionContains("@light", "@light", out);
  assertionContains("@focused", "@focused", out);
  assertionContains("simple-edit", "simple-edit", out);
  assertionContains("deep-debug", "deep-debug", out);
});

Test.test("buildDelegationProtocol: renders light tier in tier line", () => {
  let cfg = {
    activePreset: "multi-provider",
    activeMode: "normal",
    presets: {
      "multi-provider": {
        fast: { model: "opencode-go/mimo-v2.5", costRatio: 1, description: "d", whenToUse: ["x"] },
        light: { model: "opencode-go/mimo-v2.5", costRatio: 2, variant: "high", description: "d", whenToUse: ["x"] },
        medium: { model: "minimax-coding-plan/MiniMax-M3", costRatio: 5, description: "d", whenToUse: ["x"] },
        focused: { model: "minimax-coding-plan/MiniMax-M3", costRatio: 10, variant: "thinking", description: "d", whenToUse: ["x"] },
        heavy: { model: "openai/gpt-5.4", costRatio: 20, description: "d", whenToUse: ["x"] },
      },
    },
    rules: ["r1"],
    defaultTier: "medium",
    modes: { normal: { defaultTier: "medium", description: "d" } },
};
  let out = Protocol.buildDelegationProtocol(Protocol.tierConfigFromDict(cfg));
  assertionContains("@light in tier line", "@light", out);
  assertionContains("@focused in tier line", "@focused", out);
});

Test.test("buildDelegationProtocol: contains @light contract section", () => {
  let cfg = {
    activePreset: "multi-provider",
    activeMode: "normal",
    presets: {
      "multi-provider": {
        fast: { model: "opencode-go/mimo-v2.5", costRatio: 1, description: "d", whenToUse: ["x"] },
        light: { model: "opencode-go/mimo-v2.5", costRatio: 2, variant: "high", description: "d", whenToUse: ["x"] },
        medium: { model: "minimax-coding-plan/MiniMax-M3", costRatio: 5, description: "d", whenToUse: ["x"] },
        focused: { model: "minimax-coding-plan/MiniMax-M3", costRatio: 10, variant: "thinking", description: "d", whenToUse: ["x"] },
        heavy: { model: "openai/gpt-5.4", costRatio: 20, description: "d", whenToUse: ["x"] },
      },
    },
    rules: ["r1"],
    defaultTier: "medium",
    modes: { normal: { defaultTier: "medium", description: "d" } },
};
  let out = Protocol.buildDelegationProtocol(Protocol.tierConfigFromDict(cfg));
  assertionContains("@light contract section", "### @light contract", out);
  assertionContains("@focused contract section", "### @focused contract", out);
});

export {
  assertionEqual,
  assertionTrue,
  assertionFalse,
  assertionContains,
  tier,
  minimalCfg,
  richCfg,
}
/*  Not a pure module */
