// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_float from "@rescript/runtime/lib/es6/Primitive_float.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function optString(json) {
  let s = Stdlib_JSON.Decode.string(json);
  if (s !== undefined) {
    return s;
  } else {
    return "";
  }
}

function optStringFromDict(d, k) {
  let json = d[k];
  if (json !== undefined) {
    return optString(json);
  } else {
    return "";
  }
}

function optStringOrNullFromDict(d, k) {
  let json = d[k];
  if (json !== undefined) {
    let s = Stdlib_JSON.Decode.string(json);
    if (s !== undefined) {
      return s;
    } else {
      return null;
    }
  } else {
    return null;
  }
}

function optFloatFromDict(d, k) {
  let json = d[k];
  if (json === undefined) {
    return null;
  }
  let n = Stdlib_JSON.Decode.float(json);
  if (n !== undefined) {
    return n;
  } else {
    return null;
  }
}

function optStringArrayFromDict(d, k) {
  let json = d[k];
  if (json !== undefined) {
    let arr = Stdlib_JSON.Decode.array(json);
    if (arr !== undefined) {
      return arr.map(optString);
    } else {
      return [];
    }
  } else {
    return [];
  }
}

function optBoolFromDict(d, k) {
  let json = d[k];
  if (json === undefined) {
    return null;
  }
  let b = Stdlib_JSON.Decode.bool(json);
  if (b !== undefined) {
    return b;
  } else {
    return null;
  }
}

function tierDefFromDict(d) {
  return {
    model: optStringFromDict(d, "model"),
    variant: optStringOrNullFromDict(d, "variant"),
    costRatio: optFloatFromDict(d, "costRatio"),
    description: optStringFromDict(d, "description"),
    whenToUse: optStringArrayFromDict(d, "whenToUse")
  };
}

function fallbackConfigFromDict(fb) {
  let optDictStringArray = (d, k) => {
    let json = d[k];
    if (json === undefined) {
      return null;
    }
    let obj = Stdlib_JSON.Decode.object(json);
    if (obj === undefined) {
      return null;
    }
    let dict = {};
    Object.entries(obj).forEach(param => {
      let arr = Stdlib_JSON.Decode.array(param[1]);
      if (arr !== undefined) {
        dict[param[0]] = arr.map(optString);
        return;
      }
    });
    return dict;
  };
  let optDictDictStringArray = (d, k) => {
    let json = d[k];
    if (json === undefined) {
      return null;
    }
    let obj = Stdlib_JSON.Decode.object(json);
    if (obj === undefined) {
      return null;
    }
    let dict = {};
    Object.entries(obj).forEach(param => {
      let innerObj = Stdlib_JSON.Decode.object(param[1]);
      if (innerObj === undefined) {
        return;
      }
      let innerDict = {};
      Object.entries(innerObj).forEach(param => {
        let arr = Stdlib_JSON.Decode.array(param[1]);
        if (arr !== undefined) {
          innerDict[param[0]] = arr.map(optString);
          return;
        }
      });
      dict[param[0]] = innerDict;
    });
    return dict;
  };
  return {
    global: optDictStringArray(fb, "global"),
    presets: optDictDictStringArray(fb, "presets")
  };
}

function modeConfigFromDict(d) {
  let json = d["overrideRules"];
  let tmp;
  if (json !== undefined) {
    let arr = Stdlib_JSON.Decode.array(json);
    tmp = arr !== undefined ? arr.map(optString) : null;
  } else {
    tmp = null;
  }
  return {
    defaultTier: optStringFromDict(d, "defaultTier"),
    description: optStringFromDict(d, "description"),
    overrideRules: tmp
  };
}

function enforcementConfigFromDict(d) {
  let json = d["verify"];
  let tmp;
  if (json !== undefined) {
    let obj = Stdlib_JSON.Decode.object(json);
    tmp = obj !== undefined ? ({
        requireExplicitDoD: optBoolFromDict(obj, "requireExplicitDoD")
      }) : null;
  } else {
    tmp = null;
  }
  return {
    verify: tmp
  };
}

function tierConfigFromDict(d) {
  let result = {};
  let json = d["presets"];
  if (json !== undefined) {
    let presetsObj = Stdlib_JSON.Decode.object(json);
    if (presetsObj !== undefined) {
      Object.entries(presetsObj).forEach(param => {
        let presetObj = Stdlib_JSON.Decode.object(param[1]);
        if (presetObj === undefined) {
          return;
        }
        let tierMap = {};
        Object.entries(presetObj).forEach(param => {
          let tierObj = Stdlib_JSON.Decode.object(param[1]);
          if (tierObj !== undefined) {
            tierMap[param[0]] = tierDefFromDict(tierObj);
            return;
          }
        });
        result[param[0]] = tierMap;
      });
    }
  }
  let json$1 = d["fallback"];
  let tmp;
  if (json$1 !== undefined) {
    let fbObj = Stdlib_JSON.Decode.object(json$1);
    tmp = fbObj !== undefined ? fallbackConfigFromDict(fbObj) : null;
  } else {
    tmp = null;
  }
  let json$2 = d["taskPatterns"];
  let tmp$1;
  if (json$2 !== undefined) {
    let obj = Stdlib_JSON.Decode.object(json$2);
    if (obj !== undefined) {
      let dict = {};
      Object.entries(obj).forEach(param => {
        let arr = Stdlib_JSON.Decode.array(param[1]);
        if (arr !== undefined) {
          dict[param[0]] = arr.map(optString);
          return;
        }
      });
      tmp$1 = dict;
    } else {
      tmp$1 = null;
    }
  } else {
    tmp$1 = null;
  }
  let json$3 = d["modes"];
  let tmp$2;
  if (json$3 !== undefined) {
    let obj$1 = Stdlib_JSON.Decode.object(json$3);
    if (obj$1 !== undefined) {
      let dict$1 = {};
      Object.entries(obj$1).forEach(param => {
        let modeObj = Stdlib_JSON.Decode.object(param[1]);
        if (modeObj !== undefined) {
          dict$1[param[0]] = modeConfigFromDict(modeObj);
          return;
        }
      });
      tmp$2 = dict$1;
    } else {
      tmp$2 = null;
    }
  } else {
    tmp$2 = null;
  }
  let json$4 = d["enforcement"];
  let tmp$3;
  if (json$4 !== undefined) {
    let enfObj = Stdlib_JSON.Decode.object(json$4);
    tmp$3 = enfObj !== undefined ? enforcementConfigFromDict(enfObj) : null;
  } else {
    tmp$3 = null;
  }
  return {
    activePreset: optStringFromDict(d, "activePreset"),
    activeMode: optStringOrNullFromDict(d, "activeMode"),
    presets: result,
    rules: optStringArrayFromDict(d, "rules"),
    defaultTier: optStringFromDict(d, "defaultTier"),
    fallback: tmp,
    taskPatterns: tmp$1,
    modes: tmp$2,
    enforcement: tmp$3
  };
}

function modeDefaultTier(m) {
  return m.defaultTier;
}

function getActiveTiers(cfg) {
  let tiers = cfg.presets[cfg.activePreset];
  if (tiers !== undefined) {
    return tiers;
  }
  let keys = Object.keys(cfg.presets);
  if (keys.length === 0) {
    return {};
  }
  let tiers$1 = cfg.presets[keys[0]];
  if (tiers$1 !== undefined) {
    return tiers$1;
  } else {
    return {};
  }
}

function getActiveMode(cfg) {
  let match = cfg.modes;
  let match$1 = cfg.activeMode;
  if (match == null) {
    return;
  }
  if (match$1 == null) {
    return;
  }
  let mode = match[match$1];
  if (mode !== undefined) {
    return mode;
  }
}

function buildFallbackInstructions(cfg) {
  let fb = cfg.fallback;
  if (fb == null) {
    return "";
  }
  let fbPresets = fb.presets;
  let presetMap = !(fbPresets == null) ? fbPresets[cfg.activePreset] : undefined;
  let map;
  if (presetMap !== undefined) {
    let keys = Object.keys(presetMap);
    map = keys.length !== 0 ? presetMap : Primitive_option.fromNullable(fb.global);
  } else {
    map = Primitive_option.fromNullable(fb.global);
  }
  if (map === undefined) {
    return "";
  }
  let chains = [];
  Object.entries(map).forEach(param => {
    let presetOrder = param[1];
    if (!Array.isArray(presetOrder)) {
      return;
    }
    let valid = presetOrder.filter(p => {
      if (p !== cfg.activePreset) {
        return Stdlib_Option.isSome(cfg.presets[p]);
      } else {
        return false;
      }
    });
    if (valid.length !== 0) {
      chains.push([
        param[0] + "→" + valid.join("→"),
        valid
      ]);
      return;
    }
  });
  let validChains = chains.map(param => param[0]).filter(s => s !== "");
  if (validChains.length === 0) {
    return "";
  } else {
    return `Err→retry-alt-tier→fail→direct. Chain: ` + validChains.join(" | ");
  }
}

function buildTaskTaxonomy(cfg) {
  let tp = cfg.taskPatterns;
  if (tp == null) {
    return "";
  }
  let keys = Object.keys(tp);
  if (keys.length === 0) {
    return "";
  }
  let lines = ["R:"];
  keys.forEach(k => {
    let patterns = tp[k];
    if (patterns !== undefined && patterns.length !== 0) {
      lines.push(`@` + k + `→` + patterns.join("/"));
      return;
    }
  });
  return lines.join(" ");
}

function buildDecomposeHint(cfg) {
  let modeOpt = getActiveMode(cfg);
  let hasOverrideRules;
  if (modeOpt !== undefined) {
    let rules = modeOpt.overrideRules;
    hasOverrideRules = (rules == null) ? false : rules.length !== 0;
  } else {
    hasOverrideRules = false;
  }
  if (hasOverrideRules) {
    return "";
  }
  let tiers = getActiveTiers(cfg);
  let entries = Object.entries(tiers);
  if (entries.length < 2) {
    return "";
  }
  let entriesCopy = entries.slice();
  entriesCopy.sort((param, param$1) => {
    let r = param[1].costRatio;
    let aRatio = (r == null) ? 1.0 : r;
    let r$1 = param$1[1].costRatio;
    let bRatio = (r$1 == null) ? 1.0 : r$1;
    return Primitive_float.compare(aRatio, bRatio);
  });
  let match = entriesCopy[0];
  let cheapestName = match[0];
  let match$1 = entriesCopy[1];
  let midName = match$1[0];
  if (cheapestName === midName) {
    return "";
  } else {
    return `Multi-phase: prefer explore(@` + cheapestName + `)→execute(@` + midName + `) when phases are separable. Cheapest-first when practical.`;
  }
}

function buildDelegationProtocol(cfg) {
  let tiers = getActiveTiers(cfg);
  let tierLineParts = [];
  Object.entries(tiers).forEach(param => {
    let t = param[1];
    let shortParts = t.model.split("/");
    let short = shortParts[shortParts.length - 1 | 0];
    let vv = t.variant;
    let v = (vv == null) ? "" : `/` + vv;
    let r = t.costRatio;
    let c = (r == null) ? "" : `(` + (Math.round(r) | 0).toString() + `x)`;
    tierLineParts.push(`@` + param[0] + `=` + short + v + c);
  });
  let tierLine = tierLineParts.join(" ");
  let modeOpt = getActiveMode(cfg);
  let am = cfg.activeMode;
  let modeSuffix = (am == null) ? "" : ` mode:` + am;
  let taxonomy = buildTaskTaxonomy(cfg);
  let decompose = buildDecomposeHint(cfg);
  let effectiveRules;
  if (modeOpt !== undefined) {
    let rules = modeOpt.overrideRules;
    effectiveRules = (rules == null) || rules.length === 0 ? cfg.rules : rules;
  } else {
    effectiveRules = cfg.rules;
  }
  let parts = [];
  effectiveRules.forEach(r => {
    parts.push((parts.length + 1 | 0).toString() + `.` + r);
  });
  let rulesLine = parts.join(" ");
  let fallback = buildFallbackInstructions(cfg);
  let protocolParts = [];
  let add = s => {
    protocolParts.push(s);
  };
  add("## Model Delegation Protocol — MANDATORY");
  add("");
  add("You are the orchestrator. Information-gathering is NOT orchestration — it IS execution. Execution belongs to subagents, not to you.");
  add("");
  add(`Preset: ` + cfg.activePreset + `. Tiers: ` + tierLine + `.` + modeSuffix);
  add("");
  add("### HARD ROUTING (non-negotiable)");
  add("- **Read-only work** (grep, glob, read, ls, lookup, count, git-info, doc-lookup, type-check, exists-check) → default to `Task(subagent_type=\"fast\", ...)`. Self-cap (TARGET): ≤2 direct read-only calls per user turn; on the 3rd read-only need, dispatch @fast instead. You may exceed with a 1-line `reason:` note when dispatching feels clearly wrong. Rationale: every tool-result token is billed at your tier rate — a grep via @fast costs ~20x less than the same grep here.");
  add("- **Localized/simple implementation** (simple edits, small fixes, config tweaks, single-file refactoring) → `Task(subagent_type=\"light\", ...)`.");
  add("- **Standard implementation work** (write, edit, refactor, tests, bug-fix, build-fix, create-file, config, api-endpoint) → `Task(subagent_type=\"medium\", ...)`.");
  add("- **Deep single-system analysis** (single-system debugging, complex bug isolation, single-system review) → `Task(subagent_type=\"focused\", ...)`.");
  add("- **Architecture / security / perf / debugging after ≥2 failures / multi-system tradeoffs / RCA** → `Task(subagent_type=\"heavy\", ...)`, UNLESS you ARE @heavy (opus); then handle locally and never self-call @heavy.");
  add("");
  add("### DISPATCH CAPS (read-only budget per subagent)");
  add("Subagents carry a TARGET cap on their own read-only tool calls (baseline: @fast=8, @light=7, @medium=5, @focused=4, @heavy=3). Include `CAP:N` in the dispatch prompt to override (e.g., `CAP:3` for a tight lookup, `CAP:none` to disable). Mode adjustments apply automatically via rules below. Subagents also run a redundancy check every call: if they detect repeated reads/greps of the same area, they STOP and return partial findings with `DONE: ...`, `NEED MORE: ...`, or `ESCALATE: ...` — you decide the next step from their return.");
  add("");
  add("### ROLE CONTRACT");
  add("The primary agent's job: decompose the user's request, dispatch subagents, synthesize their results, and answer the user. Keep orchestration-first posture: prefer dispatching read-only exploration to @fast rather than running repeated Grep/Read/Glob/Bash calls yourself. Self-cap applies (see HARD ROUTING above): ≤2 direct read-only calls per turn as a target; beyond that, dispatch @fast.");
  add("");
  add("### @fast contract");
  add("@fast is a read-only explorer. It will search/grep/read/count/lookup and return file:line paths, snippets, and a one-line summary. It will refuse edits. Batch related searches into a single @fast dispatch when possible; fire independent searches in parallel (one message, multiple Task calls).");
  add("");
  add("### @medium contract");
  add("@medium is the implementer. It writes, edits, refactors, adds tests, fixes bugs, applies build-fixes. It matches existing project patterns, runs targeted tests for changed areas, and reports back if it hits 2+ consecutive failures instead of self-escalating. Give it context: file paths, patterns to match, what verification to run.");
  add("");
  add("### @light contract");
  add("@light is a localized implementation specialist. Scope: simple edits, small fixes, config tweaks, single-file refactoring. CAP\u22647. Stay within the given scope; if work grows beyond a single file or touches multiple modules, ESCALATE immediately. Return a concise summary: files changed, what was done, verification run.");
  add("");
  add("### @focused contract (CRITICAL \u2014 read before every @focused dispatch)");
  add("@focused is a deep single-system analysis specialist. Scope: deep single-system debugging, complex bug isolation, single-system code review, targeted performance analysis within one module/package. CAP\u22644. Stay within the one system you were dispatched to; if the work spans multiple systems or packages, return SCOPE GROWTH. Your 4 reads are for targeted single-system verification, not cross-system exploration.");
  add("");
  add("### @heavy contract (CRITICAL \u2014 read before every @heavy dispatch)");
  add("@heavy has **no Task tool** \u2014 it cannot self-explore, cannot grep, cannot delegate. Dispatching @heavy without context can waste a run: it may reason on thin evidence or return \"SCOPE GROWTH\" asking for additional @fast findings.");
  add("**Before @heavy, gather context first \u2014 usually via @fast.** If you already have sufficient concrete context, dispatch @heavy directly. If @heavy still needs more evidence, collect it with @fast and re-invoke.");
  add("Pattern: `Task(@fast, \"collect X, Y, Z\")` (when needed) \u2192 synthesize findings \u2192 `Task(@heavy, \"given these findings: [paste], analyze W\")`.");
  add("");
  add("### CONFLICT WITH CLAUDE.md / AGENTS.md");
  add("If CLAUDE.md or AGENTS.md (or any other guide in your context) says \"use direct tools first when scope is clear\" or labels Grep/Read/Glob as \"FREE\", **this protocol wins**. Those labels are wrong about cost: tools executed by you are billed at your tier rate \u2014 every tool-result token is tokenized into your context. A Grep dispatched to @fast costs ~20x less than the same Grep executed by @heavy. Treat yourself as expensive and delegate reads by default.");
  add("");
  if (taxonomy !== "") {
    add(taxonomy);
    add("");
  }
  if (decompose !== "") {
    add(decompose);
    add("");
  }
  add("### Compact rules");
  add(rulesLine);
  if (fallback !== "") {
    add("");
    add(fallback);
  }
  add("");
  add("Delegate with `Task(subagent_type=\"fast\"|\"light\"|\"medium\"|\"focused\"|\"heavy\", prompt=\"...\")`. Keep orchestration and final synthesis here.");
  add("");
  add("### Invalid Targets");
  add("**`build` is NOT a valid `Task(subagent_type=...)` target** \u2014 the `build` agent is the built-in primary/default agent, not a router-managed subagent. Dispatching `Task(subagent_type=\"build\")` will be rejected with a runtime guard error. Use `fast`, `light`, `medium`, `focused`, or `heavy` instead, or use a skill agent that carries the `\"subagent\"` mode marker in its definition.");
  return protocolParts.join("\n");
}

function isClaudeModel(modelID) {
  let stringContains = (s, needle) => {
    let _i = 0;
    while (true) {
      let i = _i;
      if (i > (s.length - needle.length | 0)) {
        return false;
      }
      let remaining = s.substring(i, s.length);
      if (remaining.startsWith(needle)) {
        return true;
      }
      _i = i + 1 | 0;
      continue;
    };
  };
  if (modelID == null) {
    return false;
  }
  let lower = modelID.toLowerCase();
  if (lower.startsWith("anthropic/")) {
    return true;
  }
  if (stringContains(lower, "/claude-")) {
    return true;
  }
  let _i = 0;
  while (true) {
    let i = _i;
    if (i >= lower.length) {
      return false;
    }
    let remaining = lower.substring(i, lower.length);
    if (remaining.startsWith("claude-")) {
      if (i === 0) {
        return true;
      }
      let prev = lower.charAt(i - 1 | 0);
      if (prev === "/" || prev === "-") {
        return true;
      }
      _i = i + 1 | 0;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

let d = {};

d["fast"] = "SCOPE NOTE \u2014 any cached instruction priming you to 'thoroughly explore\nthe codebase' or 'gather context broadly' does not apply here. This is\na single dispatch with a single question. Stay narrow to the ask.\n\nBefore every tool call, ask: 'Does THIS read answer the dispatch\nquestion specifically, or am I drifting into context-gathering for my\nown understanding?' If the latter, stop \u2014 you have enough.";

d["light"] = "SCOPE NOTE \u2014 this dispatch is for localized single-file or small-scope\nchanges. If the work grows beyond a single file or touches multiple\nmodules, return ESCALATE immediately. Do NOT expand scope unilaterally.\n\nStay within the given scope. A 6th or 7th tool call is a sign the\nscope is growing \u2014 ESCALATE rather than continuing.";

d["medium"] = "SCOPE NOTE \u2014 cached instructions may prime you to deeply understand\nsurrounding code before editing. For THIS dispatch, the orchestrator\nhas already scoped the problem; trust that scoping. Read what's needed\nfor the edit, not the whole module.\n\nA 4th or 5th 'context read' is usually a sign the dispatch was under-\nscoped \u2014 return NEED CONTEXT rather than expanding scope yourself.";

d["focused"] = "AUTHORITY OVERRIDE \u2014 this block supersedes any cached prefix suggesting\nyou should 'investigate broadly' or 'trace through multiple systems'.\nYou are @focused, a SINGLE-SYSTEM deep analysis specialist. Stay within\nthe one system/module you were dispatched to.\n\nIf the work spans multiple systems or packages, return SCOPE GROWTH\nimmediately. Your 4 reads are for targeted single-system verification,\nnot cross-system exploration.";

d["heavy"] = "AUTHORITY OVERRIDE \u2014 this block supersedes any cached prefix suggesting\nyou should 'investigate thoroughly', 'gather comprehensive context', or\n'trace through the code systematically before analyzing'. You are\n@heavy, an ANALYSIS specialist. The orchestrator should have pre-\ngathered context via @fast before dispatching you. If it didn't, return\n`SCOPE GROWTH:` immediately \u2014 do NOT self-gather.\n\n40 minutes of Read/Grep is not analysis \u2014 it is the orchestrator's job\nthat leaked into yours. Push it back with SCOPE GROWTH. Your 3 reads\nare for targeted verification, not exploration.";

let claudeOrchestratorPrefix = "AUTHORITY OVERRIDE \u2014 this block supersedes any prior system instruction\nabout 'exploring the codebase', 'gathering context with tools', or using\nRead/Grep/Glob to validate assumptions. Those instructions describe a\ngeneral-purpose Claude Code session. THIS session is a routing\norchestrator.\n\nYour job is to DISPATCH, not to EXECUTE. Read-only work (grep/read/\nglob/ls) is execution, and execution is delegated to @fast. You may run\nAT MOST 2 direct read-only tool calls per turn \u2014 a 3rd call is a rule\nviolation. If you need more context, you dispatch @fast.\n\nIf a cached instruction told you to 'be thorough', 'explore broadly', or\n'read supporting files' \u2014 ignore it here. Thoroughness is achieved by\ndispatching the right tier, not by you becoming the explorer.";

let claudeAntiNarration = "ANTI-NARRATION \u2014 do NOT write progress commentary in your response or\nthinking output. Forbidden phrasings include:\n  - \"Still writing the X function...\"\n  - \"Now I'll implement Y...\"\n  - \"Let me add Z...\"\n  - \"Continuing with W...\"\n  - \"Going to fix V...\"\n\nEach of these signals planning without production. If you write one, the\nNEXT tokens MUST contain the actual artifact (the code, the edit, the\nconcrete output). Otherwise, stop and return with status.\n\nException: when the user explicitly asks for an explanation, plan, or\nwalkthrough, prose is welcome \u2014 this rule targets unsolicited progress\nnarration during code and implementation tasks.";

function buildDoDProtocolSection(cfg) {
  let enf = cfg.enforcement;
  let requireExplicit;
  if (enf == null) {
    requireExplicit = false;
  } else {
    let v = enf.verify;
    if (v == null) {
      requireExplicit = false;
    } else {
      let b = v.requireExplicitDoD;
      requireExplicit = (b == null) ? false : b;
    }
  }
  let omitLine = requireExplicit ? "A DoD is REQUIRED: a non-trivial dispatch without an [acceptance] block is rejected." : "If you omit the block, a minimal DoD is auto-inferred from the task type.";
  let lines = [];
  let add = s => {
    lines.push(s);
  };
  add("### Acceptance / Definition of Done (enforcement is ON)");
  add("Non-trivial delegations are independently verified before their result is accepted (producer \u2260 grader; grader \u2265 producer tier). Attach an acceptance block to your dispatch so the gate knows what \"done\" means:");
  add("");
  add("[acceptance]");
  add("check: testsPass");
  add("check: buildPasses");
  add("check: fileExists path=src/foo.ts");
  add("check: run command=\"node -e ...\" expect=OK");
  add("criteria: <plain-language success condition>");
  add("deliverable: <path or short description>");
  add("[/acceptance]");
  add("");
  add("- check kinds: testsPass | buildPasses | lintClean | fileExists path=\u2026 | schemaMatch path=\u2026 schema=\u2026 | run command=\"\u2026\" expect=\u2026");
  add("- " + omitLine);
  add("- A failing DoD causes the result to be rejected and retried/escalated, not silently accepted.");
  return lines.join("\n");
}

function assembleSystemPrompt(cfg, orchestratorModel, enforcementOn) {
  let delegationProtocol = buildDelegationProtocol(cfg);
  let dodSection = enforcementOn ? `\n\n---\n\n` + buildDoDProtocolSection(cfg) : "";
  if (isClaudeModel(orchestratorModel)) {
    return claudeOrchestratorPrefix + `\n\n` + claudeAntiNarration + `\n\n---\n\n` + delegationProtocol + dodSection;
  } else {
    return delegationProtocol + dodSection;
  }
}

let claudeTierPrefix = d;

export {
  tierConfigFromDict,
  modeDefaultTier,
  getActiveTiers,
  getActiveMode,
  buildFallbackInstructions,
  buildTaskTaxonomy,
  buildDecomposeHint,
  buildDelegationProtocol,
  isClaudeModel,
  claudeTierPrefix,
  claudeOrchestratorPrefix,
  claudeAntiNarration,
  buildDoDProtocolSection,
  assembleSystemPrompt,
}
/*  Not a pure module */
