// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TierLadderHelpers from "./TierLadderHelpers.res.mjs";

let defaultTierNames = [
  "fast",
  "light",
  "medium",
  "focused",
  "heavy"
];

function resolveLadder(cfg) {
  let e = cfg.enforcement;
  if (e === undefined) {
    return TierLadderHelpers.resolveFromPreset(cfg);
  }
  let esc = e.escalate;
  if (esc === undefined) {
    return TierLadderHelpers.resolveFromPreset(cfg);
  }
  let arr = esc.ladder;
  if (arr !== undefined) {
    return arr.slice();
  } else {
    return TierLadderHelpers.resolveFromPreset(cfg);
  }
}

export {
  defaultTierNames,
  resolveLadder,
}
/* No side effect */
