// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as Config from "./Config.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as TierLadder from "./TierLadder.res.mjs";

function arrayEqual(a, b) {
  Test.assertion(undefined, "arrayEqual", (a, b) => Belt_Array.eq(a, b, (x, y) => x === y), a, b);
}

function notSameRef(a, b) {
  Test.assertion(undefined, "notSameRef", (a, b) => a !== b, a, b);
}

function makeCfg(tiers, explicitLadder) {
  let tiersJson = tiers.map(param => {
    let costRatio = param[2];
    let costPart = costRatio !== undefined ? `,"costRatio":` + costRatio.toString() : "";
    return `    "` + param[0] + `":{"model":"` + param[1] + `","description":"","whenToUse":[]` + costPart + `}`;
  }).join(",\n");
  let ladderJson;
  if (explicitLadder !== undefined) {
    let items = explicitLadder.map(s => `"` + s + `"`).join(",");
    ladderJson = `,"enforcement":{"escalate":{"ladder":[` + items + `]}}`;
  } else {
    ladderJson = "";
  }
  let jsonStr = `{
  "activePreset": "default",
  "presets": {"default": {
` + tiersJson + `
  }},
  "rules": [],
  "defaultTier": "medium"` + ladderJson + `
}`;
  let cfg = Config.parse(JSON.parse(jsonStr));
  if (cfg !== undefined) {
    return cfg;
  } else {
    return Stdlib_Exn.raiseError("makeCfg: failed to parse constructed JSON");
  }
}

Test.test("explicit enforcement.escalate.ladder is returned unchanged", () => {
  let cfg = makeCfg([[
      "fast",
      "a/f",
      undefined
    ]], [
    "medium",
    "heavy"
  ]);
  let result = TierLadder.resolveLadder(cfg);
  arrayEqual(result, [
    "medium",
    "heavy"
  ]);
});

Test.test("explicit ladder is copied (not the same array reference)", () => {
  let cfg = makeCfg([[
      "fast",
      "a/f",
      undefined
    ]], [
    "medium",
    "heavy"
  ]);
  let result = TierLadder.resolveLadder(cfg);
  notSameRef(result, [
    "medium",
    "heavy"
  ]);
  arrayEqual(result, [
    "medium",
    "heavy"
  ]);
});

Test.test("explicit ladder wins over preset costRatio ordering", () => {
  let cfg = makeCfg([
    [
      "fast",
      "a/f",
      1.0
    ],
    [
      "medium",
      "a/m",
      5.0
    ],
    [
      "heavy",
      "a/h",
      20.0
    ]
  ], [
    "heavy",
    "fast"
  ]);
  arrayEqual(TierLadder.resolveLadder(cfg), [
    "heavy",
    "fast"
  ]);
});

Test.test("preset tiers sorted by costRatio ascending", () => {
  let cfg = makeCfg([
    [
      "fast",
      "a/f",
      1.0
    ],
    [
      "light",
      "a/l",
      2.0
    ],
    [
      "medium",
      "a/m",
      5.0
    ],
    [
      "focused",
      "a/fc",
      10.0
    ],
    [
      "heavy",
      "a/h",
      20.0
    ]
  ], undefined);
  arrayEqual(TierLadder.resolveLadder(cfg), [
    "fast",
    "light",
    "medium",
    "focused",
    "heavy"
  ]);
});

Test.test("missing costRatio sorts to end (stable insertion order tie-break)", () => {
  let cfg = makeCfg([
    [
      "alpha",
      "a/a",
      undefined
    ],
    [
      "beta",
      "a/b",
      1.0
    ],
    [
      "gamma",
      "a/g",
      undefined
    ]
  ], undefined);
  arrayEqual(TierLadder.resolveLadder(cfg), [
    "beta",
    "alpha",
    "gamma"
  ]);
});

Test.test("equal costRatio preserves insertion order (stable sort)", () => {
  let cfg = makeCfg([
    [
      "first",
      "a/f",
      5.0
    ],
    [
      "second",
      "a/s",
      5.0
    ],
    [
      "third",
      "a/t",
      5.0
    ]
  ], undefined);
  arrayEqual(TierLadder.resolveLadder(cfg), [
    "first",
    "second",
    "third"
  ]);
});

Test.test("three-tier preset returns exactly three rungs", () => {
  let cfg = makeCfg([
    [
      "fast",
      "a/f",
      1.0
    ],
    [
      "medium",
      "a/m",
      5.0
    ],
    [
      "heavy",
      "a/h",
      20.0
    ]
  ], undefined);
  arrayEqual(TierLadder.resolveLadder(cfg), [
    "fast",
    "medium",
    "heavy"
  ]);
});

Test.test("two-tier preset returns exactly two rungs", () => {
  let cfg = makeCfg([
    [
      "fast",
      "a/f",
      1.0
    ],
    [
      "heavy",
      "a/h",
      20.0
    ]
  ], undefined);
  arrayEqual(TierLadder.resolveLadder(cfg), [
    "fast",
    "heavy"
  ]);
});

Test.test("single-tier preset returns exactly one rung", () => {
  let cfg = makeCfg([[
      "heavy",
      "a/h",
      20.0
    ]], undefined);
  arrayEqual(TierLadder.resolveLadder(cfg), ["heavy"]);
});

Test.test("preset with no costRatio returns present tiers in insertion order", () => {
  let cfg = makeCfg([
    [
      "zebra",
      "a/z",
      undefined
    ],
    [
      "alpha",
      "a/a",
      undefined
    ]
  ], undefined);
  arrayEqual(TierLadder.resolveLadder(cfg), [
    "zebra",
    "alpha"
  ]);
});

Test.test("does not mutate the input cfg", () => {
  let cfg = makeCfg([
    [
      "fast",
      "a/f",
      1.0
    ],
    [
      "medium",
      "a/m",
      5.0
    ]
  ], ["medium"]);
  let ladderBefore = cfg.enforcement;
  TierLadder.resolveLadder(cfg);
  Test.assertion(undefined, "cfgNotMutated", (before, after) => before === after, ladderBefore, cfg.enforcement);
});

Test.test("does not mutate the explicit ladder array", () => {
  let cfg = makeCfg([[
      "fast",
      "a/f",
      undefined
    ]], [
    "medium",
    "heavy"
  ]);
  let getLadder = cfg => {
    let e = cfg.enforcement;
    if (e === undefined) {
      return [];
    }
    let esc = e.escalate;
    if (esc === undefined) {
      return [];
    }
    let l = esc.ladder;
    if (l !== undefined) {
      return l;
    } else {
      return [];
    }
  };
  let cfgLadderBefore = getLadder(cfg);
  TierLadder.resolveLadder(cfg);
  let cfgLadderAfter = getLadder(cfg);
  Test.assertion(undefined, "ladderNotMutated", (before, after) => Belt_Array.eq(before, after, (x, y) => x === y), cfgLadderBefore, cfgLadderAfter);
});

Test.test("returns a fresh array on every call", () => {
  let cfg = makeCfg([
    [
      "fast",
      "a/f",
      1.0
    ],
    [
      "medium",
      "a/m",
      5.0
    ]
  ], undefined);
  let r1 = TierLadder.resolveLadder(cfg);
  let r2 = TierLadder.resolveLadder(cfg);
  notSameRef(r1, r2);
  arrayEqual(r1, r2);
});

Test.test("custom three-tier preset resolves to 3 rungs with no extra tiers", () => {
  let cfg = makeCfg([
    [
      "turbo",
      "a/t",
      15.0
    ],
    [
      "fast",
      "a/f",
      1.0
    ],
    [
      "heavy",
      "a/h",
      20.0
    ]
  ], undefined);
  let result = TierLadder.resolveLadder(cfg);
  Test.assertion(undefined, "length3", (r, param) => r === 3, result.length, 3);
  arrayEqual(result, [
    "fast",
    "turbo",
    "heavy"
  ]);
});

Test.test("enforcement absent returns preset tiers sorted by costRatio", () => {
  let cfg = makeCfg([
    [
      "fast",
      "a/f",
      3.0
    ],
    [
      "heavy",
      "a/h",
      1.0
    ]
  ], undefined);
  arrayEqual(TierLadder.resolveLadder(cfg), [
    "heavy",
    "fast"
  ]);
});

Test.test("returns all tiers when skipTiers is not set", () => {
  let cfg = makeCfg([
    [
      "fast",
      "a/f",
      1.0
    ],
    [
      "medium",
      "a/m",
      5.0
    ],
    [
      "heavy",
      "a/h",
      20.0
    ]
  ], undefined);
  arrayEqual(TierLadder.resolveLadder(cfg), [
    "fast",
    "medium",
    "heavy"
  ]);
});

export {
  arrayEqual,
  notSameRef,
  makeCfg,
}
/*  Not a pure module */
