// Generated by ReScript, PLEASE EDIT WITH CARE


function getCostRatio(tier) {
  let r = tier.costRatio;
  if (r !== undefined) {
    return r;
  } else {
    return 1.0e15;
  }
}

function defaultThreeTier() {
  return [
    "fast",
    "medium",
    "heavy"
  ];
}

function resolveFromPreset(cfg) {
  let preset = cfg.presets[cfg.activePreset];
  if (preset === undefined) {
    return [
      "fast",
      "medium",
      "heavy"
    ];
  }
  let tierNames = Object.keys(preset);
  let len = tierNames.length;
  if (len <= 0) {
    return [
      "fast",
      "medium",
      "heavy"
    ];
  }
  let pairs = tierNames.map(name => {
    let tier = preset[name];
    return [
      name,
      getCostRatio(tier)
    ];
  });
  let sorted = pairs.toSorted((param, param$1) => param[1] - param$1[1]);
  return sorted.map(param => param[0]);
}

export {
  getCostRatio,
  defaultThreeTier,
  resolveFromPreset,
}
/* No side effect */
