// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

let validCheckKinds = [
  "run",
  "fileExists",
  "schemaMatch",
  "testsPass",
  "buildPasses",
  "lintClean"
];

let validDodKinds = [
  "deterministic",
  "checker",
  "none"
];

function parseKvPairs(s) {
  let result = {};
  let parts = s.split(" ");
  for (let i = 0, i_finish = parts.length; i < i_finish; ++i) {
    let part = parts[i];
    if (part !== undefined) {
      let eqIdx = "=".indexOf(part);
      if (eqIdx > 0) {
        let key = part.substring(0, eqIdx);
        let rest = part.substring(eqIdx + 1 | 0, part.length);
        let val = rest.startsWith("\"") && rest.endsWith("\"") ? rest.substring(1, rest.length - 1 | 0) : rest;
        result[key] = val;
      }
    }
  }
  return result;
}

function summarizeDispatch(text) {
  if (text === "") {
    return "";
  }
  let lines = Js_string.split("\n", text);
  let _i = 0;
  let acc = "";
  while (true) {
    let i = _i;
    if (i >= lines.length) {
      return acc;
    }
    let trimmed = lines[i];
    if (trimmed !== undefined) {
      let collapsed = trimmed.trim().replace(/\\s+/, " ");
      if (collapsed !== "") {
        if (collapsed.length > 120) {
          return Js_string.slice(0, 120, collapsed);
        } else {
          return collapsed;
        }
      }
      _i = i + 1 | 0;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function normalizeDoD(d) {
  let checks = Array.isArray(d.checks) ? Belt_Array.concatMany([d.checks]) : [];
  let criteria = Array.isArray(d.criteria) ? Belt_Array.concatMany([d.criteria]) : [];
  let kind = checks.length !== 0 ? "deterministic" : (
      criteria.length !== 0 ? "checker" : "none"
    );
  let v = d.deliverable;
  let rawDeliverable = (v == null) ? "" : v.trim();
  let deliverable = rawDeliverable !== "" ? rawDeliverable : null;
  return {
    kind: kind,
    checks: checks,
    criteria: criteria,
    deliverable: deliverable,
    source: d.source
  };
}

function makeCheckKindSet() {
  let s = {};
  for (let i = 0, i_finish = validCheckKinds.length; i < i_finish; ++i) {
    let k = validCheckKinds[i];
    if (k !== undefined) {
      s[k] = true;
    }
  }
  return s;
}

let checkKindSet = makeCheckKindSet();

function makeDodKindSet() {
  let s = {};
  for (let i = 0, i_finish = validDodKinds.length; i < i_finish; ++i) {
    let k = validDodKinds[i];
    if (k !== undefined) {
      s[k] = true;
    }
  }
  return s;
}

let dodKindSet = makeDodKindSet();

let openTagRe = /^\s*\[(acceptance|dod)\]\s*$/i;

let closeTagRe = /^\s*\[\/(acceptance|dod)\]\s*$/i;

function findOpenTag(lines, start) {
  let _i = start;
  while (true) {
    let i = _i;
    if (i >= lines.length) {
      return -1;
    }
    let line = lines[i];
    if (line !== undefined) {
      if (openTagRe.test(line)) {
        return i;
      }
      _i = i + 1 | 0;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function findCloseTag(lines, start) {
  let _i = start;
  while (true) {
    let i = _i;
    if (i >= lines.length) {
      return -1;
    }
    let line = lines[i];
    if (line !== undefined) {
      if (closeTagRe.test(line)) {
        return i;
      }
      _i = i + 1 | 0;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function sliceInner(lines, start, end) {
  let _i = start;
  let _acc = [];
  while (true) {
    let acc = _acc;
    let i = _i;
    if (i >= end) {
      return acc;
    }
    let line = lines[i];
    if (line !== undefined) {
      _acc = Belt_Array.concatMany([
        acc,
        [line]
      ]);
      _i = i + 1 | 0;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function kindStrToCheckKind(s) {
  switch (s) {
    case "buildPasses" :
      return "buildPasses";
    case "fileExists" :
      return "fileExists";
    case "lintClean" :
      return "lintClean";
    case "schemaMatch" :
      return "schemaMatch";
    case "testsPass" :
      return "testsPass";
    default:
      return "run";
  }
}

function kindStrToDodKind(s) {
  switch (s) {
    case "checker" :
      return "checker";
    case "deterministic" :
      return "deterministic";
    default:
      return "none";
  }
}

function processLine(line, state) {
  let trimmed = line.trim();
  if (trimmed === "") {
    return;
  }
  let lline = trimmed.toLowerCase();
  if (lline.startsWith("check:")) {
    if (state.invalidKindDirective) {
      return;
    }
    let rest = trimmed.slice(6, trimmed.length);
    let restTrimmed = rest.trim();
    let spaceIdx = restTrimmed.indexOf(" ");
    let kindStr = spaceIdx === -1 ? restTrimmed : restTrimmed.slice(0, spaceIdx);
    let remainder = spaceIdx === -1 ? "" : restTrimmed.slice(spaceIdx + 1 | 0, restTrimmed.length);
    if (!Belt_Option.isSome(checkKindSet[kindStr])) {
      return;
    }
    let kvPairs = parseKvPairs(remainder);
    let v = kvPairs["command"];
    let v$1 = kvPairs["expect"];
    let v$2 = kvPairs["path"];
    let v$3 = kvPairs["schema"];
    let check_kind = kindStrToCheckKind(kindStr);
    let check_command = v !== undefined ? v : null;
    let check_expect = v$1 !== undefined ? v$1 : null;
    let check_path = v$2 !== undefined ? v$2 : null;
    let check_schema = v$3 !== undefined ? v$3 : null;
    let check = {
      kind: check_kind,
      command: check_command,
      expect: check_expect,
      path: check_path,
      schema: check_schema
    };
    state.checks = Belt_Array.concatMany([
      state.checks,
      [check]
    ]);
    return;
  }
  if (lline.startsWith("criteria:")) {
    if (state.invalidKindDirective) {
      return;
    }
    let rest$1 = trimmed.slice(9, trimmed.length);
    let restTrimmed$1 = rest$1.trim();
    if (restTrimmed$1 !== "") {
      state.criteria = Belt_Array.concatMany([
        state.criteria,
        [restTrimmed$1]
      ]);
      return;
    } else {
      return;
    }
  }
  if (lline.startsWith("deliverable:")) {
    if (state.invalidKindDirective) {
      return;
    }
    let rest$2 = trimmed.slice(12, trimmed.length);
    let restTrimmed$2 = rest$2.trim();
    state.deliverable = restTrimmed$2 !== "" ? restTrimmed$2 : null;
    return;
  }
  if (!lline.startsWith("kind:")) {
    return;
  }
  let rest$3 = trimmed.slice(5, trimmed.length);
  let restTrimmed$3 = rest$3.toLowerCase().trim();
  if (restTrimmed$3 === "") {
    state.invalidKindDirective = true;
    state.checks = [];
    state.criteria = [];
    state.deliverable = null;
    state.kindHint = "none";
  } else if (Belt_Option.isSome(dodKindSet[restTrimmed$3])) {
    state.kindHint = kindStrToDodKind(restTrimmed$3);
  } else {
    state.invalidKindDirective = true;
    state.checks = [];
    state.criteria = [];
    state.deliverable = null;
    state.kindHint = "none";
  }
}

function processLines(lines, state) {
  for (let i = 0, i_finish = lines.length; i < i_finish; ++i) {
    let line = lines[i];
    if (line !== undefined) {
      processLine(line, state);
    }
  }
}

function parseAcceptanceBlock(text, source) {
  let lines = Js_string.split("\n", text);
  let openIdx = findOpenTag(lines, 0);
  if (openIdx === -1) {
    return null;
  }
  let closeIdx = findCloseTag(lines, openIdx + 1 | 0);
  if (closeIdx === -1) {
    return null;
  }
  let innerLines = sliceInner(lines, openIdx + 1 | 0, closeIdx);
  let state = {
    checks: [],
    criteria: [],
    deliverable: null,
    kindHint: null,
    invalidKindDirective: false
  };
  processLines(innerLines, state);
  let finalKind;
  if (state.invalidKindDirective) {
    finalKind = "none";
  } else {
    let k = state.kindHint;
    finalKind = (k == null) ? "none" : k;
  }
  return normalizeDoD({
    kind: finalKind,
    checks: state.checks,
    criteria: state.criteria,
    deliverable: state.deliverable,
    source: source
  });
}

function parseDoDFromDispatch(dispatchText) {
  return parseAcceptanceBlock(dispatchText, "explicit");
}

function parseDoDFromAnnotation(annotationText) {
  return parseAcceptanceBlock(annotationText, "annotation");
}

function inferDoD(dispatchText, _tier, hints) {
  let lower = dispatchText.toLowerCase();
  let p = hints.declaredPath;
  let hasDeclaredPath = (p == null) ? false : p.trim() !== "";
  let category = /\\b(bug|fix|broken|regression|failing)\\b/.test(lower) ? "bugfix" : (
      /\\b(refactor|rename|extract|restructure|cleanup|clean up)\\b/.test(lower) ? "refactor" : (
          /\\b(write|generate|emit|scaffold)\\b/.test(lower) && hasDeclaredPath ? "writeFile" : (
              /\\b(implement|add|feature|create|build|endpoint|function|component|fix)\\b/.test(lower) ? "impl" : (
                  /\\b(test|spec|coverage)\\b/.test(lower) ? "test" : "unknown"
                )
            )
        )
    );
  let checks;
  if (category === "bugfix" || category === "impl") {
    let cmd = hints.buildCommand;
    let buildCheck = !(cmd == null) && cmd.trim() !== "" ? ({
        kind: "buildPasses",
        command: cmd,
        expect: null,
        path: null,
        schema: null
      }) : undefined;
    let cmd$1 = hints.testCommand;
    let testCheck = !(cmd$1 == null) && cmd$1.trim() !== "" ? ({
        kind: "testsPass",
        command: cmd$1,
        expect: null,
        path: null,
        schema: null
      }) : undefined;
    checks = buildCheck !== undefined ? (
        testCheck !== undefined ? [
            buildCheck,
            testCheck
          ] : [buildCheck]
      ) : (
        testCheck !== undefined ? [testCheck] : []
      );
  } else if (category === "refactor") {
    let cmd$2 = hints.buildCommand;
    let buildCheck$1 = !(cmd$2 == null) && cmd$2.trim() !== "" ? ({
        kind: "buildPasses",
        command: cmd$2,
        expect: null,
        path: null,
        schema: null
      }) : undefined;
    let cmd$3 = hints.lintCommand;
    let lintCheck = !(cmd$3 == null) && cmd$3.trim() !== "" ? ({
        kind: "lintClean",
        command: cmd$3,
        expect: null,
        path: null,
        schema: null
      }) : undefined;
    checks = buildCheck$1 !== undefined ? (
        lintCheck !== undefined ? [
            buildCheck$1,
            lintCheck
          ] : [buildCheck$1]
      ) : (
        lintCheck !== undefined ? [lintCheck] : []
      );
  } else if (category === "writeFile") {
    let p$1 = hints.declaredPath;
    if (p$1 == null) {
      checks = [];
    } else {
      let trimmed = p$1.trim();
      checks = trimmed !== "" ? [{
            kind: "fileExists",
            command: null,
            expect: null,
            path: trimmed,
            schema: null
          }] : [];
    }
  } else if (category === "test") {
    let cmd$4 = hints.testCommand;
    checks = (cmd$4 == null) ? [] : (
        cmd$4.trim() !== "" ? [{
              kind: "testsPass",
              command: cmd$4,
              expect: null,
              path: null,
              schema: null
            }] : []
      );
  } else {
    checks = [];
  }
  let criteria;
  if (checks.length === 0) {
    let summary = summarizeDispatch(dispatchText);
    criteria = [summary !== "" ? summary : "the delegated task is completed as described in the dispatch"];
  } else {
    criteria = [];
  }
  let p$2 = hints.declaredPath;
  let rawPath = (p$2 == null) ? "" : p$2.trim();
  let deliverable = rawPath !== "" ? rawPath : null;
  let kind = checks.length !== 0 ? "deterministic" : "checker";
  return normalizeDoD({
    kind: kind,
    checks: checks,
    criteria: criteria,
    deliverable: deliverable,
    source: "inferred"
  });
}

function isCheckable(d) {
  let match = d.kind;
  if (match === "deterministic") {
    return d.checks.length !== 0;
  } else if (match === "checker") {
    return d.criteria.length !== 0;
  } else {
    return false;
  }
}

function getCheckCommand(c) {
  return c.command;
}

function getCheckExpect(c) {
  return c.expect;
}

function getCheckPath(c) {
  return c.path;
}

function getCheckSchema(c) {
  return c.schema;
}

function getCheckKind(c) {
  return c.kind;
}

function getDodDeliverable(d) {
  return d.deliverable;
}

function getDodKind(d) {
  return d.kind;
}

function getDodChecks(d) {
  return d.checks;
}

function getDodCriteria(d) {
  return d.criteria;
}

function getDodSource(d) {
  return d.source;
}

export {
  summarizeDispatch,
  normalizeDoD,
  parseAcceptanceBlock,
  parseDoDFromDispatch,
  parseDoDFromAnnotation,
  inferDoD,
  isCheckable,
  getCheckCommand,
  getCheckExpect,
  getCheckPath,
  getCheckSchema,
  getCheckKind,
  getDodDeliverable,
  getDodKind,
  getDodChecks,
  getDodCriteria,
  getDodSource,
}
/* checkKindSet Not a pure module */
