// Generated by ReScript, PLEASE EDIT WITH CARE

import * as VerifyDoD from "./VerifyDoD.res.mjs";
import * as VerifyDispatchCore from "./VerifyDispatchCore.res.mjs";

let summarizeDispatch = VerifyDoD.summarizeDispatch;

let normalizeDoD = VerifyDoD.normalizeDoD;

let parseAcceptanceBlock = VerifyDoD.parseAcceptanceBlock;

let parseDoDFromDispatch = VerifyDoD.parseDoDFromDispatch;

let parseDoDFromAnnotation = VerifyDoD.parseDoDFromAnnotation;

let inferDoD = VerifyDoD.inferDoD;

let isCheckable = VerifyDoD.isCheckable;

let getCheckCommand = VerifyDoD.getCheckCommand;

let getCheckExpect = VerifyDoD.getCheckExpect;

let getCheckPath = VerifyDoD.getCheckPath;

let getCheckSchema = VerifyDoD.getCheckSchema;

let getCheckKind = VerifyDoD.getCheckKind;

let getDodDeliverable = VerifyDoD.getDodDeliverable;

let getDodKind = VerifyDoD.getDodKind;

let getDodChecks = VerifyDoD.getDodChecks;

let getDodCriteria = VerifyDoD.getDodCriteria;

let getDodSource = VerifyDoD.getDodSource;

let extractChangedFile = VerifyDispatchCore.extractChangedFile;

let createChangedFileStore = VerifyDispatchCore.createChangedFileStore;

let parseTaskResult = VerifyDispatchCore.parseTaskResult;

let buildDelegationDoD = VerifyDispatchCore.buildDelegationDoD;

let tierModel = VerifyDispatchCore.tierModel;

let shouldVerifyTask = VerifyDispatchCore.shouldVerifyTask;

let buildForcingNote = VerifyDispatchCore.buildForcingNote;

let buildAcceptedSuffix = VerifyDispatchCore.buildAcceptedSuffix;

export {
  summarizeDispatch,
  normalizeDoD,
  parseAcceptanceBlock,
  parseDoDFromDispatch,
  parseDoDFromAnnotation,
  inferDoD,
  isCheckable,
  getCheckCommand,
  getCheckExpect,
  getCheckPath,
  getCheckSchema,
  getCheckKind,
  getDodDeliverable,
  getDodKind,
  getDodChecks,
  getDodCriteria,
  getDodSource,
  extractChangedFile,
  createChangedFileStore,
  parseTaskResult,
  buildDelegationDoD,
  tierModel,
  shouldVerifyTask,
  buildForcingNote,
  buildAcceptedSuffix,
}
/* VerifyDoD Not a pure module */
