// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as VerifyDoD from "./VerifyDoD.res.mjs";

function assertionEqual(operator, expected, actual) {
  Test.assertion(undefined, operator, (a, b) => a === b, actual, expected);
}

function assertionTrue(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === true, actual, true);
}

function assertionFalse(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === false, actual, false);
}

function assertionContains(operator, needle, haystack) {
  let contains = haystack.indexOf(needle) >= 0;
  Test.assertion(undefined, operator, (_a, _b) => _b === true, contains, true);
}

Test.test("summarizeDispatch: empty string returns empty", () => {
  let result = VerifyDoD.summarizeDispatch("");
  assertionEqual("empty input", "", result);
});

Test.test("summarizeDispatch: single-line dispatch returns trimmed", () => {
  let result = VerifyDoD.summarizeDispatch("  fix the auth bug  ");
  assertionEqual("trimmed", "fix the auth bug", result);
});

Test.test("summarizeDispatch: multi-line dispatch returns first non-empty line", () => {
  let result = VerifyDoD.summarizeDispatch("implement the parser\nsecond line\nthird line");
  assertionEqual("first line", "implement the parser", result);
});

Test.test("summarizeDispatch: leading blank lines skip to first non-empty", () => {
  let result = VerifyDoD.summarizeDispatch("\n\n  add tests  \nmore content");
  assertionEqual("skips blanks", "add tests", result);
});

Test.test("summarizeDispatch: preserves content after first line", () => {
  let result = VerifyDoD.summarizeDispatch("main task\ndetail line");
  assertionContains("contains first", "main task", result);
});

Test.test("parseAcceptanceBlock: well-formed block returns Some(dod)", () => {
  let result = VerifyDoD.parseAcceptanceBlock("[acceptance]\ncheck: run \"npm test\"\ncheck: build \"npm run build\"\n[/acceptance]", "explicit");
  if (result == null) {
    return assertionTrue("should be Some", false);
  } else {
    return assertionTrue("dod returned", true);
  }
});

Test.test("parseAcceptanceBlock: missing close tag returns null", () => {
  let result = VerifyDoD.parseAcceptanceBlock("[acceptance]\ncheck: run \"npm test\"\n", "explicit");
  if (result == null) {
    return assertionTrue("null on missing close", true);
  } else {
    return assertionTrue("should be None", false);
  }
});

Test.test("parseAcceptanceBlock: empty block returns dod with kind=#none", () => {
  let result = VerifyDoD.parseAcceptanceBlock("[acceptance]\n[/acceptance]", "explicit");
  if (result == null) {
    return assertionTrue("should be Some", false);
  } else {
    return assertionEqual("kind none", "none", VerifyDoD.getDodKind(result));
  }
});

Test.test("parseAcceptanceBlock: whitespace-only block returns dod kind=#none", () => {
  let result = VerifyDoD.parseAcceptanceBlock("   [acceptance]   \n  \n  [/acceptance]  ", "explicit");
  if (result == null) {
    return assertionTrue("should be Some", false);
  } else {
    return assertionEqual("whitespace→none", "none", VerifyDoD.getDodKind(result));
  }
});

Test.test("parseAcceptanceBlock: mixed check kinds parse correctly", () => {
  let result = VerifyDoD.parseAcceptanceBlock("[acceptance]\ncheck: testsPass\ncheck: buildPasses\ncheck: lintClean\n[/acceptance]", "annotation");
  if (result == null) {
    return assertionTrue("should be Some", false);
  }
  let checks = VerifyDoD.getDodChecks(result);
  assertionEqual("3 checks", "3", checks.length.toString());
});

Test.test("parseAcceptanceBlock: fileExists check parses path", () => {
  let result = VerifyDoD.parseAcceptanceBlock("[acceptance]\ncheck: fileExists \"src/auth.ts\"\n[/acceptance]", "explicit");
  if (result == null) {
    return assertionTrue("should be Some", false);
  }
  let checks = VerifyDoD.getDodChecks(result);
  assertionEqual("1 check", "1", checks.length.toString());
});

Test.test("parseDoDFromDispatch: dispatch without [acceptance] returns null", () => {
  let result = VerifyDoD.parseDoDFromDispatch("just a plain dispatch without any acceptance block");
  if (result == null) {
    return assertionTrue("null without block", true);
  } else {
    return assertionTrue("should not be None", false);
  }
});

Test.test("parseDoDFromDispatch: dispatch with [acceptance] returns dod", () => {
  let result = VerifyDoD.parseDoDFromDispatch("implement login\n[acceptance]\ncheck: run \"npm test\"\n[/acceptance]");
  if (result == null) {
    return assertionTrue("should not be None", false);
  } else {
    return assertionTrue("dod parsed", true);
  }
});

Test.test("parseDoDFromDispatch: identical text to parseDoDFromAnnotation produces same dod", () => {
  let identicalBlock = "[acceptance]\ncheck: testsPass\n[/acceptance]";
  let fromDispatch = VerifyDoD.parseDoDFromDispatch(identicalBlock);
  let fromAnnotation = VerifyDoD.parseDoDFromAnnotation(identicalBlock);
  if (fromDispatch == null) {
    return assertionTrue("should not be None", false);
  }
  if (fromAnnotation == null) {
    return assertionTrue("should not be None", false);
  }
  let k1 = VerifyDoD.getDodKind(fromDispatch);
  let k2 = VerifyDoD.getDodKind(fromAnnotation);
  assertionEqual("same kind", k1, k2);
});

Test.test("parseDoDFromAnnotation: well-formed annotation returns dod", () => {
  let result = VerifyDoD.parseDoDFromAnnotation("[acceptance]\ncheck: buildPasses\ncheck: lintClean\n[/acceptance]");
  if (result == null) {
    return assertionTrue("should not be None", false);
  }
  let checks = VerifyDoD.getDodChecks(result);
  assertionEqual("2 checks", "2", checks.length.toString());
});

Test.test("parseDoDFromAnnotation: empty string returns null", () => {
  let result = VerifyDoD.parseDoDFromAnnotation("");
  if (result == null) {
    return assertionTrue("null on empty", true);
  } else {
    return assertionTrue("should not be None", false);
  }
});

Test.test("parseDoDFromAnnotation: annotation with criteria lines", () => {
  let result = VerifyDoD.parseDoDFromAnnotation("[acceptance]\ncheck: run \"make test\"\ncriteria: must pass CI\ncriteria: no regressions\n[/acceptance]");
  if (result == null) {
    return assertionTrue("should not be None", false);
  }
  VerifyDoD.getDodCriteria(result);
  assertionTrue("has criteria", true);
});

Test.test("inferDoD: dispatch text matching impl keyword creates checks", () => {
  let hints_testCommand = null;
  let hints_lintCommand = null;
  let hints_declaredPath = null;
  let hints = {
    testCommand: hints_testCommand,
    buildCommand: "make build",
    lintCommand: hints_lintCommand,
    declaredPath: hints_declaredPath
  };
  let result = VerifyDoD.inferDoD("build the project", "tier", hints);
  let checks = VerifyDoD.getDodChecks(result);
  assertionTrue("has impl checks", checks.length !== 0);
});

Test.test("inferDoD: empty hints returns dod kind=checker (no checks created)", () => {
  let hints_testCommand = null;
  let hints_buildCommand = null;
  let hints_lintCommand = null;
  let hints_declaredPath = null;
  let hints = {
    testCommand: hints_testCommand,
    buildCommand: hints_buildCommand,
    lintCommand: hints_lintCommand,
    declaredPath: hints_declaredPath
  };
  let result = VerifyDoD.inferDoD("generic task", "", hints);
  assertionEqual("kind checker", "checker", VerifyDoD.getDodKind(result));
});

Test.test("inferDoD: build-only hint produces checks for impl-category text", () => {
  let hints_testCommand = null;
  let hints_lintCommand = null;
  let hints_declaredPath = null;
  let hints = {
    testCommand: hints_testCommand,
    buildCommand: "make build",
    lintCommand: hints_lintCommand,
    declaredPath: hints_declaredPath
  };
  let result = VerifyDoD.inferDoD("build the project", "tier", hints);
  let checks = VerifyDoD.getDodChecks(result);
  assertionTrue("has checks", checks.length !== 0);
});

Test.test("inferDoD: test-only hint produces checks for test-category text", () => {
  let hints_buildCommand = null;
  let hints_lintCommand = null;
  let hints_declaredPath = null;
  let hints = {
    testCommand: "jest",
    buildCommand: hints_buildCommand,
    lintCommand: hints_lintCommand,
    declaredPath: hints_declaredPath
  };
  let result = VerifyDoD.inferDoD("write tests for auth", "tier", hints);
  let checks = VerifyDoD.getDodChecks(result);
  assertionTrue("test check exists", checks.length !== 0);
});

Test.test("inferDoD: declaredPath present triggers fileExists check", () => {
  let hints_testCommand = null;
  let hints_buildCommand = null;
  let hints_lintCommand = null;
  let hints = {
    testCommand: hints_testCommand,
    buildCommand: hints_buildCommand,
    lintCommand: hints_lintCommand,
    declaredPath: "src/utils.ts"
  };
  let result = VerifyDoD.inferDoD("write a file", "tier", hints);
  let checks = VerifyDoD.getDodChecks(result);
  assertionTrue("has checks", checks.length !== 0);
});

Test.test("inferDoD: source is always inferred", () => {
  let hints_buildCommand = null;
  let hints_lintCommand = null;
  let hints_declaredPath = null;
  let hints = {
    testCommand: "npm test",
    buildCommand: hints_buildCommand,
    lintCommand: hints_lintCommand,
    declaredPath: hints_declaredPath
  };
  let result = VerifyDoD.inferDoD("run tests", "tier", hints);
  assertionEqual("source inferred", "inferred", VerifyDoD.getDodSource(result));
});

Test.test("normalizeDoD: valid dod passes through unchanged", () => {
  let inputDod_checks = [{
      kind: "run",
      command: "npm test",
      expect: null,
      path: null,
      schema: null
    }];
  let inputDod_criteria = [];
  let inputDod = {
    kind: "deterministic",
    checks: inputDod_checks,
    criteria: inputDod_criteria,
    deliverable: "auth module",
    source: "explicit"
  };
  let result = VerifyDoD.normalizeDoD(inputDod);
  assertionEqual("kind preserved", "deterministic", VerifyDoD.getDodKind(result));
});

Test.test("normalizeDoD: empty checks array is preserved", () => {
  let inputDod_checks = [];
  let inputDod_criteria = [];
  let inputDod_deliverable = null;
  let inputDod = {
    kind: "none",
    checks: inputDod_checks,
    criteria: inputDod_criteria,
    deliverable: inputDod_deliverable,
    source: "none"
  };
  let result = VerifyDoD.normalizeDoD(inputDod);
  let checks = VerifyDoD.getDodChecks(result);
  assertionEqual("empty checks", "0", checks.length.toString());
});

Test.test("isCheckable: dod with checks returns true", () => {
  let aDod_checks = [{
      kind: "run",
      command: "npm test",
      expect: null,
      path: null,
      schema: null
    }];
  let aDod_criteria = [];
  let aDod_deliverable = null;
  let aDod = {
    kind: "deterministic",
    checks: aDod_checks,
    criteria: aDod_criteria,
    deliverable: aDod_deliverable,
    source: "explicit"
  };
  assertionTrue("isCheckable true", VerifyDoD.isCheckable(aDod));
});

Test.test("isCheckable: dod with kind=none returns false", () => {
  let emptyDod_checks = [];
  let emptyDod_criteria = [];
  let emptyDod_deliverable = null;
  let emptyDod = {
    kind: "none",
    checks: emptyDod_checks,
    criteria: emptyDod_criteria,
    deliverable: emptyDod_deliverable,
    source: "none"
  };
  assertionFalse("isCheckable false for none", VerifyDoD.isCheckable(emptyDod));
});

Test.test("isCheckable: dod with kind=checker returns true", () => {
  let checkerDod_checks = [];
  let checkerDod_criteria = [];
  let checkerDod_deliverable = null;
  let checkerDod = {
    kind: "checker",
    checks: checkerDod_checks,
    criteria: checkerDod_criteria,
    deliverable: checkerDod_deliverable,
    source: "inferred"
  };
  assertionTrue("isCheckable checker", VerifyDoD.isCheckable(checkerDod));
});

export {
  assertionEqual,
  assertionTrue,
  assertionFalse,
  assertionContains,
}
/*  Not a pure module */
