// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as VerifyDoD from "./VerifyDoD.res.mjs";
import * as VerifyDispatchCore from "./VerifyDispatchCore.res.mjs";

function assertionEqual(operator, expected, actual) {
  Test.assertion(undefined, operator, (a, b) => a === b, actual, expected);
}

function assertionTrue(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === true, actual, true);
}

function assertionFalse(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === false, actual, false);
}

function assertionContains(operator, needle, haystack) {
  let contains = haystack.indexOf(needle) >= 0;
  Test.assertion(undefined, operator, (_a, _b) => _b === true, contains, true);
}

let minimalTierConfig_activeMode = null;

let minimalTierConfig_presets = Object.fromEntries([[
    "anthropic",
    Object.fromEntries([
      [
        "fast",
        {
          model: "anthropic/claude-haiku-4-5"
        }
      ],
      [
        "medium",
        {
          model: "anthropic/claude-sonnet-4-6"
        }
      ]
    ])
  ]]);

let minimalTierConfig_rules = ["base-rule"];

let minimalTierConfig_fallback = null;

let minimalTierConfig_taskPatterns = null;

let minimalTierConfig_modes = null;

let minimalTierConfig_enforcement = null;

let minimalTierConfig = {
  activePreset: "anthropic",
  activeMode: minimalTierConfig_activeMode,
  presets: minimalTierConfig_presets,
  rules: minimalTierConfig_rules,
  defaultTier: "fast",
  fallback: minimalTierConfig_fallback,
  taskPatterns: minimalTierConfig_taskPatterns,
  modes: minimalTierConfig_modes,
  enforcement: minimalTierConfig_enforcement
};

Test.test("buildDelegationDoD: with acceptance string matches parseDoDFromAnnotation", () => {
  let acceptanceBlock = "[acceptance]\ncheck: testsPass\n[/acceptance]";
  let args = {
    prompt: "implement auth",
    description: "add login",
    acceptance: acceptanceBlock
  };
  let hints_testCommand = null;
  let hints_buildCommand = null;
  let hints_lintCommand = null;
  let hints_declaredPath = null;
  let hints = {
    testCommand: hints_testCommand,
    buildCommand: hints_buildCommand,
    lintCommand: hints_lintCommand,
    declaredPath: hints_declaredPath
  };
  let result = VerifyDispatchCore.buildDelegationDoD(args, hints);
  let fromAnnotation = VerifyDoD.parseDoDFromAnnotation(acceptanceBlock);
  if (fromAnnotation == null) {
    return assertionTrue("should not be None", false);
  }
  let rKind = VerifyDoD.getDodKind(result);
  let eKind = VerifyDoD.getDodKind(fromAnnotation);
  assertionEqual("same kind", eKind, rKind);
});

Test.test("buildDelegationDoD: null acceptance falls back to inferDoD", () => {
  let args_prompt = null;
  let args_description = null;
  let args_acceptance = null;
  let args = {
    prompt: args_prompt,
    description: args_description,
    acceptance: args_acceptance
  };
  let hints_buildCommand = null;
  let hints_lintCommand = null;
  let hints_declaredPath = null;
  let hints = {
    testCommand: "npm test",
    buildCommand: hints_buildCommand,
    lintCommand: hints_lintCommand,
    declaredPath: hints_declaredPath
  };
  let result = VerifyDispatchCore.buildDelegationDoD(args, hints);
  let checks = VerifyDoD.getDodChecks(result);
  assertionTrue("has inferred checks", checks.length !== 0);
});

Test.test("buildDelegationDoD: empty acceptance string falls back to inferDoD", () => {
  let args_prompt = null;
  let args_description = null;
  let args = {
    prompt: args_prompt,
    description: args_description,
    acceptance: ""
  };
  let hints_buildCommand = null;
  let hints_lintCommand = null;
  let hints_declaredPath = null;
  let hints = {
    testCommand: "jest",
    buildCommand: hints_buildCommand,
    lintCommand: hints_lintCommand,
    declaredPath: hints_declaredPath
  };
  let result = VerifyDispatchCore.buildDelegationDoD(args, hints);
  let checks = VerifyDoD.getDodChecks(result);
  assertionTrue("empty acceptance→infer", checks.length !== 0);
});

Test.test("buildDelegationDoD: null acceptance falls back to inferDoD using prompt", () => {
  let args_acceptance = null;
  let args = {
    prompt: "build the feature",
    description: "description",
    acceptance: args_acceptance
  };
  let hints_testCommand = null;
  let hints_lintCommand = null;
  let hints_declaredPath = null;
  let hints = {
    testCommand: hints_testCommand,
    buildCommand: "make build",
    lintCommand: hints_lintCommand,
    declaredPath: hints_declaredPath
  };
  let result = VerifyDispatchCore.buildDelegationDoD(args, hints);
  let kind = VerifyDoD.getDodKind(result);
  assertionEqual("kind checker", "checker", kind);
});

Test.test("buildDelegationDoD: source is explicit when acceptance provided", () => {
  let args_prompt = null;
  let args_description = null;
  let args = {
    prompt: args_prompt,
    description: args_description,
    acceptance: "[acceptance]\ncheck: run \"echo hi\"\n[/acceptance]"
  };
  let hints_testCommand = null;
  let hints_buildCommand = null;
  let hints_lintCommand = null;
  let hints_declaredPath = null;
  let hints = {
    testCommand: hints_testCommand,
    buildCommand: hints_buildCommand,
    lintCommand: hints_lintCommand,
    declaredPath: hints_declaredPath
  };
  let result = VerifyDispatchCore.buildDelegationDoD(args, hints);
  let source = VerifyDoD.getDodSource(result);
  assertionEqual("source explicit", "explicit", source);
});

Test.test("shouldVerifyTask: no acceptance string returns false", () => {
  let result = VerifyDispatchCore.shouldVerifyTask("implement feature x", "add the login flow", null);
  assertionFalse("no acceptance → no verify", result);
});

Test.test("shouldVerifyTask: empty acceptance block returns false", () => {
  let result = VerifyDispatchCore.shouldVerifyTask("implement feature", "add feature", "[acceptance]\n[/acceptance]");
  assertionFalse("empty block → no verify", result);
});

Test.test("shouldVerifyTask: whitespace-only acceptance returns false", () => {
  let result = VerifyDispatchCore.shouldVerifyTask("do something", "desc", "   [acceptance]   \n  \n[/acceptance]");
  assertionFalse("whitespace-only → no verify", result);
});

Test.test("shouldVerifyTask: acceptance with check lines returns true", () => {
  let result = VerifyDispatchCore.shouldVerifyTask("implement feature", "add feature", "[acceptance]\ncheck: run \"npm test\"\n[/acceptance]");
  assertionTrue("check present → verify", result);
});

Test.test("shouldVerifyTask: acceptance with criteria only returns false", () => {
  let result = VerifyDispatchCore.shouldVerifyTask("task", "desc", "[acceptance]\ncriteria: must be good\n[/acceptance]");
  assertionFalse("criteria only → no verify", result);
});

Test.test("shouldVerifyTask: acceptance with fileExists check returns true", () => {
  let result = VerifyDispatchCore.shouldVerifyTask("implement", "desc", "[acceptance]\ncheck: fileExists \"src/auth.ts\"\n[/acceptance]");
  assertionTrue("fileExists → verify", result);
});

Test.test("tierModel: empty model name returns null", () => {
  let result = VerifyDispatchCore.tierModel(minimalTierConfig, "");
  if (result == null) {
    return assertionTrue("null for empty tier name", true);
  } else {
    return assertionTrue("should not be None", false);
  }
});

Test.test("tierModel: known tier fast returns tierModelResult", () => {
  let result = VerifyDispatchCore.tierModel(minimalTierConfig, "fast");
  if (result == null) {
    return assertionTrue("should not be None", false);
  } else {
    return assertionContains("fast tier has model", "claude", result.modelID);
  }
});

Test.test("tierModel: medium tier returns correct model", () => {
  let result = VerifyDispatchCore.tierModel(minimalTierConfig, "medium");
  if (result == null) {
    return assertionTrue("should not be None", false);
  } else {
    return assertionContains("medium tier model", "claude", result.modelID);
  }
});

Test.test("tierModel: unknown tier returns null", () => {
  let result = VerifyDispatchCore.tierModel(minimalTierConfig, "nonexistent-tier");
  if (result == null) {
    return assertionTrue("null for unknown tier", true);
  } else {
    return assertionTrue("should not be None", false);
  }
});

Test.test("buildForcingNote: empty producers returns note with default body", () => {
  let result = VerifyDispatchCore.buildForcingNote([], null);
  assertionContains("has NOT ACCEPTED", "NOT ACCEPTED", result);
});

Test.test("buildForcingNote: producers with no hint returns string", () => {
  let result = VerifyDispatchCore.buildForcingNote([
    "tier-a",
    "tier-b"
  ], null);
  assertionContains("contains producer", "tier-a", result);
});

Test.test("buildForcingNote: with escalationHint includes producer and next tier", () => {
  let hint = {
    producerTier: "fast",
    nextTier: "medium"
  };
  let result = VerifyDispatchCore.buildForcingNote(["fast"], hint);
  assertionContains("contains producerTier", "fast", result);
});

Test.test("buildForcingNote: hint with null fields handles gracefully", () => {
  let hint_producerTier = null;
  let hint_nextTier = null;
  let hint = {
    producerTier: hint_producerTier,
    nextTier: hint_nextTier
  };
  let result = VerifyDispatchCore.buildForcingNote(["fast"], hint);
  assertionContains("producer in note", "fast", result);
});

Test.test("buildAcceptedSuffix: non-empty input returns suffixed string", () => {
  let result = VerifyDispatchCore.buildAcceptedSuffix("task description");
  assertionContains("input preserved", "task description", result);
});

Test.test("buildAcceptedSuffix: empty input returns formatted suffix", () => {
  let result = VerifyDispatchCore.buildAcceptedSuffix("");
  assertionContains("accepted marker", "router ✓ accepted", result);
});

Test.test("buildAcceptedSuffix: long description is preserved", () => {
  let input = "this is a very long task description that spans multiple ideas";
  let result = VerifyDispatchCore.buildAcceptedSuffix(input);
  assertionContains("long desc preserved", input, result);
});

Test.test("parseTaskResult: full JSON decodes all fields", () => {
  let json = {
    "output": "all done",
    "metadata": {
      "sessionID": "sess-123",
      "parentSessionID": "parent-456"
    }
  };
  let result = VerifyDispatchCore.parseTaskResult(json);
  assertionEqual("finalReturnText", "all done", result.finalReturnText);
});

Test.test("parseTaskResult: missing keys return empty/null defaults", () => {
  let json = { "output": "" };
  let result = VerifyDispatchCore.parseTaskResult(json);
  assertionEqual("empty output → empty", "", result.finalReturnText);
});

Test.test("parseTaskResult: partial JSON fills defaults for missing", () => {
  let json = { "output": "partial result" };
  let result = VerifyDispatchCore.parseTaskResult(json);
  assertionEqual("partial result", "partial result", result.finalReturnText);
});

Test.test("extractChangedFile: valid path and status returns Some(changedFile)", () => {
  let json = { "path": "src/auth.ts", "status": "modified" };
  let result = VerifyDispatchCore.extractChangedFile("src/auth.ts", json);
  if (result == null) {
    return assertionTrue("should not be None", false);
  } else {
    return assertionContains("path preserved", "auth.ts", result.path);
  }
});

Test.test("extractChangedFile: missing path returns null", () => {
  let json = { "status": "added" };
  let result = VerifyDispatchCore.extractChangedFile("any", json);
  if (result == null) {
    return assertionTrue("null on missing path", true);
  } else {
    return assertionTrue("should not be None", false);
  }
});

Test.test("extractChangedFile: different file path returns null", () => {
  let json = { "path": "src/other.ts", "status": "modified" };
  let result = VerifyDispatchCore.extractChangedFile("src/auth.ts", json);
  if (result == null) {
    return assertionTrue("null for mismatched path", true);
  } else {
    return assertionTrue("should not be None", false);
  }
});

Test.test("createChangedFileStore: returns a store value", () => {
  VerifyDispatchCore.createChangedFileStore();
  assertionTrue("store created", true);
});

export {
  assertionEqual,
  assertionTrue,
  assertionFalse,
  assertionContains,
  minimalTierConfig,
}
/* minimalTierConfig Not a pure module */
