// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as VerifyDoD from "./VerifyDoD.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

let writeTools = [
  "write",
  "edit"
];

function isWriteTool(tool) {
  let found = false;
  for (let i = 0, i_finish = writeTools.length; i < i_finish; ++i) {
    let w = writeTools[i];
    if (w !== undefined && w === tool) {
      found = true;
    }
  }
  return found;
}

function getStringField(obj, key) {
  let v = Js_dict.get(obj, key);
  if (v === undefined) {
    return "";
  }
  let s = Js_json.classify(v);
  if (typeof s !== "object" || s.TAG !== "JSONString") {
    return "";
  } else {
    return s._0;
  }
}

function extractChangedFile(tool, args) {
  if (!isWriteTool(tool)) {
    return null;
  }
  let o = Js_json.classify(args);
  let obj;
  obj = typeof o !== "object" ? ({}) : (
      o.TAG === "JSONObject" ? o._0 : ({})
    );
  let path = getStringField(obj, "filePath");
  let pathB = path === "" ? getStringField(obj, "path") : path;
  let pathC = pathB === "" ? getStringField(obj, "file") : pathB;
  if (pathC === "") {
    return null;
  }
  let status = tool === "write" ? "written" : "modified";
  return {
    path: pathC,
    status: status
  };
}

function recFindPrev(m, path) {
  let v = Js_dict.get(m, path);
  if (v !== undefined) {
    return v;
  } else {
    return "";
  }
}

function createChangedFileStore() {
  let bySession = {};
  let record = (sessionID, tool, args) => {
    let cf = extractChangedFile(tool, args);
    if (cf == null) {
      return;
    }
    let existing = Js_dict.get(bySession, sessionID);
    let m;
    if (existing !== undefined) {
      m = existing;
    } else {
      let newMap = {};
      bySession[sessionID] = newMap;
      m = newMap;
    }
    let prev = recFindPrev(m, cf.path);
    let newStatus = prev === "written" ? "written" : cf.status;
    m[cf.path] = newStatus;
  };
  let get = sessionID => {
    let m = Js_dict.get(bySession, sessionID);
    if (m !== undefined) {
      let entries = Js_dict.entries(m);
      let _i = 0;
      let _acc = [];
      while (true) {
        let acc = _acc;
        let i = _i;
        if (i >= entries.length) {
          return acc;
        }
        let match = entries[i];
        if (match !== undefined) {
          _acc = Belt_Array.concatMany([
            acc,
            [{
                path: match[0],
                status: match[1]
              }]
          ]);
          _i = i + 1 | 0;
          continue;
        }
        _i = i + 1 | 0;
        continue;
      };
    } else {
      return [];
    }
  };
  let clear = sessionID => ((delete bySession[sessionID]));
  return {
    record: record,
    get: get,
    clear: clear
  };
}

function getMetadataField(metadata, key1, key2) {
  let _keys = {
    hd: key1,
    tl: {
      hd: key2,
      tl: /* [] */0
    }
  };
  while (true) {
    let keys = _keys;
    if (keys === 0) {
      return null;
    }
    let rest = keys.tl;
    let v = Js_dict.get(metadata, keys.hd);
    if (v !== undefined) {
      let s = Js_json.classify(v);
      if (typeof s !== "object") {
        _keys = rest;
        continue;
      }
      if (s.TAG === "JSONString") {
        return s._0;
      }
      _keys = rest;
      continue;
    } else {
      _keys = rest;
      continue;
    }
  };
}

function extractTaskResultContent(s) {
  let openTag = "<task_result>";
  let openIdx = openTag.indexOf(s);
  let closeIdx = openIdx !== -1 ? "</task_result>".indexOf(s) : -1;
  if (openIdx === -1) {
    return s;
  }
  if (closeIdx === -1) {
    return s;
  }
  let start = openIdx + openTag.length | 0;
  if (start > closeIdx) {
    return s;
  } else {
    return s.substring(start, closeIdx).trim();
  }
}

function parseTaskResult(output) {
  let o = Js_json.classify(output);
  let obj;
  obj = typeof o !== "object" ? ({}) : (
      o.TAG === "JSONObject" ? o._0 : ({})
    );
  let v = Js_dict.get(obj, "output");
  let outputStr;
  if (v !== undefined) {
    let s = Js_json.classify(v);
    outputStr = typeof s !== "object" || s.TAG !== "JSONString" ? "" : s._0;
  } else {
    outputStr = "";
  }
  let finalReturnText = extractTaskResultContent(outputStr).trim();
  let v$1 = Js_dict.get(obj, "metadata");
  let metadata;
  if (v$1 !== undefined) {
    let o$1 = Js_json.classify(v$1);
    metadata = typeof o$1 !== "object" ? ({}) : (
        o$1.TAG === "JSONObject" ? o$1._0 : ({})
      );
  } else {
    metadata = {};
  }
  let childSessionID = getMetadataField(metadata, "sessionId", "sessionID");
  let parentSessionID = getMetadataField(metadata, "parentSessionId", "parentSessionID");
  return {
    finalReturnText: finalReturnText,
    childSessionID: childSessionID,
    parentSessionID: parentSessionID
  };
}

function buildDelegationDoD(args, hints) {
  let v = args.acceptance;
  let blockSource;
  if (v == null) {
    let v$1 = args.prompt;
    if (v$1 == null) {
      let v$2 = args.description;
      blockSource = (v$2 == null) ? "" : v$2;
    } else {
      blockSource = v$1;
    }
  } else {
    blockSource = v;
  }
  let explicit = VerifyDoD.parseDoDFromDispatch(blockSource);
  if (!(explicit == null)) {
    return explicit;
  }
  let v$3 = args.prompt;
  let dispatch;
  if (v$3 == null) {
    let v$4 = args.description;
    dispatch = (v$4 == null) ? "" : v$4;
  } else {
    dispatch = v$3;
  }
  return VerifyDoD.inferDoD(dispatch, "", hints);
}

function getActiveTiers(cfg) {
  let tiers = Js_dict.get(cfg.presets, cfg.activePreset);
  if (tiers !== undefined) {
    return tiers;
  } else {
    return {};
  }
}

function tierModel(cfg, tierName) {
  let tiers = getActiveTiers(cfg);
  let t = Js_dict.get(tiers, tierName);
  if (t === undefined) {
    return null;
  }
  let model = t.model;
  if (model === "") {
    return null;
  }
  let slashIdx = model.indexOf("/");
  if (slashIdx <= 0 || slashIdx >= (model.length - 1 | 0)) {
    return null;
  }
  let providerID = model.slice(0, slashIdx);
  let modelID = model.slice(slashIdx + 1 | 0, model.length);
  return {
    providerID: providerID,
    modelID: modelID
  };
}

function shouldVerifyTask(tool, mode, $$require) {
  if (tool !== "task") {
    return false;
  }
  if (mode === "off") {
    return false;
  }
  let requireStr = ($$require == null) ? "whenDoDPresent" : $$require;
  return requireStr !== "never";
}

function joinReasons(reasons) {
  let _i = 0;
  let _acc = "";
  while (true) {
    let acc = _acc;
    let i = _i;
    if (i >= reasons.length) {
      return acc;
    }
    let reason = reasons[i];
    if (reason !== undefined) {
      let prefix = acc === "" ? "- " : "\n- ";
      _acc = acc + prefix + reason;
      _i = i + 1 | 0;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function buildForcingNote(reasons, escalation) {
  let body = reasons.length !== 0 ? joinReasons(reasons) : "- (no reasons provided)";
  let next;
  if (escalation == null) {
    next = "NEXT: address the above and re-run the delegation; do not treat the prior result as complete.";
  } else {
    let nextTier = escalation.nextTier;
    if (nextTier == null) {
      next = "NEXT: address the above and re-run the delegation; do not treat the prior result as complete.";
    } else {
      let pt = escalation.producerTier;
      let producer = (pt == null) ? "" : " (escalated from " + pt + ")";
      next = "NEXT: address the above, then re-run via `Task(subagent_type=\"" + nextTier + "\")" + producer + "; do not treat the prior result as complete.";
    }
  }
  return "[router ⚠ NOT ACCEPTED] The delegated result was not accepted by independent verification:\n" + body + "\n" + next;
}

function buildAcceptedSuffix(method) {
  return "\n\n[router ✓ accepted: " + method + "]";
}

export {
  extractChangedFile,
  createChangedFileStore,
  parseTaskResult,
  buildDelegationDoD,
  tierModel,
  shouldVerifyTask,
  buildForcingNote,
  buildAcceptedSuffix,
}
/* VerifyDoD Not a pure module */
