// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Js_option from "@rescript/runtime/lib/es6/Js_option.js";

function deepMerge(base, override) {
  let baseObj = Js_json.decodeObject(base);
  let overrideObj = Js_json.decodeObject(override);
  let baseIsObj = baseObj !== undefined;
  let overrideIsObj = overrideObj !== undefined;
  if (!baseIsObj) {
    return override;
  }
  if (!overrideIsObj) {
    if (typeof override === "undefined") {
      return base;
    } else {
      return override;
    }
  }
  let b = Js_option.getExn(baseObj);
  let o = Js_option.getExn(overrideObj);
  let merged = {};
  let baseKeys = Object.keys(b);
  for (let i = 0, i_finish = baseKeys.length; i < i_finish; ++i) {
    let key = baseKeys[i];
    if (key !== undefined) {
      let v = Js_dict.get(b, key);
      if (v !== undefined) {
        merged[key] = v;
      }
    }
  }
  let overrideKeys = Object.keys(o);
  for (let i$1 = 0, i_finish$1 = overrideKeys.length; i$1 < i_finish$1; ++i$1) {
    let key$1 = overrideKeys[i$1];
    if (key$1 !== undefined) {
      let ov = Js_dict.get(o, key$1);
      if (ov !== undefined) {
        let bv = Js_dict.get(b, key$1);
        if (bv !== undefined) {
          merged[key$1] = deepMerge(bv, ov);
        } else {
          merged[key$1] = ov;
        }
      }
    }
  }
  return merged;
}

export {
  deepMerge,
}
/* No side effect */
