// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as ConfigMerge from "./ConfigMerge.res.mjs";

function pass() {
  Test.assertion(undefined, undefined, (param, param$1) => true, true, true);
}

function deepEqual(message, a, b) {
  Test.assertion(message, "deepEqual", (x, y) => JSON.stringify(x) === JSON.stringify(y), a, b);
}

function stringContains(haystack, needle) {
  return haystack.indexOf(needle) >= 0;
}

function parse(s) {
  return JSON.parse(s);
}

Test.test("deepMerge: two empty objects produce empty object", () => {
  let base = {};
  let override = {};
  deepEqual(undefined, ConfigMerge.deepMerge(base, override), {});
});

Test.test("deepMerge: merging empty with self returns self", () => {
  let base = {};
  deepEqual(undefined, ConfigMerge.deepMerge(base, base), base);
});

Test.test("deepMerge: undefined base returns override", () => {
  let override = {};
  deepEqual(undefined, ConfigMerge.deepMerge(undefined, override), override);
});

Test.test("deepMerge: undefined override returns base", () => {
  let base = {};
  deepEqual(undefined, ConfigMerge.deepMerge(base, undefined), base);
});

Test.test("deepMerge: nested objects merge deeply", () => {
  let base = JSON.parse(`{
    "presets": {
      "multi-provider": {
        "fast": {"model": "a/fast"}
      }
    },
    "rules": []
  }`);
  let override = JSON.parse(`{
    "presets": {
      "multi-provider": {
        "fast": {"description": "updated"}
      }
    }
  }`);
  let result = ConfigMerge.deepMerge(base, override);
  let resultStr = JSON.stringify(result);
  Test.assertion(undefined, "hasModel", (_a, _b) => stringContains(resultStr, "\"model\"") === true, true, true);
});

Test.test("deepMerge: override adds new keys", () => {
  let base = JSON.parse(`{"a": 1}`);
  let override = JSON.parse(`{"b": 2}`);
  let result = ConfigMerge.deepMerge(base, override);
  let resultStr = JSON.stringify(result);
  Test.assertion(undefined, "hasBoth", (_a, _b) => {
    if (stringContains(resultStr, "\"a\"") === true) {
      return stringContains(resultStr, "\"b\"") === true;
    } else {
      return false;
    }
  }, true, true);
});

Test.test("deepMerge: deep nested merge preserves non-overridden keys", () => {
  let base = JSON.parse(`{
    "enforcement": {
      "mode": "off",
      "guard": {"budget": 5000}
    }
  }`);
  let override = JSON.parse(`{
    "enforcement": {
      "guard": {"budget": 10000}
    }
  }`);
  let result = ConfigMerge.deepMerge(base, override);
  let resultStr = JSON.stringify(result);
  Test.assertion(undefined, "modePreserved", (_a, _b) => stringContains(resultStr, "\"off\"") === true, true, true);
});

Test.test("deepMerge: array override replaces base (not concat)", () => {
  let base = JSON.parse(`{"rules": ["a", "b"]}`);
  let override = JSON.parse(`{"rules": ["c"]}`);
  let result = ConfigMerge.deepMerge(base, override);
  let resultStr = JSON.stringify(result);
  Test.assertion(undefined, "arrayReplaced", (_a, _b) => {
    if (stringContains(resultStr, "\"c\"") === true) {
      return stringContains(resultStr, "\"a\"") === false;
    } else {
      return false;
    }
  }, true, true);
});

Test.test("deepMerge: nested array also replaces", () => {
  let base = JSON.parse(`{
    "presets": {
      "p": {
        "fast": {"whenToUse": ["old1", "old2"]}
      }
    }
  }`);
  let override = JSON.parse(`{
    "presets": {
      "p": {
        "fast": {"whenToUse": ["new"]}
      }
    }
  }`);
  let result = ConfigMerge.deepMerge(base, override);
  let resultStr = JSON.stringify(result);
  Test.assertion(undefined, "nestedArrayReplaced", (_a, _b) => {
    if (stringContains(resultStr, "\"new\"") === true) {
      return stringContains(resultStr, "\"old1\"") === false;
    } else {
      return false;
    }
  }, true, true);
});

Test.test("deepMerge: string override replaces string base", () => {
  let base = "hello";
  let override = "world";
  deepEqual(undefined, ConfigMerge.deepMerge(base, override), "world");
});

Test.test("deepMerge: number override replaces number base", () => {
  let base = 10;
  let override = 20;
  deepEqual(undefined, ConfigMerge.deepMerge(base, override), 20);
});

Test.test("deepMerge: boolean override replaces boolean base", () => {
  let base = false;
  let override = true;
  deepEqual(undefined, ConfigMerge.deepMerge(base, override), true);
});

Test.test("deepMerge: object override replaces scalar base", () => {
  let base = 42;
  let override = JSON.parse(`{"key": "value"}`);
  deepEqual(undefined, ConfigMerge.deepMerge(base, override), override);
});

Test.test("deepMerge: scalar override replaces object base", () => {
  let base = JSON.parse(`{"key": "value"}`);
  let override = 42;
  deepEqual(undefined, ConfigMerge.deepMerge(base, override), 42);
});

Test.test("deepMerge: null override replaces non-null base", () => {
  let base = "hello";
  let override = null;
  deepEqual(undefined, ConfigMerge.deepMerge(base, override), null);
});

Test.test("deepMerge: null base is preserved (null !== undefined)", () => {
  let override = "override";
  deepEqual(undefined, ConfigMerge.deepMerge(null, override), override);
});

Test.test("deepMerge: null nested value can be overridden", () => {
  let base = JSON.parse(`{"capability": null}`);
  let override = JSON.parse(`{"capability": "binary"}`);
  let result = ConfigMerge.deepMerge(base, override);
  let resultStr = JSON.stringify(result);
  Test.assertion(undefined, "nullOverridden", (_a, _b) => stringContains(resultStr, "\"binary\"") === true, true, true);
});

Test.test("deepMerge: null in nested object merges correctly", () => {
  let base = JSON.parse(`{
    "capability": {
      "kind": null,
      "field": "variant"
    }
  }`);
  let override = JSON.parse(`{
    "capability": {
      "kind": "binary"
    }
  }`);
  let result = ConfigMerge.deepMerge(base, override);
  let resultStr = JSON.stringify(result);
  Test.assertion(undefined, "fieldPreserved", (_a, _b) => {
    if (stringContains(resultStr, "\"field\"") === true) {
      return stringContains(resultStr, "\"binary\"") === true;
    } else {
      return false;
    }
  }, true, true);
});

Test.test("deepMerge: three-way chained merge (bundled → global → local)", () => {
  let bundled = JSON.parse(`{
    "activePreset": "multi-provider",
    "presets": {"p": {"fast": {"model": "a/fast"}}},
    "rules": [],
    "defaultTier": "fast"
  }`);
  let global = JSON.parse(`{
    "activePreset": "custom"
  }`);
  let local = JSON.parse(`{
    "rules": ["local-rule"]
  }`);
  let step1 = ConfigMerge.deepMerge(bundled, global);
  let step2 = ConfigMerge.deepMerge(step1, local);
  let resultStr = JSON.stringify(step2);
  Test.assertion(undefined, "threeWay", (_a, _b) => {
    if (stringContains(resultStr, "\"custom\"") === true && stringContains(resultStr, "\"local-rule\"") === true) {
      return stringContains(resultStr, "\"a/fast\"") === true;
    } else {
      return false;
    }
  }, true, true);
});

export {
  pass,
  deepEqual,
  stringContains,
  parse,
}
/*  Not a pure module */
