// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function deepMerge(base, override) {
  let baseObj = Stdlib_JSON.Decode.object(base);
  let overrideObj = Stdlib_JSON.Decode.object(override);
  let baseIsObj = baseObj !== undefined;
  let overrideIsObj = overrideObj !== undefined;
  if (!baseIsObj) {
    return override;
  }
  if (!overrideIsObj) {
    if (overrideObj === undefined) {
      return base;
    } else {
      return override;
    }
  }
  let b = Stdlib_Option.getOrThrow(baseObj, undefined);
  let o = Stdlib_Option.getOrThrow(overrideObj, undefined);
  let merged = {};
  let baseKeys = Object.keys(b);
  for (let i = 0, i_finish = baseKeys.length; i < i_finish; ++i) {
    let key = baseKeys[i];
    if (key !== undefined) {
      let v = b[key];
      if (v !== undefined) {
        merged[key] = v;
      }
    }
  }
  let overrideKeys = Object.keys(o);
  for (let i$1 = 0, i_finish$1 = overrideKeys.length; i$1 < i_finish$1; ++i$1) {
    let key$1 = overrideKeys[i$1];
    if (key$1 !== undefined) {
      let ov = o[key$1];
      if (ov !== undefined) {
        let bv = b[key$1];
        if (bv !== undefined) {
          merged[key$1] = deepMerge(bv, ov);
        } else {
          merged[key$1] = ov;
        }
      }
    }
  }
  return merged;
}

export {
  deepMerge,
}
/* No side effect */
