// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";

function resolveTierModelGuard(cfg, tierName) {
  let tiers = Js_dict.get(cfg.presets, cfg.activePreset);
  if (tiers === undefined) {
    return {
      ok: false,
      reason: "invalid model or provider configuration"
    };
  }
  let tier = Js_dict.get(tiers, tierName);
  if (tier === undefined) {
    return {
      ok: false,
      reason: "invalid model or provider configuration"
    };
  }
  let modelStr = tier.model;
  let slashPos = modelStr.indexOf("/");
  if (slashPos <= 0 || slashPos >= (modelStr.length - 1 | 0)) {
    return {
      ok: false,
      reason: "invalid model or provider configuration"
    };
  } else {
    return {
      ok: true,
      model: {
        providerID: modelStr.slice(0, slashPos),
        modelID: modelStr.slice(slashPos + 1 | 0, modelStr.length)
      }
    };
  }
}

export {
  resolveTierModelGuard,
}
/* No side effect */
