// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as TierModelGuard from "./TierModelGuard.res.mjs";

function resultEqual(res, expected) {
  Test.assertion(undefined, "resultEqual", (a, b) => {
    if (a.ok !== b.ok) {
      return false;
    }
    let match = a.ok;
    let match$1 = b.ok;
    if (!match) {
      if (match$1) {
        return false;
      } else {
        return a.reason === b.reason;
      }
    }
    if (!match$1) {
      return false;
    }
    let match$2 = a.model;
    let match$3 = b.model;
    if (match$2 !== undefined && match$3 !== undefined && match$2.providerID === match$3.providerID) {
      return match$2.modelID === match$3.modelID;
    } else {
      return false;
    }
  }, res, expected);
}

function makeCfg(tiers) {
  let tiersDict = {};
  tiers.forEach(param => {
    let tierCfg_model = param[1];
    let tierCfg_whenToUse = [];
    let tierCfg = {
      model: tierCfg_model,
      variant: undefined,
      costRatio: undefined,
      description: "",
      whenToUse: tierCfg_whenToUse,
      thinking: undefined,
      reasoning: undefined,
      capability: undefined
    };
    tiersDict[param[0]] = tierCfg;
  });
  let presets = {};
  presets["p"] = tiersDict;
  return {
    activePreset: "p",
    activeMode: undefined,
    tierCaps: undefined,
    tierPrompts: undefined,
    presets: presets,
    rules: [],
    defaultTier: "fast",
    fallback: undefined,
    taskPatterns: undefined,
    modes: undefined,
    enforcement: undefined,
    reasoningPolicy: undefined
  };
}

Test.test("passes through a known tier with a well-formed model string", () => {
  let cfg = makeCfg([[
      "fast",
      "anthropic/claude-haiku-4-5"
    ]]);
  let result = TierModelGuard.resolveTierModelGuard(cfg, "fast");
  resultEqual(result, {
    ok: true,
    model: {
      providerID: "anthropic",
      modelID: "claude-haiku-4-5"
    }
  });
});

Test.test("fails closed on an unknown tier with the canonical reason", () => {
  let cfg = makeCfg([[
      "fast",
      "anthropic/claude-haiku-4-5"
    ]]);
  let result = TierModelGuard.resolveTierModelGuard(cfg, "nope");
  resultEqual(result, {
    ok: false,
    reason: "invalid model or provider configuration"
  });
});

Test.test("fails closed when the tier exists but the model string has no slash", () => {
  let cfg = makeCfg([[
      "weird",
      "noslash"
    ]]);
  let result = TierModelGuard.resolveTierModelGuard(cfg, "weird");
  resultEqual(result, {
    ok: false,
    reason: "invalid model or provider configuration"
  });
});

Test.test("fails closed when the model string has a trailing slash", () => {
  let cfg = makeCfg([[
      "empty",
      "anthropic/"
    ]]);
  let result = TierModelGuard.resolveTierModelGuard(cfg, "empty");
  resultEqual(result, {
    ok: false,
    reason: "invalid model or provider configuration"
  });
});

Test.test("returns the same canonical reason regardless of underlying failure mode", () => {
  let cfg = makeCfg([
    [
      "weird",
      "noslash"
    ],
    [
      "empty",
      "anthropic/"
    ]
  ]);
  let r1 = TierModelGuard.resolveTierModelGuard(cfg, "nope");
  let r2 = TierModelGuard.resolveTierModelGuard(cfg, "weird");
  let r3 = TierModelGuard.resolveTierModelGuard(cfg, "empty");
  Test.assertion(undefined, "r1Fail", (a, b) => a === b, r1.ok, false);
  Test.assertion(undefined, "r1Reason", (a, b) => a === b, r1.reason, "invalid model or provider configuration");
  Test.assertion(undefined, "r2Fail", (a, b) => a === b, r2.ok, false);
  Test.assertion(undefined, "r2Reason", (a, b) => a === b, r2.reason, "invalid model or provider configuration");
  Test.assertion(undefined, "r3Fail", (a, b) => a === b, r3.ok, false);
  Test.assertion(undefined, "r3Reason", (a, b) => a === b, r3.reason, "invalid model or provider configuration");
});

Test.test("is a thin wrapper — pass-through shape matches tierModel output exactly", () => {
  let cfg = makeCfg([[
      "fast",
      "anthropic/claude-haiku-4-5"
    ]]);
  let result = TierModelGuard.resolveTierModelGuard(cfg, "fast");
  let match = result.model;
  if (match !== undefined) {
    Test.assertion(undefined, "providerID", (a, b) => a === b, match.providerID, "anthropic");
    return Test.assertion(undefined, "modelID", (a, b) => a === b, match.modelID, "claude-haiku-4-5");
  } else {
    return Stdlib_Exn.raiseError("Expected Ok but got None");
  }
});

export {
  resultEqual,
  makeCfg,
}
/*  Not a pure module */
