// Generated by ReScript, PLEASE EDIT WITH CARE


function resolveTierModelGuard(cfg, tierName) {
  let tiers = cfg.presets[cfg.activePreset];
  if (tiers === undefined) {
    return {
      ok: false,
      reason: "invalid model or provider configuration"
    };
  }
  let tier = tiers[tierName];
  if (tier === undefined) {
    return {
      ok: false,
      reason: "invalid model or provider configuration"
    };
  }
  let modelStr = tier.model;
  let slashPos = modelStr.indexOf("/");
  if (slashPos <= 0 || slashPos >= (modelStr.length - 1 | 0)) {
    return {
      ok: false,
      reason: "invalid model or provider configuration"
    };
  } else {
    return {
      ok: true,
      model: {
        providerID: modelStr.slice(0, slashPos),
        modelID: modelStr.slice(slashPos + 1 | 0, modelStr.length)
      }
    };
  }
}

export {
  resolveTierModelGuard,
}
/* No side effect */
