// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as Ladder from "./Ladder.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function assertionEqual(operator, expected, actual) {
  Test.assertion(undefined, operator, (a, b) => a === b, actual, expected);
}

function assertionTrue(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === true, actual, true);
}

function assertionFalse(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === false, actual, false);
}

function stringContains(haystack, needle) {
  return haystack.indexOf(needle) >= 0;
}

function makePolicy(ladderOpt, floorTierOpt, maxAttemptsPerTierOpt, maxTotalAttemptsOpt, costMultipleOpt, param) {
  let ladder = ladderOpt !== undefined ? ladderOpt : [
      "fast",
      "medium",
      "heavy"
    ];
  let floorTier = floorTierOpt !== undefined ? Primitive_option.valFromOption(floorTierOpt) : null;
  let maxAttemptsPerTier = maxAttemptsPerTierOpt !== undefined ? maxAttemptsPerTierOpt : 1;
  let maxTotalAttempts = maxTotalAttemptsOpt !== undefined ? maxTotalAttemptsOpt : 4;
  let costMultiple = costMultipleOpt !== undefined ? Primitive_option.valFromOption(costMultipleOpt) : 4;
  return {
    ladder: ladder,
    floorTier: floorTier,
    maxAttemptsPerTier: maxAttemptsPerTier,
    maxTotalAttempts: maxTotalAttempts,
    costMultiple: costMultiple
  };
}

function makeState(currentTierOpt, attemptsThisTierOpt, totalAttemptsOpt, escalationsOpt, firstAttemptCostOpt, cumulativeCostOpt, param) {
  let currentTier = currentTierOpt !== undefined ? currentTierOpt : "fast";
  let attemptsThisTier = attemptsThisTierOpt !== undefined ? attemptsThisTierOpt : 0;
  let totalAttempts = totalAttemptsOpt !== undefined ? totalAttemptsOpt : 0;
  let escalations = escalationsOpt !== undefined ? escalationsOpt : 0;
  let firstAttemptCost = firstAttemptCostOpt !== undefined ? Primitive_option.valFromOption(firstAttemptCostOpt) : null;
  let cumulativeCost = cumulativeCostOpt !== undefined ? cumulativeCostOpt : 0;
  return {
    currentTier: currentTier,
    attemptsThisTier: attemptsThisTier,
    totalAttempts: totalAttempts,
    escalations: escalations,
    firstAttemptCost: firstAttemptCost,
    cumulativeCost: cumulativeCost
  };
}

Test.test("tierRank: known tier returns correct index", () => {
  let ladder = [
    "fast",
    "medium",
    "heavy"
  ];
  assertionEqual("fast", Ladder.tierRank("fast", ladder), 0);
  assertionEqual("medium", Ladder.tierRank("medium", ladder), 1);
  assertionEqual("heavy", Ladder.tierRank("heavy", ladder), 2);
});

Test.test("tierRank: unknown tier returns -1", () => {
  let ladder = [
    "fast",
    "medium",
    "heavy"
  ];
  assertionEqual("ultra", Ladder.tierRank("ultra", ladder), -1);
  assertionEqual("empty", Ladder.tierRank("", ladder), -1);
});

Test.test("tierRank: empty ladder returns -1", () => assertionEqual("empty", Ladder.tierRank("fast", []), -1));

Test.test("resolveStartTier: producer in ladder, no floor => returns producerTier", () => {
  let p = makePolicy(undefined, undefined, undefined, undefined, undefined, undefined);
  assertionEqual("fast", Ladder.resolveStartTier("fast", p), "fast");
  assertionEqual("medium", Ladder.resolveStartTier("medium", p), "medium");
  assertionEqual("heavy", Ladder.resolveStartTier("heavy", p), "heavy");
});

Test.test("resolveStartTier: producer below floorTier => returns floorTier", () => {
  let p = makePolicy(undefined, "medium", undefined, undefined, undefined, undefined);
  assertionEqual("below", Ladder.resolveStartTier("fast", p), "medium");
});

Test.test("resolveStartTier: producer at floorTier => returns producerTier (same)", () => {
  let p = makePolicy(undefined, "medium", undefined, undefined, undefined, undefined);
  assertionEqual("at", Ladder.resolveStartTier("medium", p), "medium");
});

Test.test("resolveStartTier: producer above floorTier => returns producerTier", () => {
  let p = makePolicy(undefined, "fast", undefined, undefined, undefined, undefined);
  assertionEqual("above", Ladder.resolveStartTier("heavy", p), "heavy");
});

Test.test("resolveStartTier: floorTier heavy with producer fast => starts at heavy", () => {
  let p = makePolicy(undefined, "heavy", undefined, undefined, undefined, undefined);
  assertionEqual("heavyFloor", Ladder.resolveStartTier("fast", p), "heavy");
});

Test.test("resolveStartTier: unknown producer not in ladder => uses ladder[0]", () => {
  let p = makePolicy(undefined, undefined, undefined, undefined, undefined, undefined);
  assertionEqual("unknown", Ladder.resolveStartTier("unknown", p), "fast");
});

Test.test("resolveStartTier: unknown producer + floor medium => starts at medium", () => {
  let p = makePolicy(undefined, "medium", undefined, undefined, undefined, undefined);
  assertionEqual("unknownFloor", Ladder.resolveStartTier("unknown", p), "medium");
});

Test.test("resolveStartTier: empty ladder, no floor => returns producerTier as fallback", () => {
  let p = makePolicy([], undefined, undefined, undefined, undefined, undefined);
  assertionEqual("empty", Ladder.resolveStartTier("medium", p), "medium");
});

Test.test("resolveStartTier: floorTier not in ladder => acts as -1", () => {
  let p = makePolicy(undefined, "nonexistent", undefined, undefined, undefined, undefined);
  assertionEqual("unknownFloor", Ladder.resolveStartTier("fast", p), "fast");
});

Test.test("newLadderState: initialises all counters to zero/null", () => {
  let p = makePolicy(undefined, undefined, undefined, undefined, undefined, undefined);
  let s = Ladder.newLadderState("fast", p);
  assertionEqual("currentTier", s.currentTier, "fast");
  assertionEqual("attemptsThisTier", s.attemptsThisTier, 0);
  assertionEqual("totalAttempts", s.totalAttempts, 0);
  assertionEqual("escalations", s.escalations, 0);
  assertionEqual("firstAttemptCost", Primitive_option.fromNullable(s.firstAttemptCost), undefined);
  assertionEqual("cumulativeCost", s.cumulativeCost, 0);
});

Test.test("newLadderState: applies floorTier to currentTier", () => {
  let p = makePolicy(undefined, "medium", undefined, undefined, undefined, undefined);
  let s = Ladder.newLadderState("fast", p);
  assertionEqual("floor", s.currentTier, "medium");
});

Test.test("newLadderState: does not mutate input policy", () => {
  let p = makePolicy(undefined, undefined, undefined, undefined, undefined, undefined);
  let pJson = JSON.stringify(p);
  Ladder.newLadderState("fast", p);
  let pJsonAfter = JSON.stringify(p);
  assertionEqual("noMutate", pJson, pJsonAfter);
});

Test.test("recordAttempt: increments totalAttempts and cumulativeCost", () => {
  let s = makeState(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  let s2 = Ladder.recordAttempt(s, 5);
  assertionEqual("total", s2.totalAttempts, 1);
  assertionEqual("cumulative", s2.cumulativeCost, 5);
  assertionEqual("first", Primitive_option.fromNullable(s2.firstAttemptCost), 5);
});

Test.test("recordAttempt: firstAttemptCost set only once", () => {
  let s = makeState(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  let s1 = Ladder.recordAttempt(s, 3);
  let s2 = Ladder.recordAttempt(s1, 10);
  assertionEqual("first", Primitive_option.fromNullable(s2.firstAttemptCost), 3);
  assertionEqual("cumulative", s2.cumulativeCost, 13);
  assertionEqual("total", s2.totalAttempts, 2);
});

Test.test("recordAttempt: default cost is 0", () => {
  let s = makeState(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  let s2 = Ladder.recordAttempt(s, undefined);
  assertionEqual("cumulative", s2.cumulativeCost, 0);
  assertionEqual("first", Primitive_option.fromNullable(s2.firstAttemptCost), 0);
});

Test.test("recordAttempt: does NOT mutate input state", () => {
  let s = makeState(undefined, undefined, 0, undefined, undefined, 0, undefined);
  let sOrig = JSON.stringify(s);
  Ladder.recordAttempt(s, 7);
  let sAfter = JSON.stringify(s);
  assertionEqual("noMutate", sOrig, sAfter);
});

Test.test("recordAttempt: accumulates cost across many calls", () => {
  let s = makeState(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  let s1 = Ladder.recordAttempt(s, 1);
  let s2 = Ladder.recordAttempt(s1, 2);
  let s3 = Ladder.recordAttempt(s2, 3);
  let s4 = Ladder.recordAttempt(s3, 4);
  assertionEqual("cumulative", s4.cumulativeCost, 10);
  assertionEqual("first", Primitive_option.fromNullable(s4.firstAttemptCost), 1);
  assertionEqual("total", s4.totalAttempts, 4);
});

Test.test("nextTierAfter: fast => medium", () => {
  let p = makePolicy(undefined, undefined, undefined, undefined, undefined, undefined);
  assertionEqual("fast", Primitive_option.fromNullable(Ladder.nextTierAfter("fast", p)), "medium");
});

Test.test("nextTierAfter: medium => heavy", () => {
  let p = makePolicy(undefined, undefined, undefined, undefined, undefined, undefined);
  assertionEqual("medium", Primitive_option.fromNullable(Ladder.nextTierAfter("medium", p)), "heavy");
});

Test.test("nextTierAfter: heavy (top) => null", () => {
  let p = makePolicy(undefined, undefined, undefined, undefined, undefined, undefined);
  assertionEqual("top", Primitive_option.fromNullable(Ladder.nextTierAfter("heavy", p)), undefined);
});

Test.test("nextTierAfter: unknown tier => null", () => {
  let p = makePolicy(undefined, undefined, undefined, undefined, undefined, undefined);
  assertionEqual("unknown", Primitive_option.fromNullable(Ladder.nextTierAfter("unknown", p)), undefined);
});

Test.test("nextTierAfter: single-tier ladder => null", () => {
  let p = makePolicy(["medium"], undefined, undefined, undefined, undefined, undefined);
  assertionEqual("single", Primitive_option.fromNullable(Ladder.nextTierAfter("medium", p)), undefined);
});

Test.test("buildLadderForcingMessage: includes header line", () => {
  let msg = Ladder.buildLadderForcingMessage(["reason A"]);
  assertionTrue("header", stringContains(msg, "[router escalation]"));
});

Test.test("buildLadderForcingMessage: includes NEXT line", () => {
  let msg = Ladder.buildLadderForcingMessage(["x"]);
  assertionTrue("next", stringContains(msg, "NEXT: retry with these failures addressed."));
});

Test.test("buildLadderForcingMessage: formats each reason as a bullet", () => {
  let msg = Ladder.buildLadderForcingMessage([
    "foo",
    "bar"
  ]);
  assertionTrue("foo", stringContains(msg, "- foo"));
  assertionTrue("bar", stringContains(msg, "- bar"));
});

Test.test("buildLadderForcingMessage: empty reasons uses fallback bullet", () => {
  let msg = Ladder.buildLadderForcingMessage([]);
  assertionTrue("fallback", stringContains(msg, "- (no reasons provided)"));
  assertionFalse("noFoo", stringContains(msg, "- foo"));
});

Test.test("buildLadderForcingMessage: multiple reasons all present", () => {
  let msg = Ladder.buildLadderForcingMessage([
    "err1",
    "err2",
    "err3"
  ]);
  assertionTrue("err1", stringContains(msg, "- err1"));
  assertionTrue("err2", stringContains(msg, "- err2"));
  assertionTrue("err3", stringContains(msg, "- err3"));
});

Test.test("buildLadderForcingMessage: pure pass-through (no scrubbing)", () => {
  let msg = Ladder.buildLadderForcingMessage(["secret=abc123"]);
  assertionTrue("passThrough", stringContains(msg, "secret=abc123"));
});

Test.test("nextAction: verdict.pass=true => accept", () => {
  let p = makePolicy(undefined, undefined, undefined, undefined, undefined, undefined);
  let s = makeState(undefined, undefined, 1, undefined, undefined, undefined, undefined);
  let a = Ladder.nextAction(s, {
    pass: true,
    reasons: undefined
  }, p, undefined);
  assertionEqual("action", a.action, "accept");
});

Test.test("nextAction: verdict null => treated as FAIL", () => {
  let p = makePolicy(undefined, undefined, 2, 4, undefined, undefined);
  let s = makeState(undefined, 0, 1, undefined, undefined, undefined, undefined);
  let a = Ladder.nextAction(s, null, p, undefined);
  assertionFalse("notAccept", a.action === "accept");
});

Test.test("nextAction: verdict undefined => treated as FAIL", () => {
  let p = makePolicy(undefined, undefined, 2, 4, undefined, undefined);
  let s = makeState(undefined, 0, 1, undefined, undefined, undefined, undefined);
  let a = Ladder.nextAction(s, null, p, undefined);
  assertionFalse("notAccept", a.action === "accept");
});

Test.test("nextAction: maxTotalAttempts reached => give_up with message", () => {
  let p = makePolicy(undefined, undefined, undefined, 3, undefined, undefined);
  let s = makeState(undefined, 0, 3, undefined, undefined, undefined, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionEqual("action", a.action, "give_up");
  let r = a.reason;
  if (r == null) {
    return assertionTrue("reason", false);
  } else {
    return assertionTrue("reason", stringContains(r, "max total attempts (3)"));
  }
});

Test.test("nextAction: maxTotalAttempts check precedes retry", () => {
  let p = makePolicy(undefined, undefined, 5, 2, undefined, undefined);
  let s = makeState(undefined, 0, 2, undefined, undefined, undefined, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionEqual("giveUp", a.action, "give_up");
});

Test.test("nextAction: cost ceiling exceeded => give_up", () => {
  let p = makePolicy(undefined, undefined, undefined, 10, 2, undefined);
  let s = makeState(undefined, undefined, 2, undefined, 5, 11, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionEqual("action", a.action, "give_up");
  assertionEqual("reason", Primitive_option.fromNullable(a.reason), "cost ceiling exceeded");
});

Test.test("nextAction: cost ceiling at exact threshold is NOT exceeded", () => {
  let p = makePolicy(undefined, undefined, undefined, 10, 2, undefined);
  let s = makeState(undefined, 0, 2, undefined, 5, 10, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionEqual("retry", a.action, "retry");
});

Test.test("nextAction: retry when attemptsThisTier < maxAttemptsPerTier", () => {
  let p = makePolicy(undefined, undefined, 2, 10, undefined, undefined);
  let s = makeState(undefined, 0, 1, undefined, undefined, undefined, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionEqual("action", a.action, "retry");
  assertionEqual("tier", Primitive_option.fromNullable(a.tier), "fast");
  assertionTrue("forcing", Primitive_option.fromNullable(a.forcingMessage) !== undefined);
});

Test.test("nextAction: retry includes forcingMessage from verdict reasons", () => {
  let p = makePolicy(undefined, undefined, 3, 10, undefined, undefined);
  let s = makeState(undefined, 0, 1, undefined, undefined, undefined, undefined);
  let verdict_reasons = ["bad output"];
  let verdict = {
    pass: false,
    reasons: verdict_reasons
  };
  let a = Ladder.nextAction(s, verdict, p, undefined);
  assertionEqual("action", a.action, "retry");
  let msg = a.forcingMessage;
  if (msg == null) {
    return assertionTrue("forcing", false);
  } else {
    return assertionTrue("forcing", stringContains(msg, "bad output"));
  }
});

Test.test("nextAction: escalate when attemptsThisTier >= maxAttemptsPerTier and next tier exists", () => {
  let p = makePolicy(undefined, undefined, 1, 10, undefined, undefined);
  let s = makeState("fast", 1, 1, undefined, undefined, undefined, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionEqual("action", a.action, "escalate");
  assertionEqual("tier", Primitive_option.fromNullable(a.tier), "medium");
  assertionTrue("forcing", Primitive_option.fromNullable(a.forcingMessage) !== undefined);
});

Test.test("nextAction: give_up at top of ladder", () => {
  let p = makePolicy(undefined, undefined, 1, 10, undefined, undefined);
  let s = makeState("heavy", 1, 1, undefined, undefined, undefined, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionEqual("action", a.action, "give_up");
  assertionEqual("reason", Primitive_option.fromNullable(a.reason), "no higher tier (already at top of ladder)");
});

Test.test("nextAction: maxAttemptsPerTier 0 => escalate immediately", () => {
  let p = makePolicy([
    "fast",
    "medium",
    "heavy"
  ], undefined, 0, 10, undefined, undefined);
  let s = makeState("fast", 0, 1, undefined, undefined, undefined, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionEqual("action", a.action, "escalate");
  assertionEqual("tier", Primitive_option.fromNullable(a.tier), "medium");
});

Test.test("nextAction: single-tier ladder retries up to cap then give_up", () => {
  let p = makePolicy(["medium"], undefined, 2, 10, undefined, undefined);
  let s = makeState("medium", 2, 3, undefined, undefined, undefined, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionEqual("action", a.action, "give_up");
  assertionEqual("reason", Primitive_option.fromNullable(a.reason), "no higher tier (already at top of ladder)");
});

Test.test("nextAction: no forcingMessage on give_up", () => {
  let p = makePolicy(undefined, undefined, undefined, 1, undefined, undefined);
  let s = makeState(undefined, undefined, 1, undefined, undefined, undefined, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionEqual("action", a.action, "give_up");
  assertionEqual("noForcing", Primitive_option.fromNullable(a.forcingMessage), undefined);
});

Test.test("nextAction: costMultiple=0 => cost check never triggers", () => {
  let p = makePolicy(undefined, undefined, 1, 10, 0, undefined);
  let s = makeState(undefined, 0, 2, undefined, 1, 99999, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionFalse("notGiveUp", a.action === "give_up");
});

Test.test("nextAction: firstAttemptCost null => cost check never triggers", () => {
  let p = makePolicy(undefined, undefined, 3, 10, 2, undefined);
  let s = makeState(undefined, 0, 1, undefined, null, 100, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionFalse("notGiveUp", a.action === "give_up");
});

Test.test("nextAction: accept takes priority over cost/attempt checks", () => {
  let p = makePolicy(undefined, undefined, undefined, 1, 1, undefined);
  let s = makeState(undefined, undefined, 5, undefined, 1, 100, undefined);
  let a = Ladder.nextAction(s, {
    pass: true,
    reasons: undefined
  }, p, undefined);
  assertionEqual("action", a.action, "accept");
});

Test.test("advance: retry increments attemptsThisTier only", () => {
  let s = makeState("fast", 0, undefined, undefined, undefined, undefined, undefined);
  let action_forcingMessage = null;
  let action_reason = null;
  let action = {
    action: "retry",
    tier: "fast",
    forcingMessage: action_forcingMessage,
    reason: action_reason
  };
  let s2 = Ladder.advance(s, action);
  assertionEqual("attempts", s2.attemptsThisTier, 1);
  assertionEqual("tier", s2.currentTier, "fast");
  assertionEqual("escalations", s2.escalations, 0);
  assertionEqual("totalUnchanged", s2.totalAttempts, 0);
});

Test.test("advance: escalate updates currentTier resets attemptsThisTier increments escalations", () => {
  let s = makeState("fast", 1, undefined, 0, undefined, undefined, undefined);
  let action_forcingMessage = null;
  let action_reason = null;
  let action = {
    action: "escalate",
    tier: "medium",
    forcingMessage: action_forcingMessage,
    reason: action_reason
  };
  let s2 = Ladder.advance(s, action);
  assertionEqual("tier", s2.currentTier, "medium");
  assertionEqual("attempts", s2.attemptsThisTier, 0);
  assertionEqual("escalations", s2.escalations, 1);
});

Test.test("advance: accept => state unchanged", () => {
  let s = makeState("medium", undefined, 3, undefined, undefined, undefined, undefined);
  let action_tier = null;
  let action_forcingMessage = null;
  let action_reason = null;
  let action = {
    action: "accept",
    tier: action_tier,
    forcingMessage: action_forcingMessage,
    reason: action_reason
  };
  let s2 = Ladder.advance(s, action);
  assertionEqual("same", s2, s);
});

Test.test("advance: give_up => state unchanged", () => {
  let s = makeState("heavy", undefined, 4, undefined, undefined, undefined, undefined);
  let action_tier = null;
  let action_forcingMessage = null;
  let action = {
    action: "give_up",
    tier: action_tier,
    forcingMessage: action_forcingMessage,
    reason: "done"
  };
  let s2 = Ladder.advance(s, action);
  assertionEqual("same", s2, s);
});

Test.test("advance: does NOT mutate input state on retry", () => {
  let s = makeState(undefined, 2, undefined, undefined, undefined, undefined, undefined);
  let sOrig = JSON.stringify(s);
  let action_forcingMessage = null;
  let action_reason = null;
  let action = {
    action: "retry",
    tier: "fast",
    forcingMessage: action_forcingMessage,
    reason: action_reason
  };
  Ladder.advance(s, action);
  let sAfter = JSON.stringify(s);
  assertionEqual("noMutate", sOrig, sAfter);
});

Test.test("advance: does NOT mutate input state on escalate", () => {
  let s = makeState("fast", undefined, undefined, 0, undefined, undefined, undefined);
  let sOrig = JSON.stringify(s);
  let action_forcingMessage = null;
  let action_reason = null;
  let action = {
    action: "escalate",
    tier: "medium",
    forcingMessage: action_forcingMessage,
    reason: action_reason
  };
  Ladder.advance(s, action);
  let sAfter = JSON.stringify(s);
  assertionEqual("noMutate", sOrig, sAfter);
});

Test.test("buildEscalatePolicy: all defaults when enforcement absent", () => {
  let cfg_presets = {};
  let cfg_rules = [];
  let cfg = {
    activePreset: "default",
    presets: cfg_presets,
    rules: cfg_rules,
    defaultTier: "fast",
    enforcement: undefined
  };
  let p = Ladder.buildEscalatePolicy(cfg);
  Test.assertion(undefined, "ladderDeepEqual", Primitive_object.equal, p.ladder, [
    "fast",
    "medium",
    "heavy"
  ]);
  assertionEqual("floorTier", Primitive_option.fromNullable(p.floorTier), undefined);
  assertionEqual("maxAttempts", p.maxAttemptsPerTier, 1);
  assertionEqual("maxTotal", p.maxTotalAttempts, 4);
  assertionEqual("costMultiple", Primitive_option.fromNullable(p.costMultiple), 4);
});

Test.test("formatLadderScorecard: accepted=true => verdict=PASS", () => {
  let s = makeState("medium", undefined, 2, 1, undefined, 8, undefined);
  let result = Ladder.formatLadderScorecard(s, true, "grader");
  assertionTrue("PASS", stringContains(result, "verdict=PASS"));
  assertionTrue("tier", stringContains(result, "final_tier=medium"));
  assertionTrue("attempts", stringContains(result, "attempts=2"));
  assertionTrue("escalations", stringContains(result, "escalations=1"));
  assertionTrue("cost", stringContains(result, "cost=8"));
  assertionTrue("method", stringContains(result, "method=grader"));
});

Test.test("formatLadderScorecard: accepted=false => verdict=UNMET", () => {
  let s = makeState(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  let result = Ladder.formatLadderScorecard(s, false, "heuristic");
  assertionTrue("UNMET", stringContains(result, "verdict=UNMET"));
  assertionFalse("noPASS", stringContains(result, "verdict=PASS"));
});

Test.test("edge: FAIL at heavy with no retries left => give_up no higher tier", () => {
  let p = makePolicy(undefined, undefined, 1, 10, undefined, undefined);
  let s = makeState("heavy", 1, 1, undefined, undefined, undefined, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionEqual("giveUp", a.action, "give_up");
  assertionEqual("reason", Primitive_option.fromNullable(a.reason), "no higher tier (already at top of ladder)");
});

Test.test("edge: maxTotalAttempts mid-ladder => give_up max total attempts", () => {
  let p = makePolicy(undefined, undefined, 5, 2, undefined, undefined);
  let s = makeState("medium", 0, 2, undefined, undefined, undefined, undefined);
  let a = Ladder.nextAction(s, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionEqual("giveUp", a.action, "give_up");
  let r = a.reason;
  if (r == null) {
    return assertionTrue("reason", false);
  } else {
    return assertionTrue("reason", stringContains(r, "max total attempts (2)"));
  }
});

Test.test("edge: retry then PASS => accept on second call", () => {
  let p = makePolicy(undefined, undefined, 2, 10, undefined, undefined);
  let s = makeState(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  let s2 = Ladder.recordAttempt(s, 1);
  let a1 = Ladder.nextAction(s2, {
    pass: false,
    reasons: undefined
  }, p, undefined);
  assertionEqual("retry1", a1.action, "retry");
  let s3 = Ladder.advance(s2, a1);
  let s4 = Ladder.recordAttempt(s3, 1);
  let a2 = Ladder.nextAction(s4, {
    pass: true,
    reasons: undefined
  }, p, undefined);
  assertionEqual("accept2", a2.action, "accept");
});

Test.test("edge: floorTier heavy with producer fast => starts at heavy", () => {
  let p = makePolicy(undefined, "heavy", undefined, undefined, undefined, undefined);
  let s = Ladder.newLadderState("fast", p);
  assertionEqual("startsHeavy", s.currentTier, "heavy");
});

Test.test("edge: producer below floor => starts at floor", () => {
  let p = makePolicy(undefined, "medium", undefined, undefined, undefined, undefined);
  let s = Ladder.newLadderState("fast", p);
  assertionEqual("startsFloor", s.currentTier, "medium");
});

Test.test("edge: unknown producer not in ladder => starts at ladder[0]", () => {
  let p = makePolicy(undefined, null, undefined, undefined, undefined, undefined);
  let s = Ladder.newLadderState("turbo", p);
  assertionEqual("startsLadder0", s.currentTier, "fast");
});

export {
  assertionEqual,
  assertionTrue,
  assertionFalse,
  stringContains,
  makePolicy,
  makeState,
}
/*  Not a pure module */
