// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TierLadder from "../router/TierLadder.res.mjs";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function isAborted(signal) {
  if (signal !== undefined) {
    return aborted(signal);
  } else {
    return false;
  }
}

function tierRank(tier, ladder) {
  return ladder.indexOf(tier);
}

function resolveStartTier(producerTier, policy) {
  let pi = policy.ladder.indexOf(producerTier);
  let ft = policy.floorTier;
  let fi = ft !== undefined ? policy.ladder.indexOf(ft) : -1;
  let p = pi >= 0 ? pi : 0;
  let f = fi >= 0 ? fi : 0;
  let startIdx = p > f ? p : f;
  let t = policy.ladder[startIdx];
  if (t !== undefined) {
    return t;
  } else {
    return producerTier;
  }
}

function newLadderState(producerTier, policy) {
  return {
    currentTier: resolveStartTier(producerTier, policy),
    attemptsThisTier: 0,
    totalAttempts: 0,
    escalations: 0,
    firstAttemptCost: undefined,
    cumulativeCost: 0
  };
}

function recordAttempt(state, costUnitsOpt) {
  let costUnits = costUnitsOpt !== undefined ? costUnitsOpt : 0;
  return {
    currentTier: state.currentTier,
    attemptsThisTier: state.attemptsThisTier,
    totalAttempts: state.totalAttempts + 1 | 0,
    escalations: state.escalations,
    firstAttemptCost: state.firstAttemptCost === undefined ? costUnits : state.firstAttemptCost,
    cumulativeCost: state.cumulativeCost + costUnits | 0
  };
}

function nextTierAfter(currentTier, policy) {
  let ci = policy.ladder.indexOf(currentTier);
  if (ci >= 0 && (ci + 1 | 0) <= (policy.ladder.length - 1 | 0)) {
    return policy.ladder[ci + 1 | 0];
  }
}

function buildLadderForcingMessage(reasons) {
  let len = reasons.length;
  let list = len === 0 ? "- (no reasons provided)" : reasons.map(r => "- " + r).join("\n");
  return "[router escalation] previous attempt did not pass verification:\n" + list + "\nNEXT: retry with these failures addressed.";
}

function nextAction(state, verdict, policy, signal) {
  if (verdict !== undefined && verdict.pass === true) {
    return {
      action: "accept",
      tier: undefined,
      forcingMessage: undefined,
      reason: undefined
    };
  }
  if (isAborted(signal)) {
    return {
      action: "give_up",
      tier: undefined,
      forcingMessage: undefined,
      reason: "aborted"
    };
  }
  let fc = state.firstAttemptCost;
  let costExceeded = fc !== undefined ? state.cumulativeCost > (fc * policy.costMultiple | 0) : false;
  if (state.totalAttempts >= policy.maxTotalAttempts) {
    return {
      action: "give_up",
      tier: undefined,
      forcingMessage: undefined,
      reason: "max total attempts (" + String(policy.maxTotalAttempts) + ") reached"
    };
  }
  if (costExceeded) {
    return {
      action: "give_up",
      tier: undefined,
      forcingMessage: undefined,
      reason: "cost ceiling exceeded"
    };
  }
  if (state.attemptsThisTier < policy.maxAttemptsPerTier) {
    let reasons = verdict !== undefined ? Belt_Option.getWithDefault(verdict.reasons, []) : [];
    return {
      action: "retry",
      tier: state.currentTier,
      forcingMessage: buildLadderForcingMessage(reasons),
      reason: undefined
    };
  }
  let next = nextTierAfter(state.currentTier, policy);
  if (next === undefined) {
    return {
      action: "give_up",
      tier: undefined,
      forcingMessage: undefined,
      reason: "no higher tier (already at top of ladder)"
    };
  }
  let reasons$1 = verdict !== undefined ? Belt_Option.getWithDefault(verdict.reasons, []) : [];
  return {
    action: "escalate",
    tier: next,
    forcingMessage: buildLadderForcingMessage(reasons$1),
    reason: undefined
  };
}

function advance(state, action) {
  let match = action.action;
  if (match === "accept" || match === "give_up") {
    return state;
  }
  if (match !== "escalate") {
    return {
      currentTier: state.currentTier,
      attemptsThisTier: state.attemptsThisTier + 1 | 0,
      totalAttempts: state.totalAttempts,
      escalations: state.escalations,
      firstAttemptCost: state.firstAttemptCost,
      cumulativeCost: state.cumulativeCost
    };
  }
  let t = action.tier;
  if (t !== undefined) {
    return {
      currentTier: t,
      attemptsThisTier: 0,
      totalAttempts: state.totalAttempts,
      escalations: state.escalations + 1 | 0,
      firstAttemptCost: state.firstAttemptCost,
      cumulativeCost: state.cumulativeCost
    };
  } else {
    return state;
  }
}

function buildEscalatePolicy(cfg) {
  let enf = cfg.enforcement;
  let esc = enf !== undefined ? enf.escalate : undefined;
  let explicitLadder = esc !== undefined ? esc.ladder : undefined;
  let ladder = Belt_Option.getWithDefault(explicitLadder, TierLadder.defaultTierNames);
  let floorTier = esc !== undefined ? Belt_Option.flatMap(esc.floorTier, x => x) : undefined;
  let maxAttemptsPerTier = esc !== undefined ? esc.maxAttemptsPerTier : undefined;
  let maxTotalAttempts = esc !== undefined ? esc.maxTotalAttempts : undefined;
  let costMultiple;
  if (esc !== undefined) {
    let cc = esc.costCeiling;
    costMultiple = cc !== undefined ? Belt_Option.map(cc.multiple, v => v | 0) : undefined;
  } else {
    costMultiple = undefined;
  }
  return {
    ladder: ladder,
    floorTier: floorTier,
    maxAttemptsPerTier: Belt_Option.getWithDefault(maxAttemptsPerTier, 1),
    maxTotalAttempts: Belt_Option.getWithDefault(maxTotalAttempts, 4),
    costMultiple: Belt_Option.getWithDefault(costMultiple, 4)
  };
}

function formatLadderScorecard(state, accepted, method) {
  let verdictStr = accepted ? "PASS" : "UNMET";
  return "[router delegate scorecard | final_tier=" + state.currentTier + " | attempts=" + String(state.totalAttempts) + " | escalations=" + String(state.escalations) + " | cost=" + String(state.cumulativeCost) + " | verdict=" + verdictStr + " | method=" + method + "]";
}

export {
  tierRank,
  resolveStartTier,
  newLadderState,
  recordAttempt,
  nextTierAfter,
  buildLadderForcingMessage,
  nextAction,
  advance,
  buildEscalatePolicy,
  formatLadderScorecard,
}
/* No side effect */
