// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function isAborted(signal) {
  if (signal !== undefined) {
    return signal.aborted;
  } else {
    return false;
  }
}

function tierRank(tier, ladder) {
  return ladder.indexOf(tier);
}

function resolveStartTier(producerTier, policy) {
  let pi = policy.ladder.indexOf(producerTier);
  let ft = policy.floorTier;
  let fi = (ft == null) ? -1 : policy.ladder.indexOf(ft);
  let p = pi >= 0 ? pi : 0;
  let f = fi >= 0 ? fi : 0;
  let startIdx = p > f ? p : f;
  let t = policy.ladder[startIdx];
  if (t !== undefined) {
    return t;
  } else {
    return producerTier;
  }
}

function newLadderState(producerTier, policy) {
  return {
    currentTier: resolveStartTier(producerTier, policy),
    attemptsThisTier: 0,
    totalAttempts: 0,
    escalations: 0,
    firstAttemptCost: null,
    cumulativeCost: 0
  };
}

function recordAttempt(state, costUnitsOpt) {
  let costUnits = costUnitsOpt !== undefined ? costUnitsOpt : 0;
  return {
    currentTier: state.currentTier,
    attemptsThisTier: state.attemptsThisTier,
    totalAttempts: state.totalAttempts + 1 | 0,
    escalations: state.escalations,
    firstAttemptCost: (state.firstAttemptCost == null) ? costUnits : state.firstAttemptCost,
    cumulativeCost: state.cumulativeCost + costUnits | 0
  };
}

function nextTierAfter(currentTier, policy) {
  let ci = policy.ladder.indexOf(currentTier);
  if (!(ci >= 0 && (ci + 1 | 0) <= (policy.ladder.length - 1 | 0))) {
    return null;
  }
  let t = policy.ladder[ci + 1 | 0];
  if (t !== undefined) {
    return t;
  } else {
    return null;
  }
}

function buildLadderForcingMessage(reasons) {
  let len = reasons.length;
  let list = len === 0 ? "- (no reasons provided)" : reasons.map(r => "- " + r).join("\n");
  return "[router escalation] previous attempt did not pass verification:\n" + list + "\nNEXT: retry with these failures addressed.";
}

function nextAction(state, verdict, policy, signal) {
  let isAccept = (verdict == null) ? false : verdict.pass;
  if (isAccept) {
    return {
      action: "accept",
      tier: null,
      forcingMessage: null,
      reason: null
    };
  }
  if (isAborted(signal)) {
    return {
      action: "give_up",
      tier: null,
      forcingMessage: null,
      reason: "aborted"
    };
  }
  let fc = state.firstAttemptCost;
  let costExceeded;
  if (fc == null) {
    costExceeded = false;
  } else {
    let cm = policy.costMultiple;
    costExceeded = (cm == null) ? false : cm >= 0 && state.cumulativeCost > (fc * cm | 0);
  }
  if (state.totalAttempts >= policy.maxTotalAttempts) {
    return {
      action: "give_up",
      tier: null,
      forcingMessage: null,
      reason: "max total attempts (" + String(policy.maxTotalAttempts) + ") reached"
    };
  }
  if (costExceeded) {
    return {
      action: "give_up",
      tier: null,
      forcingMessage: null,
      reason: "cost ceiling exceeded"
    };
  }
  if (state.attemptsThisTier < policy.maxAttemptsPerTier) {
    let reasons = (verdict == null) ? [] : Belt_Option.getWithDefault(verdict.reasons, []);
    return {
      action: "retry",
      tier: state.currentTier,
      forcingMessage: buildLadderForcingMessage(reasons),
      reason: null
    };
  }
  let next = nextTierAfter(state.currentTier, policy);
  if (next == null) {
    return {
      action: "give_up",
      tier: null,
      forcingMessage: null,
      reason: "no higher tier (already at top of ladder)"
    };
  }
  let reasons$1 = (verdict == null) ? [] : Belt_Option.getWithDefault(verdict.reasons, []);
  return {
    action: "escalate",
    tier: next,
    forcingMessage: buildLadderForcingMessage(reasons$1),
    reason: null
  };
}

function advance(state, action) {
  let match = action.action;
  if (match === "accept" || match === "give_up") {
    return state;
  }
  if (match !== "escalate") {
    return {
      currentTier: state.currentTier,
      attemptsThisTier: state.attemptsThisTier + 1 | 0,
      totalAttempts: state.totalAttempts,
      escalations: state.escalations,
      firstAttemptCost: state.firstAttemptCost,
      cumulativeCost: state.cumulativeCost
    };
  }
  let t = action.tier;
  if (t == null) {
    return state;
  } else {
    return {
      currentTier: t,
      attemptsThisTier: 0,
      totalAttempts: state.totalAttempts,
      escalations: state.escalations + 1 | 0,
      firstAttemptCost: state.firstAttemptCost,
      cumulativeCost: state.cumulativeCost
    };
  }
}

function buildEscalatePolicy(_cfg) {
  let enf = _cfg.enforcement;
  let esc = enf !== undefined ? enf.escalate : undefined;
  let explicitLadder = esc !== undefined ? esc.ladder : undefined;
  let ladder = Belt_Option.getWithDefault(explicitLadder, [
    "fast",
    "medium",
    "heavy"
  ]);
  let floorTier;
  if (esc !== undefined) {
    let ft = Belt_Option.flatMap(esc.floorTier, x => x);
    floorTier = ft !== undefined ? ft : null;
  } else {
    floorTier = null;
  }
  let maxAttemptsPerTier = esc !== undefined ? esc.maxAttemptsPerTier : undefined;
  let maxTotalAttempts = esc !== undefined ? esc.maxTotalAttempts : undefined;
  let costMultiple;
  if (esc !== undefined) {
    let cc = esc.costCeiling;
    if (cc !== undefined) {
      let v = cc.multiple;
      costMultiple = v !== undefined ? v | 0 : null;
    } else {
      costMultiple = 4;
    }
  } else {
    costMultiple = 4;
  }
  return {
    ladder: ladder,
    floorTier: floorTier,
    maxAttemptsPerTier: Belt_Option.getWithDefault(maxAttemptsPerTier, 1),
    maxTotalAttempts: Belt_Option.getWithDefault(maxTotalAttempts, 4),
    costMultiple: costMultiple
  };
}

function formatLadderScorecard(state, accepted, method) {
  let verdictStr = accepted ? "PASS" : "UNMET";
  return "[router delegate scorecard | final_tier=" + state.currentTier + " | attempts=" + String(state.totalAttempts) + " | escalations=" + String(state.escalations) + " | cost=" + String(state.cumulativeCost) + " | verdict=" + verdictStr + " | method=" + method + "]";
}

export {
  tierRank,
  resolveStartTier,
  newLadderState,
  recordAttempt,
  nextTierAfter,
  buildLadderForcingMessage,
  nextAction,
  advance,
  buildEscalatePolicy,
  formatLadderScorecard,
}
/* No side effect */
