// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReasoningTranslate from "./ReasoningTranslate.res.mjs";
import * as ReasoningCapability from "./ReasoningCapability.res.mjs";

function _levelFromString(s) {
  switch (s) {
    case "elevated" :
      return "elevated";
    case "max" :
      return "max";
    case "minimal" :
      return "minimal";
    case "normal" :
      return "normal";
    default:
      return;
  }
}

function _getMode(policy) {
  if (policy !== undefined) {
    return policy.mode;
  }
}

function _getDefaultLevel(policy) {
  if (policy !== undefined) {
    return policy.defaultLevel;
  }
}

function resolveReasoningOverride(tier, policy, sessionOverride, _signals) {
  let mode = _getMode(policy);
  if (mode === undefined) {
    return null;
  }
  if (mode === "static") {
    return null;
  }
  if (mode === undefined) {
    return null;
  }
  switch (mode) {
    case "manual" :
      let level;
      if (sessionOverride !== undefined) {
        level = sessionOverride;
      } else {
        let dl = _getDefaultLevel(policy);
        level = dl !== undefined ? _levelFromString(dl) : undefined;
      }
      if (level === undefined) {
        return null;
      }
      let c = tier.capability;
      let cap = c !== undefined ? c : ReasoningCapability.inferCapability(tier);
      let r = ReasoningTranslate.translateLevel(cap, level);
      if (r !== undefined) {
        return r;
      } else {
        return null;
      }
    default:
      return null;
  }
}

export {
  resolveReasoningOverride,
}
/* ReasoningTranslate Not a pure module */
