// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReasoningMatch from "./ReasoningMatch.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function _levelFromString(s) {
  switch (s) {
    case "elevated" :
      return "elevated";
    case "max" :
      return "max";
    case "minimal" :
      return "minimal";
    case "normal" :
      return "normal";
    default:
      return null;
  }
}

function _getMatchMode(m) {
  if (m === undefined) {
    return "stem";
  }
  switch (m) {
    case "regex" :
      return "regex";
    case "substring" :
      return "substring";
    case "word" :
      return "word";
    default:
      return "stem";
  }
}

function _isExcluded(exclusions, prompt, description, mode) {
  return exclusions.some(k => {
    if (k === "") {
      return false;
    } else if (ReasoningMatch.matchSignal(prompt, k, mode)) {
      return true;
    } else {
      return ReasoningMatch.matchSignal(description, k, mode);
    }
  });
}

function _checkRule(rule, idx, prompt, description) {
  if (rule.keywords.length === 0) {
    return;
  }
  let mode = _getMatchMode(rule.match);
  let modeStr = mode === "word" ? "word" : (
      mode === "substring" ? "substring" : (
          mode === "regex" ? "regex" : "stem"
        )
    );
  let ex = rule.excludeKeywords;
  let exclusions = ex !== undefined ? ex : [];
  if (_isExcluded(exclusions, prompt, description, mode)) {
    return;
  }
  let matched = rule.keywords.find(kw => {
    if (kw === "") {
      return false;
    } else if (ReasoningMatch.matchSignal(prompt, kw, mode)) {
      return true;
    } else {
      return ReasoningMatch.matchSignal(description, kw, mode);
    }
  });
  if (matched === undefined) {
    return;
  }
  let source = ReasoningMatch.matchSignal(prompt, matched, mode) ? "prompt" : "description";
  let lvl = _levelFromString(rule.level);
  return {
    level: lvl,
    reason: `keyword match: rule[` + idx.toString() + `] "` + matched + `" (` + modeStr + `) in ` + source
  };
}

function _scanRules(rules, _idx, prompt, description) {
  while (true) {
    let idx = _idx;
    let rulesLen = rules.length;
    if (idx >= rulesLen) {
      return;
    }
    let rule = rules[idx];
    if (rule !== undefined) {
      let d = _checkRule(rule, idx, prompt, description);
      if (d !== undefined) {
        return d;
      }
      _idx = idx + 1 | 0;
      continue;
    }
    _idx = idx + 1 | 0;
    continue;
  };
}

function selectAdaptiveLevel(signals, policy) {
  let adaptive = policy !== undefined ? policy.adaptive : undefined;
  if (adaptive === undefined) {
    return {
      level: null,
      reason: "no adaptive config"
    };
  }
  if (signals.isTrivial) {
    let s = adaptive.trivialLevel;
    let lvl = s !== undefined ? _levelFromString(s) : null;
    return {
      level: lvl,
      reason: "trivial"
    };
  }
  let td = adaptive.tierDefaults;
  let tierDefaults = td !== undefined ? td : ({});
  let tierLevel = tierDefaults[signals.tierName];
  if (tierLevel !== undefined) {
    let lvl$1 = _levelFromString(tierLevel);
    return {
      level: lvl$1,
      reason: `tier default: ` + signals.tierName
    };
  }
  let rules = adaptive.keywordRules;
  let keywordRules = rules !== undefined ? rules : [];
  let d = _scanRules(keywordRules, 0, signals.prompt, signals.description);
  if (d !== undefined) {
    return d;
  }
  let s$1 = adaptive.defaultLevel;
  let lvl$2 = s$1 !== undefined ? _levelFromString(s$1) : null;
  return {
    level: lvl$2,
    reason: "default level"
  };
}

function getLevelNull(d) {
  return d.level;
}

function getLevelOption(d) {
  return Primitive_option.fromNullable(d.level);
}

function getReason(d) {
  return d.reason;
}

function makePolicyWithAdaptive(adaptive) {
  return {
    mode: "adaptive",
    defaultLevel: undefined,
    surfaceLimits: undefined,
    adaptive: adaptive
  };
}

export {
  selectAdaptiveLevel,
  getLevelNull,
  getLevelOption,
  getReason,
  makePolicyWithAdaptive,
}
/* No side effect */
