// Generated by ReScript, PLEASE EDIT WITH CARE


let d = {};

d["low"] = true;

d["medium"] = true;

d["high"] = true;

d["xhigh"] = true;

let d$1 = {};

d$1["thinking"] = true;

d$1["max"] = true;

function _makeBudgetLadder() {
  let d = {};
  d["minimal"] = 1024.0;
  d["normal"] = 4096.0;
  d["elevated"] = 8192.0;
  d["max"] = 16000.0;
  return d;
}

function _step3(tier) {
  let v = tier.variant;
  if (v === undefined) {
    return {
      kind: "none"
    };
  }
  let match = d[v];
  if (match !== undefined) {
    let levels = v === "xhigh" ? [
        "low",
        "medium",
        "high",
        "xhigh"
      ] : [
        "low",
        "medium",
        "high"
      ];
    return {
      kind: "discrete",
      field: "variant",
      levels: levels
    };
  }
  let match$1 = d$1[v];
  if (match$1 !== undefined) {
    return {
      kind: "binary",
      field: "variant",
      elevated: v
    };
  } else {
    return {
      kind: "none"
    };
  }
}

function _step2(tier) {
  let t = tier.thinking;
  if (t === undefined) {
    return _step3(tier);
  }
  let match = t.budgetTokens;
  if (match !== undefined) {
    return {
      kind: "budgeted",
      field: "thinking.budgetTokens",
      recommended: _makeBudgetLadder()
    };
  } else {
    return _step3(tier);
  }
}

function inferCapability(tier) {
  let r = tier.reasoning;
  if (r === undefined) {
    return _step2(tier);
  }
  let match = r.effort;
  if (match !== undefined) {
    return {
      kind: "discrete",
      field: "reasoning.effort",
      levels: [
        "low",
        "medium",
        "high"
      ]
    };
  } else {
    return _step2(tier);
  }
}

export {
  inferCapability,
}
/*  Not a pure module */
