// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReasoningMatch from "./ReasoningMatch.res.mjs";
import * as ReasoningPolicy from "./ReasoningPolicy.res.mjs";
import * as ReasoningAdaptive from "./ReasoningAdaptive.res.mjs";
import * as ReasoningTranslate from "./ReasoningTranslate.res.mjs";
import * as ReasoningCapability from "./ReasoningCapability.res.mjs";

let Match;

let Capability;

let Translate;

let Policy;

let Adaptive;

let normalizeSignalText = ReasoningMatch.normalizeSignalText;

let matchSignal = ReasoningMatch.matchSignal;

let inferCapability = ReasoningCapability.inferCapability;

let translateLevel = ReasoningTranslate.translateLevel;

let resolveReasoningOverride = ReasoningPolicy.resolveReasoningOverride;

let selectAdaptiveLevel = ReasoningAdaptive.selectAdaptiveLevel;

let getLevelNull = ReasoningAdaptive.getLevelNull;

let getLevelOption = ReasoningAdaptive.getLevelOption;

let getReason = ReasoningAdaptive.getReason;

let makePolicyWithAdaptive = ReasoningAdaptive.makePolicyWithAdaptive;

export {
  Match,
  Capability,
  Translate,
  Policy,
  Adaptive,
  normalizeSignalText,
  matchSignal,
  inferCapability,
  translateLevel,
  resolveReasoningOverride,
  selectAdaptiveLevel,
  getLevelNull,
  getLevelOption,
  getReason,
  makePolicyWithAdaptive,
}
/* ReasoningPolicy Not a pure module */
