// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReasoningMatch from "./ReasoningMatch.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function _nullLevel() {
  return null;
}

function _getTrivialLevel(_ac) {
  return ((function(ac) { return ac.trivialLevel == null ? undefined : ac.trivialLevel; })(arguments[0]));
}

function _getTierDefaults(_ac) {
  return ((function(ac) { return ac.tierDefaults == null ? undefined : ac.tierDefaults; })(arguments[0]));
}

function _getKeywordRules(_ac) {
  return ((function(ac) { return ac.keywordRules == null ? undefined : ac.keywordRules; })(arguments[0]));
}

function _getDefaultLevel(_ac) {
  return ((function(ac) { return ac.defaultLevel == null ? undefined : ac.defaultLevel; })(arguments[0]));
}

function _levelFromString(s) {
  switch (s) {
    case "elevated" :
      return "elevated";
    case "max" :
      return "max";
    case "minimal" :
      return "minimal";
    case "normal" :
      return "normal";
    default:
      return _nullLevel();
  }
}

function _getMatchMode(m) {
  if (m === undefined) {
    return "stem";
  }
  switch (m) {
    case "regex" :
      return "regex";
    case "substring" :
      return "substring";
    case "word" :
      return "word";
    default:
      return "stem";
  }
}

function _isExcluded(exclusions, prompt, description, mode) {
  return exclusions.some(k => {
    if (k === "") {
      return false;
    } else if (ReasoningMatch.matchSignal(prompt, k, mode)) {
      return true;
    } else {
      return ReasoningMatch.matchSignal(description, k, mode);
    }
  });
}

function _checkRule(rule, idx, prompt, description) {
  if (rule.keywords.length === 0) {
    return;
  }
  let mode = _getMatchMode(rule.match);
  let modeStr = mode === "word" ? "word" : (
      mode === "substring" ? "substring" : (
          mode === "regex" ? "regex" : "stem"
        )
    );
  let ex = rule.excludeKeywords;
  let exclusions = ex !== undefined ? ex : [];
  if (_isExcluded(exclusions, prompt, description, mode)) {
    return;
  }
  let matched = rule.keywords.find(kw => {
    if (kw === "") {
      return false;
    } else if (ReasoningMatch.matchSignal(prompt, kw, mode)) {
      return true;
    } else {
      return ReasoningMatch.matchSignal(description, kw, mode);
    }
  });
  if (matched === undefined) {
    return;
  }
  let source = ReasoningMatch.matchSignal(prompt, matched, mode) ? "prompt" : "description";
  let lvl = _levelFromString(rule.level);
  return {
    level: lvl,
    reason: `keyword match: rule[` + idx.toString() + `] "` + matched + `" (` + modeStr + `) in ` + source
  };
}

function _scanRules(rules, _idx, prompt, description) {
  while (true) {
    let idx = _idx;
    let rulesLen = rules.length;
    if (idx >= rulesLen) {
      return;
    }
    let rule = rules[idx];
    if (rule !== undefined) {
      let d = _checkRule(rule, idx, prompt, description);
      if (d !== undefined) {
        return d;
      }
      _idx = idx + 1 | 0;
      continue;
    }
    _idx = idx + 1 | 0;
    continue;
  };
}

function selectAdaptiveLevel(signals, _policy) {
  let p = (policy == null ? undefined : policy);
  let effectivePolicy = p !== undefined ? Primitive_option.valFromOption(p) : undefined;
  let adaptive = effectivePolicy !== undefined ? effectivePolicy.adaptive : undefined;
  if (adaptive === undefined) {
    return {
      level: _nullLevel(),
      reason: "no adaptive config"
    };
  }
  let acTrivialLevel = _getTrivialLevel(adaptive);
  let acTierDefaults = _getTierDefaults(adaptive);
  let acKeywordRules = _getKeywordRules(adaptive);
  let acDefaultLevel = _getDefaultLevel(adaptive);
  if (signals.isTrivial) {
    let lvl = acTrivialLevel !== undefined ? _levelFromString(acTrivialLevel) : _nullLevel();
    return {
      level: lvl,
      reason: "trivial"
    };
  }
  let tierDefaults = acTierDefaults !== undefined ? acTierDefaults : ({});
  let tierLevel = tierDefaults[signals.tierName];
  if (tierLevel !== undefined) {
    let lvl$1 = _levelFromString(tierLevel);
    return {
      level: lvl$1,
      reason: `tier default: ` + signals.tierName
    };
  }
  let keywordRules = acKeywordRules !== undefined ? acKeywordRules : [];
  let d = _scanRules(keywordRules, 0, signals.prompt, signals.description);
  if (d !== undefined) {
    return d;
  }
  let lvl$2 = acDefaultLevel !== undefined ? _levelFromString(acDefaultLevel) : _nullLevel();
  return {
    level: lvl$2,
    reason: "default level"
  };
}

function getLevelNull(d) {
  return d.level;
}

function getLevelOption(d) {
  return Primitive_option.fromNullable(d.level);
}

function getReason(d) {
  return d.reason;
}

function makePolicyWithAdaptive(adaptive) {
  return {
    mode: "adaptive",
    defaultLevel: undefined,
    surfaceLimits: undefined,
    adaptive: adaptive
  };
}

export {
  selectAdaptiveLevel,
  getLevelNull,
  getLevelOption,
  getReason,
  makePolicyWithAdaptive,
}
/* No side effect */
