// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as ReasoningCapability from "./ReasoningCapability.res.mjs";

function assertionEqual(operator, expected, actual) {
  Test.assertion(undefined, operator, (a, b) => a === b, actual, expected);
}

function intEqual(a, b) {
  Test.assertion(undefined, "int", (x, y) => x === y, a, b);
}

function stringEqual(actual, expected) {
  Test.assertion(undefined, "string", (a, b) => a === b, actual, expected);
}

Test.test("inferCapability: no reasoning fields => none", () => {
  let tier_whenToUse = [];
  let tier = {
    model: "provider/model",
    description: "standard tier",
    whenToUse: tier_whenToUse
  };
  let result = ReasoningCapability.inferCapability(tier);
  stringEqual(result.kind, "none");
});

Test.test("inferCapability: unknown variant => none", () => {
  let tier_variant = "custom-unknown-variant";
  let tier_whenToUse = [];
  let tier = {
    model: "provider/model",
    variant: tier_variant,
    description: "unknown variant",
    whenToUse: tier_whenToUse
  };
  let result = ReasoningCapability.inferCapability(tier);
  stringEqual(result.kind, "none");
});

Test.test("inferCapability: reasoning.effort set => discrete/reasoning.effort", () => {
  let tier_reasoning = {
    effort: "medium"
  };
  let tier_whenToUse = [];
  let tier = {
    model: "provider/model",
    reasoning: tier_reasoning,
    description: "effort tier",
    whenToUse: tier_whenToUse
  };
  let result = ReasoningCapability.inferCapability(tier);
  stringEqual(result.kind, "discrete");
  stringEqual(Belt_Option.getWithDefault(result.field, ""), "reasoning.effort");
  assertionEqual("levels_len", Belt_Option.getWithDefault(result.levels, []).length, 3);
});

Test.test("inferCapability: thinking.budgetTokens set => budgeted/thinking.budgetTokens", () => {
  let tier_thinking = {
    budgetTokens: 4096
  };
  let tier_whenToUse = [];
  let tier = {
    model: "provider/model",
    thinking: tier_thinking,
    description: "budget tier",
    whenToUse: tier_whenToUse
  };
  let result = ReasoningCapability.inferCapability(tier);
  stringEqual(result.kind, "budgeted");
  stringEqual(Belt_Option.getWithDefault(result.field, ""), "thinking.budgetTokens");
  let rec__ = result.recommended;
  let rec_normal = rec__ !== undefined ? rec__["normal"] : undefined;
  if (rec_normal !== undefined) {
    return intEqual(rec_normal | 0, 4096);
  } else {
    return intEqual(1, 0);
  }
});

Test.test("inferCapability: positional variant low/medium/high => discrete/variant", () => {
  let tier_variant = "medium";
  let tier_whenToUse = [];
  let tier = {
    model: "provider/model",
    variant: tier_variant,
    description: "positional variant",
    whenToUse: tier_whenToUse
  };
  let result = ReasoningCapability.inferCapability(tier);
  stringEqual(result.kind, "discrete");
  stringEqual(Belt_Option.getWithDefault(result.field, ""), "variant");
  assertionEqual("levels", Belt_Option.getWithDefault(result.levels, []).length, 3);
});

Test.test("inferCapability: positional variant xhigh => 4-level ladder", () => {
  let tier_variant = "xhigh";
  let tier_whenToUse = [];
  let tier = {
    model: "provider/model",
    variant: tier_variant,
    description: "xhigh variant",
    whenToUse: tier_whenToUse
  };
  let result = ReasoningCapability.inferCapability(tier);
  stringEqual(result.kind, "discrete");
  assertionEqual("xhigh_levels", Belt_Option.getWithDefault(result.levels, []).length, 4);
});

Test.test("inferCapability: named variant thinking => binary/variant", () => {
  let tier_variant = "thinking";
  let tier_whenToUse = [];
  let tier = {
    model: "provider/model",
    variant: tier_variant,
    description: "thinking tier",
    whenToUse: tier_whenToUse
  };
  let result = ReasoningCapability.inferCapability(tier);
  stringEqual(result.kind, "binary");
  stringEqual(Belt_Option.getWithDefault(result.field, ""), "variant");
  stringEqual(Belt_Option.getWithDefault(result.elevated, ""), "thinking");
});

Test.test("inferCapability: named variant max => binary/variant", () => {
  let tier_variant = "max";
  let tier_whenToUse = [];
  let tier = {
    model: "provider/model",
    variant: tier_variant,
    description: "max tier",
    whenToUse: tier_whenToUse
  };
  let result = ReasoningCapability.inferCapability(tier);
  stringEqual(result.kind, "binary");
  stringEqual(Belt_Option.getWithDefault(result.elevated, ""), "max");
});

Test.test("inferCapability: effort takes precedence over variant", () => {
  let tier_variant = "thinking";
  let tier_reasoning = {
    effort: "low"
  };
  let tier_whenToUse = [];
  let tier = {
    model: "provider/model",
    variant: tier_variant,
    reasoning: tier_reasoning,
    description: "both effort and variant set",
    whenToUse: tier_whenToUse
  };
  let result = ReasoningCapability.inferCapability(tier);
  stringEqual(result.kind, "discrete");
});

Test.test("inferCapability: thinking.budgetTokens takes precedence over variant", () => {
  let tier_variant = "high";
  let tier_thinking = {
    budgetTokens: 8192
  };
  let tier_whenToUse = [];
  let tier = {
    model: "provider/model",
    variant: tier_variant,
    thinking: tier_thinking,
    description: "both budget and variant set",
    whenToUse: tier_whenToUse
  };
  let result = ReasoningCapability.inferCapability(tier);
  stringEqual(result.kind, "budgeted");
});

Test.test("inferCapability: discrete with reasoning.effort sets field correctly", () => {
  let tier_reasoning = {
    effort: "high"
  };
  let tier_whenToUse = [];
  let tier = {
    model: "provider/model",
    reasoning: tier_reasoning,
    description: "effort",
    whenToUse: tier_whenToUse
  };
  let result = ReasoningCapability.inferCapability(tier);
  stringEqual(Belt_Option.getWithDefault(result.field, ""), "reasoning.effort");
});

Test.test("inferCapability: discrete with variant sets field correctly", () => {
  let tier_variant = "low";
  let tier_whenToUse = [];
  let tier = {
    model: "provider/model",
    variant: tier_variant,
    description: "positional",
    whenToUse: tier_whenToUse
  };
  let result = ReasoningCapability.inferCapability(tier);
  stringEqual(Belt_Option.getWithDefault(result.field, ""), "variant");
});

export {
  assertionEqual,
  intEqual,
  stringEqual,
}
/*  Not a pure module */
