// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

let _patCache = {};

function normalizeSignalText(raw) {
  return (raw.toLowerCase().split(/\s+/).join(' ').trim());
}

function _escapeRe(s) {
  return (s.replace(/[.*+?^$( )|[\\\\]\\\\]/g, '\\\\$&'));
}

function _buildPattern(keyword, mm) {
  let kwLower = keyword.toLowerCase();
  if (mm === "word") {
    let tokens = kwLower.split(" ").map(_escapeRe);
    return "\\b" + tokens.join("\\s+") + "\\b";
  }
  if (mm === "substring") {
    return kwLower.split(" ").map(_escapeRe).join("\\s+");
  }
  if (mm === "regex") {
    return kwLower;
  }
  let tokens$1 = kwLower.split(" ");
  let tokLen = tokens$1.length;
  if (tokLen === 0) {
    return "\\b\\w*";
  }
  if (tokLen === 1) {
    let v = Belt_Array.get(tokens$1, 0);
    let firstTok = v !== undefined ? v : "";
    return "\\b" + firstTok + "\\w*";
  }
  let v$1 = Belt_Array.get(tokens$1, tokLen - 1 | 0);
  let lastTok = v$1 !== undefined ? v$1 : "";
  let headToks = Belt_Array.slice(tokens$1, 0, tokLen - 1 | 0);
  let escHead = headToks.map(_escapeRe).join("\\s+");
  return "\\b" + escHead + "\\s+" + lastTok + "\\w*";
}

function matchSignal(signalTxt, keyword, mm) {
  if (keyword === "") {
    return false;
  }
  let pat = _buildPattern(keyword, mm);
  _patCache["pat"] = pat;
  let key = "pat";
  let pat$1 = Js_dict.get(_patCache, key);
  if (pat$1 !== undefined) {
    return ((function(pat, signalTxt) {
    try { return (new RegExp(pat, "i")).test(signalTxt); } catch(e) { return false; }
  })(pat, signalTxt));
  } else {
    return false;
  }
}

export {
  normalizeSignalText,
  matchSignal,
}
/* No side effect */
