// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as ReasoningMatch from "./ReasoningMatch.res.mjs";

function assertionEqual(operator, expected, actual) {
  Test.assertion(undefined, operator, (a, b) => a === b, actual, expected);
}

function assertionTrue(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === true, actual, true);
}

function assertionFalse(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === false, actual, false);
}

Test.test("normalizeSignalText: lowercases input", () => assertionEqual("mixed", ReasoningMatch.normalizeSignalText("Hello WORLD"), "hello world"));

Test.test("normalizeSignalText: collapses whitespace runs", () => {
  assertionEqual("tabs", ReasoningMatch.normalizeSignalText("hello\tworld"), "hello world");
  assertionEqual("newlines", ReasoningMatch.normalizeSignalText("hello\nworld"), "hello world");
  assertionEqual("multi-space", ReasoningMatch.normalizeSignalText("hello  world"), "hello world");
});

Test.test("normalizeSignalText: trims edges", () => {
  assertionEqual("leading", ReasoningMatch.normalizeSignalText("  hello"), "hello");
  assertionEqual("trailing", ReasoningMatch.normalizeSignalText("hello  "), "hello");
});

Test.test("normalizeSignalText: phrase whitespace normalisation", () => {
  assertionEqual("phrase", ReasoningMatch.normalizeSignalText("root\tcause"), "root cause");
  assertionEqual("phrase-multi-space", ReasoningMatch.normalizeSignalText("root    cause"), "root cause");
});

Test.test("matchSignal: word mode — exact word match", () => {
  let text = ReasoningMatch.normalizeSignalText("debug the authentication module");
  assertionTrue("debug", ReasoningMatch.matchSignal(text, "debug", "word"));
  assertionFalse("auth", ReasoningMatch.matchSignal(text, "authentication", "word"));
});

Test.test("matchSignal: word mode — case insensitive", () => {
  let text = ReasoningMatch.normalizeSignalText("DEBUG the module");
  assertionTrue("uppercase", ReasoningMatch.matchSignal(text, "debug", "word"));
});

Test.test("matchSignal: word mode — phrase match", () => {
  let text = ReasoningMatch.normalizeSignalText("fix the root cause analysis");
  assertionTrue("phrase", ReasoningMatch.matchSignal(text, "root cause", "word"));
});

Test.test("matchSignal: word mode — inflection rejects suffix", () => {
  let text = ReasoningMatch.normalizeSignalText("debugging the issue");
  assertionFalse("debugging", ReasoningMatch.matchSignal(text, "debug", "word"));
});

Test.test("matchSignal: word mode — identifier underscore not a word break", () => {
  let text = ReasoningMatch.normalizeSignalText("test_fixture");
  assertionTrue("test_fixture", ReasoningMatch.matchSignal(text, "test", "word"));
});

Test.test("matchSignal: word mode — empty keyword returns false", () => {
  let text = ReasoningMatch.normalizeSignalText("hello world");
  assertionFalse("empty", ReasoningMatch.matchSignal(text, "", "word"));
});

Test.test("matchSignal: stem mode — base word matches inflection", () => {
  let text = ReasoningMatch.normalizeSignalText("debugging the issue");
  assertionTrue("debugging", ReasoningMatch.matchSignal(text, "debug", "stem"));
});

Test.test("matchSignal: stem mode — no cross-word false positives", () => {
  let text = ReasoningMatch.normalizeSignalText("latest version");
  assertionFalse("latest", ReasoningMatch.matchSignal(text, "test", "stem"));
});

Test.test("matchSignal: stem mode — prefix not matched across words", () => {
  let text = ReasoningMatch.normalizeSignalText("prefix the output");
  assertionFalse("prefix", ReasoningMatch.matchSignal(text, "fix", "stem"));
});

Test.test("matchSignal: stem mode — phrase with inflection on last token", () => {
  let text = ReasoningMatch.normalizeSignalText("root cause analysis");
  assertionTrue("cause", ReasoningMatch.matchSignal(text, "root cause", "stem"));
});

Test.test("matchSignal: stem mode — multi-token stem on last only", () => {
  let text = ReasoningMatch.normalizeSignalText("refactoring the codebase");
  assertionTrue("refactor", ReasoningMatch.matchSignal(text, "refactor", "stem"));
});

Test.test("matchSignal: stem mode — single token suffix match", () => {
  let text = ReasoningMatch.normalizeSignalText("the refactoring task");
  assertionTrue("refactor", ReasoningMatch.matchSignal(text, "refactor", "stem"));
});

Test.test("matchSignal: substring mode — legacy includes behavior", () => {
  let text = ReasoningMatch.normalizeSignalText("fix the authentication bug");
  assertionTrue("auth", ReasoningMatch.matchSignal(text, "auth", "substring"));
});

Test.test("matchSignal: substring mode — cross-word match", () => {
  let text = ReasoningMatch.normalizeSignalText("latest update available");
  assertionTrue("test", ReasoningMatch.matchSignal(text, "test", "substring"));
});

Test.test("matchSignal: substring mode — phrase match across whitespace", () => {
  let text = ReasoningMatch.normalizeSignalText("root\tcause analysis");
  assertionTrue("root-cause", ReasoningMatch.matchSignal(text, "root cause", "substring"));
});

Test.test("matchSignal: regex mode — valid pattern matches", () => {
  let text = ReasoningMatch.normalizeSignalText("error E001 in module");
  assertionTrue("e001", ReasoningMatch.matchSignal(text, "E\\d+", "regex"));
  assertionFalse("no-match", ReasoningMatch.matchSignal(text, "W\\d+", "regex"));
});

Test.test("matchSignal: regex mode — invalid pattern fails soft to false", () => {
  let text = ReasoningMatch.normalizeSignalText("hello world");
  assertionFalse("invalid", ReasoningMatch.matchSignal(text, "(invalid", "regex"));
});

Test.test("matchSignal: regex mode — case insensitive flag", () => {
  let text = ReasoningMatch.normalizeSignalText("ERROR in module");
  assertionTrue("error", ReasoningMatch.matchSignal(text, "error", "regex"));
});

Test.test("matchSignal: cache — repeated calls do not recompile", () => {
  let text = ReasoningMatch.normalizeSignalText("debug the module");
  let r1 = ReasoningMatch.matchSignal(text, "debug", "word");
  let r2 = ReasoningMatch.matchSignal(text, "debug", "word");
  assertionTrue("r1", r1 === true);
  assertionTrue("r2", r2 === true);
  assertionTrue("same", r1 === r2);
});

Test.test("matchSignal: cache — different mode recompiles", () => {
  let text = ReasoningMatch.normalizeSignalText("debugging the module");
  let r1 = ReasoningMatch.matchSignal(text, "debug", "word");
  let r2 = ReasoningMatch.matchSignal(text, "debug", "stem");
  assertionFalse("word", r1 === false);
  assertionTrue("stem", r2 === true);
});

Test.test("matchSignal: whitespace-only keyword compiles to permissive regex", () => {
  let text = ReasoningMatch.normalizeSignalText("hello world");
  ReasoningMatch.matchSignal(text, "   ", "word");
});

Test.test("matchSignal: unknown mode treated as stem", () => {
  let text = ReasoningMatch.normalizeSignalText("debugging the module");
  assertionTrue("stem", ReasoningMatch.matchSignal(text, "debug", "word"));
});

export {
  assertionEqual,
  assertionTrue,
  assertionFalse,
}
/*  Not a pure module */
