// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";

function _effortOpts(picked) {
  return ((function(p) { return { "reasoning_effort": p }; })(arguments[0]));
}

function _budgetOpts(tokens) {
  return ((function(t) { return { "budget_tokens": t }; })(arguments[0]));
}

function _clampIdx(rank, len) {
  return ((function(rank, len) { return Math.round((rank / 3) * (len - 1)); })(arguments[0], arguments[1]));
}

let d = {};

d["minimal"] = 0;

d["normal"] = 1;

d["elevated"] = 2;

d["max"] = 3;

function translateLevel(cap, level) {
  let match = cap.kind;
  switch (match) {
    case "binary" :
      let isElevated = level === "elevated" || level === "max";
      if (isElevated) {
        let v = cap.elevated;
        if (v !== undefined) {
          return {
            variant: v
          };
        } else {
          return;
        }
      }
      let b = cap.baseline;
      if (b !== undefined) {
        return {
          variant: b
        };
      } else {
        return;
      }
    case "budgeted" :
      let levelName = level === "max" ? "max" : (
          level === "elevated" ? "elevated" : (
              level === "normal" ? "normal" : "minimal"
            )
        );
      let r = cap.recommended;
      let rec_ = r !== undefined ? r : ({});
      let t = Js_dict.get(rec_, levelName);
      let tokens = t !== undefined ? t : Js_dict.get(rec_, "normal");
      if (tokens === undefined) {
        return;
      }
      let opts = _budgetOpts(tokens);
      return {
        options: opts
      };
    case "discrete" :
      let levelName$1 = level === "max" ? "max" : (
          level === "elevated" ? "elevated" : (
              level === "normal" ? "normal" : "minimal"
            )
        );
      let r$1 = Js_dict.get(d, levelName$1);
      let rank = r$1 !== undefined ? r$1 : 0;
      let l = cap.levels;
      let levels = l !== undefined ? l : [];
      let len = levels.length;
      if (len === 0) {
        return;
      }
      let rawIdx = _clampIdx(rank, len);
      let idx = rawIdx < len ? rawIdx : len - 1 | 0;
      let v$1 = levels[idx];
      let picked = v$1 !== undefined ? v$1 : "";
      if (picked === "") {
        return;
      }
      let match$1 = cap.field;
      if (match$1 === "variant") {
        return {
          variant: picked
        };
      }
      let opts$1 = _effortOpts(picked);
      return {
        options: opts$1
      };
      break;
    default:
      return;
  }
}

export {
  translateLevel,
}
/*  Not a pure module */
