// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as ReasoningAdaptive from "./ReasoningAdaptive.res.mjs";

function assertionEqual(operator, expected, actual) {
  Test.assertion(undefined, operator, (a, b) => a === b, actual, expected);
}

function assertionTrue(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === true, actual, true);
}

function assertionFalse(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === false, actual, false);
}

function assertionSome(operator, expected, actual) {
  if (actual !== undefined) {
    return Test.assertion(undefined, operator, (a, b) => a === b, Primitive_option.valFromOption(actual), expected);
  } else {
    return Test.assertion(undefined, operator, (_a, _b) => false, undefined, undefined);
  }
}

function assertionSomeAny(operator, actual) {
  if (actual !== undefined) {
    return;
  } else {
    return Test.assertion(undefined, operator, (_a, _b) => false, undefined, undefined);
  }
}

function assertionNone(operator, actual) {
  if (actual !== undefined) {
    return Test.assertion(undefined, operator, (_a, _b) => false, undefined, undefined);
  }
}

function assertionLevelNull(operator, result) {
  let opt = ReasoningAdaptive.getLevelOption(result);
  if (opt !== undefined) {
    return Test.assertion(undefined, operator, (_a, _b) => false, undefined, undefined);
  }
}

let baseSignals = {
  prompt: "implement a new feature",
  description: "add a button to the dashboard",
  tierName: "medium",
  isTrivial: false
};

Test.test("selectAdaptiveLevel: returns null when policy is undefined", () => {
  let result = ReasoningAdaptive.selectAdaptiveLevel(baseSignals, undefined);
  assertionLevelNull("level", result);
  assertionEqual("reason", ReasoningAdaptive.getReason(result), "no adaptive config");
});

Test.test("selectAdaptiveLevel: returns null when policy.adaptive is undefined", () => {
  let result = ReasoningAdaptive.selectAdaptiveLevel(baseSignals, {
    mode: "adaptive",
    defaultLevel: undefined,
    surfaceLimits: undefined,
    adaptive: undefined
  });
  assertionLevelNull("level", result);
  assertionEqual("reason", ReasoningAdaptive.getReason(result), "no adaptive config");
});

Test.test("selectAdaptiveLevel: does not consult defaultLevel when adaptive block is missing", () => {
  let result = ReasoningAdaptive.selectAdaptiveLevel(baseSignals, {
    mode: "adaptive",
    defaultLevel: "elevated",
    surfaceLimits: undefined,
    adaptive: undefined
  });
  assertionLevelNull("level", result);
});

Test.test("selectAdaptiveLevel: applies trivialLevel when isTrivial is true", () => {
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: "minimal",
    defaultLevel: undefined,
    keywordRules: undefined,
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "implement a new feature",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: true
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "minimal", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: returns null when isTrivial is true and trivialLevel is absent", () => {
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "elevated",
    keywordRules: undefined,
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "implement a new feature",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: true
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionLevelNull("level", result);
});

Test.test("selectAdaptiveLevel: returns null when isTrivial is true and trivialLevel is explicitly null", () => {
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "normal",
    keywordRules: undefined,
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "implement a new feature",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: true
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionLevelNull("level", result);
});

Test.test("selectAdaptiveLevel: does NOT consult tierDefaults or keywordRules when isTrivial is true", () => {
  let tierDefaults = {};
  tierDefaults["medium"] = "elevated";
  let rule_keywords = ["refactor"];
  let rule = {
    keywords: rule_keywords,
    level: "max",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: "minimal",
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: tierDefaults,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "refactor this module",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: true
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "minimal", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: returns tierDefaults[tierName] when tier is listed", () => {
  let tierDefaults = {};
  tierDefaults["heavy"] = "elevated";
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "normal",
    keywordRules: undefined,
    tierDefaults: tierDefaults,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "implement a new feature",
    description: "add a button to the dashboard",
    tierName: "heavy",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "elevated", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: falls through to defaultLevel when tierName is not in tierDefaults", () => {
  let tierDefaults = {};
  tierDefaults["heavy"] = "elevated";
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "normal",
    keywordRules: undefined,
    tierDefaults: tierDefaults,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "implement a new feature",
    description: "add a button to the dashboard",
    tierName: "fast",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "normal", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: treats empty tierDefaults as absent", () => {
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "elevated",
    keywordRules: undefined,
    tierDefaults: {},
    surfaceDecision: undefined
  });
  let result = ReasoningAdaptive.selectAdaptiveLevel(baseSignals, policy);
  assertionSome("level", "elevated", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: tierDefaults wins over keywordRules", () => {
  let tierDefaults = {};
  tierDefaults["medium"] = "elevated";
  let rule_keywords = ["refactor"];
  let rule = {
    keywords: rule_keywords,
    level: "max",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "normal",
    keywordRules: [rule],
    tierDefaults: tierDefaults,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "please refactor this file",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "elevated", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: first matching keyword rule wins", () => {
  let rule1_keywords = ["refactor"];
  let rule1 = {
    keywords: rule1_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let rule2_keywords = ["fix"];
  let rule2 = {
    keywords: rule2_keywords,
    level: "minimal",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [
      rule1,
      rule2
    ],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "please fix the bug and refactor the module",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "elevated", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: matches keywords found in description", () => {
  let rule_keywords = ["refactor"];
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "implement a new endpoint",
    description: "needs a refactor of the auth layer",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "elevated", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: matches keywords found in prompt", () => {
  let rule_keywords = ["debug"];
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "debug the failing test",
    description: "in the payments service",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "elevated", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: is case-insensitive via stem mode default", () => {
  let rule_keywords = ["refactor"];
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "refactoring the auth module",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "elevated", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: substring mode matches inflections", () => {
  let rule_keywords = ["refactor"];
  let rule_match = "substring";
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: rule_match,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "we are refactoring this code",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "elevated", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: skips rules with empty keyword arrays", () => {
  let ruleEmpty_keywords = [];
  let ruleEmpty = {
    keywords: ruleEmpty_keywords,
    level: "max",
    match: undefined,
    excludeKeywords: undefined
  };
  let ruleMatch_keywords = ["refactor"];
  let ruleMatch = {
    keywords: ruleMatch_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [
      ruleEmpty,
      ruleMatch
    ],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "refactor this",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "elevated", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: reason includes rule index, keyword, mode, and source", () => {
  let rule_keywords = [
    "refactor",
    "architecture"
  ];
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "please refactor this",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionEqual("reason", ReasoningAdaptive.getReason(result), `keyword match: rule[0] "refactor" (stem) in prompt`);
});

Test.test("selectAdaptiveLevel: first matching keyword within a multi-keyword rule wins", () => {
  let rule_keywords = [
    "refactor",
    "architecture",
    "security"
  ];
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "review the architecture",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionEqual("reason", ReasoningAdaptive.getReason(result), `keyword match: rule[0] "architecture" (stem) in prompt`);
});

Test.test("selectAdaptiveLevel: skips a rule whose keywords field is missing without throwing", () => {
  let malformedRule_keywords = [];
  let malformedRule = {
    keywords: malformedRule_keywords,
    level: "max",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [malformedRule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "implement a button",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionLevelNull("level", result);
});

Test.test("selectAdaptiveLevel: falls through to defaultLevel when every keyword rule is malformed", () => {
  let malformedRule_keywords = [];
  let malformedRule = {
    keywords: malformedRule_keywords,
    level: "max",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "normal",
    keywordRules: [malformedRule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "refactor this",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "normal", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: returns defaultLevel when no rule matches", () => {
  let rule_keywords = ["refactor"];
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "normal",
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "implement a button",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "normal", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: returns null when no rule matches AND defaultLevel is absent", () => {
  let rule_keywords = ["refactor"];
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "implement a button",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionLevelNull("level", result);
});

Test.test("selectAdaptiveLevel: returns null when defaultLevel is explicitly null", () => {
  let rule_keywords = ["refactor"];
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "implement a button",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionLevelNull("level", result);
});

Test.test("selectAdaptiveLevel: returns null when nothing is configured besides an empty adaptive block", () => {
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: undefined,
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let result = ReasoningAdaptive.selectAdaptiveLevel(baseSignals, policy);
  assertionLevelNull("level", result);
});

Test.test("selectAdaptiveLevel: returns defaultLevel when prompt and description are both empty", () => {
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "normal",
    keywordRules: undefined,
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let result = ReasoningAdaptive.selectAdaptiveLevel({
    prompt: "",
    description: "",
    tierName: "medium",
    isTrivial: false
  }, policy);
  assertionSome("level", "normal", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: does not match keywords across tierName boundary", () => {
  let rule_keywords = ["refactor"];
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "implement a new feature",
    description: "add a button to the dashboard",
    tierName: "refactor",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionLevelNull("level", result);
});

Test.test("selectAdaptiveLevel: is deterministic — same inputs produce same decision", () => {
  let rule_keywords = ["debug"];
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "normal",
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "debug the flaky test",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let r1 = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  let r2 = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  let r3 = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionEqual("r1==r2", ReasoningAdaptive.getReason(r1), ReasoningAdaptive.getReason(r2));
  assertionEqual("r2==r3", ReasoningAdaptive.getReason(r2), ReasoningAdaptive.getReason(r3));
});

Test.test("selectAdaptiveLevel: stem default matches inflection debugging against debug", () => {
  let rule_keywords = ["debug"];
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "debugging the race condition in the payments worker",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "elevated", ReasoningAdaptive.getLevelOption(result));
  assertionEqual("reason", ReasoningAdaptive.getReason(result), `keyword match: rule[0] "debug" (stem) in prompt`);
});

Test.test("selectAdaptiveLevel: word mode strict — rejects inflection on last token", () => {
  let rule_keywords = ["debug"];
  let rule_match = "word";
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: rule_match,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "debugging the flaky test",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionLevelNull("level", result);
});

Test.test("selectAdaptiveLevel: excludeKeywords skips a matching rule", () => {
  let ruleFormat_keywords = ["format"];
  let ruleFormat_excludeKeywords = ["refactor"];
  let ruleFormat = {
    keywords: ruleFormat_keywords,
    level: "minimal",
    match: undefined,
    excludeKeywords: ruleFormat_excludeKeywords
  };
  let ruleRefactor_keywords = ["refactor"];
  let ruleRefactor = {
    keywords: ruleRefactor_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "normal",
    keywordRules: [
      ruleFormat,
      ruleRefactor
    ],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "format and refactor the auth module",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "elevated", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: falls through to defaultLevel when only matching rule is excluded", () => {
  let ruleFormat_keywords = ["format"];
  let ruleFormat_excludeKeywords = ["refactor"];
  let ruleFormat = {
    keywords: ruleFormat_keywords,
    level: "minimal",
    match: undefined,
    excludeKeywords: ruleFormat_excludeKeywords
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "normal",
    keywordRules: [ruleFormat],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "format the source and refactor the module",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "normal", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: regex mode matches user-supplied pattern", () => {
  let rule_keywords = ["^perf"];
  let rule_match = "regex";
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: rule_match,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "performance regression in the payments worker",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "elevated", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: regex mode falls through on invalid pattern (fail-soft)", () => {
  let rule_keywords = ["("];
  let rule_match = "regex";
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: rule_match,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "normal",
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "any task text",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "normal", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: substring mode matches test inside latest", () => {
  let rule_keywords = ["test"];
  let rule_match = "substring";
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: rule_match,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "normal",
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "update the latest fixtures",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "elevated", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: stem mode does NOT match test inside latest (cross-word false positive)", () => {
  let rule_keywords = ["test"];
  let rule = {
    keywords: rule_keywords,
    level: "elevated",
    match: undefined,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: "normal",
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "update the latest fixtures",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionSome("level", "normal", ReasoningAdaptive.getLevelOption(result));
});

Test.test("selectAdaptiveLevel: reason records the rule's actual mode", () => {
  let rule_keywords = ["test"];
  let rule_match = "substring";
  let rule = {
    keywords: rule_keywords,
    level: "normal",
    match: rule_match,
    excludeKeywords: undefined
  };
  let policy = ReasoningAdaptive.makePolicyWithAdaptive({
    trivialLevel: undefined,
    defaultLevel: undefined,
    keywordRules: [rule],
    tierDefaults: undefined,
    surfaceDecision: undefined
  });
  let signals = {
    prompt: "update the latest fixtures",
    description: "add a button to the dashboard",
    tierName: "medium",
    isTrivial: false
  };
  let result = ReasoningAdaptive.selectAdaptiveLevel(signals, policy);
  assertionEqual("reason", ReasoningAdaptive.getReason(result), `keyword match: rule[0] "test" (substring) in prompt`);
});

export {
  assertionEqual,
  assertionTrue,
  assertionFalse,
  assertionSome,
  assertionSomeAny,
  assertionNone,
  assertionLevelNull,
  baseSignals,
}
/*  Not a pure module */
