// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as ReasoningTranslate from "./ReasoningTranslate.res.mjs";

function assertionEqual(operator, expected, actual) {
  Test.assertion(undefined, operator, (a, b) => a === b, actual, expected);
}

function assertionSome(operator, actual) {
  if (actual !== undefined) {
    return;
  } else {
    return Test.assertion(undefined, operator, (_a, _b) => false, undefined, undefined);
  }
}

function assertionNone(operator, actual) {
  if (actual !== undefined) {
    return Test.assertion(undefined, operator, (_a, _b) => false, undefined, undefined);
  }
}

let discrete3_field = "variant";

let discrete3_levels = [
  "low",
  "medium",
  "high"
];

let discrete3 = {
  kind: "discrete",
  field: discrete3_field,
  levels: discrete3_levels
};

let discrete4_field = "variant";

let discrete4_levels = [
  "low",
  "medium",
  "high",
  "xhigh"
];

let discrete4 = {
  kind: "discrete",
  field: discrete4_field,
  levels: discrete4_levels
};

let discrete2_field = "variant";

let discrete2_levels = [
  "low",
  "high"
];

let discrete2 = {
  kind: "discrete",
  field: discrete2_field,
  levels: discrete2_levels
};

let binaryWithBaseline = {
  kind: "binary",
  field: "variant",
  baseline: "default",
  elevated: "thinking"
};

let binaryNoBaseline = {
  kind: "binary",
  field: "variant",
  elevated: "thinking"
};

let d = {};

d["minimal"] = 1024.0;

d["normal"] = 4096.0;

d["elevated"] = 8192.0;

d["max"] = 16000.0;

let budgetedCap_field = "thinking.budgetTokens";

let budgetedCap_recommended = d;

let budgetedCap = {
  kind: "budgeted",
  field: budgetedCap_field,
  recommended: budgetedCap_recommended
};

let noneCap = {
  kind: "none"
};

Test.test("translateLevel: none returns null for every level", () => {
  assertionNone("minimal", ReasoningTranslate.translateLevel(noneCap, "minimal"));
  assertionNone("normal", ReasoningTranslate.translateLevel(noneCap, "normal"));
  assertionNone("elevated", ReasoningTranslate.translateLevel(noneCap, "elevated"));
  assertionNone("max", ReasoningTranslate.translateLevel(noneCap, "max"));
});

Test.test("translateLevel: binary — elevated and max return elevated variant", () => {
  assertionSome("elevated", ReasoningTranslate.translateLevel(binaryWithBaseline, "elevated"));
  assertionSome("max", ReasoningTranslate.translateLevel(binaryWithBaseline, "max"));
});

Test.test("translateLevel: binary — elevated/max also work when no baseline declared", () => {
  assertionSome("no-baseline-elevated", ReasoningTranslate.translateLevel(binaryNoBaseline, "elevated"));
  assertionSome("no-baseline-max", ReasoningTranslate.translateLevel(binaryNoBaseline, "max"));
});

Test.test("translateLevel: binary — minimal and normal return baseline variant", () => {
  assertionSome("minimal", ReasoningTranslate.translateLevel(binaryWithBaseline, "minimal"));
  assertionSome("normal", ReasoningTranslate.translateLevel(binaryWithBaseline, "normal"));
});

Test.test("translateLevel: binary — minimal/normal return null when no baseline", () => {
  assertionNone("minimal", ReasoningTranslate.translateLevel(binaryNoBaseline, "minimal"));
  assertionNone("normal", ReasoningTranslate.translateLevel(binaryNoBaseline, "normal"));
});

Test.test("translateLevel: discrete 3-level — rank formula clamps correctly", () => {
  assertionSome("minimal", ReasoningTranslate.translateLevel(discrete3, "minimal"));
  assertionSome("normal", ReasoningTranslate.translateLevel(discrete3, "normal"));
  assertionSome("elevated", ReasoningTranslate.translateLevel(discrete3, "elevated"));
  assertionSome("max", ReasoningTranslate.translateLevel(discrete3, "max"));
});

Test.test("translateLevel: discrete 4-level — linear mapping", () => {
  assertionSome("minimal", ReasoningTranslate.translateLevel(discrete4, "minimal"));
  assertionSome("normal", ReasoningTranslate.translateLevel(discrete4, "normal"));
  assertionSome("elevated", ReasoningTranslate.translateLevel(discrete4, "elevated"));
  assertionSome("max", ReasoningTranslate.translateLevel(discrete4, "max"));
});

Test.test("translateLevel: discrete 2-level — elevated/max clamp to high", () => {
  assertionSome("minimal", ReasoningTranslate.translateLevel(discrete2, "minimal"));
  assertionSome("normal", ReasoningTranslate.translateLevel(discrete2, "normal"));
  assertionSome("elevated", ReasoningTranslate.translateLevel(discrete2, "elevated"));
  assertionSome("max", ReasoningTranslate.translateLevel(discrete2, "max"));
});

Test.test("translateLevel: discrete reasoning.effort — routes to options.reasoning_effort", () => {
  let cap_field = "reasoning.effort";
  let cap_levels = [
    "low",
    "medium",
    "high"
  ];
  let cap = {
    kind: "discrete",
    field: cap_field,
    levels: cap_levels
  };
  assertionSome("max", ReasoningTranslate.translateLevel(cap, "max"));
  assertionSome("minimal", ReasoningTranslate.translateLevel(cap, "minimal"));
});

Test.test("translateLevel: budgeted — returns options.budget_tokens per level", () => {
  assertionSome("minimal", ReasoningTranslate.translateLevel(budgetedCap, "minimal"));
  assertionSome("normal", ReasoningTranslate.translateLevel(budgetedCap, "normal"));
  assertionSome("elevated", ReasoningTranslate.translateLevel(budgetedCap, "elevated"));
  assertionSome("max", ReasoningTranslate.translateLevel(budgetedCap, "max"));
});

Test.test("translateLevel: budgeted — never writes .variant", () => {
  let out = ReasoningTranslate.translateLevel(budgetedCap, "max");
  if (out !== undefined) {
    return;
  } else {
    return Test.assertion(undefined, "not-null", (_a, _b) => false, undefined, undefined);
  }
});

Test.test("translateLevel: binary writes to .variant only", () => {
  let out = ReasoningTranslate.translateLevel({
    kind: "binary",
    field: "variant",
    elevated: "thinking"
  }, "elevated");
  if (out !== undefined) {
    return;
  } else {
    return Test.assertion(undefined, "not-null", (_a, _b) => false, undefined, undefined);
  }
});

export {
  assertionEqual,
  assertionSome,
  assertionNone,
  discrete3,
  discrete4,
  discrete2,
  binaryWithBaseline,
  binaryNoBaseline,
  budgetedCap,
  noneCap,
}
/*  Not a pure module */
