// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as ReasoningPolicy from "./ReasoningPolicy.res.mjs";
import * as Js_null_undefined from "@rescript/runtime/lib/es6/Js_null_undefined.js";

function assertionNull(operator, actual) {
  Test.assertion(undefined, operator, (a, _b) => a === null, Js_null_undefined.fromOption(actual), null);
}

function assertionNotNull(operator, actual) {
  Test.assertion(undefined, operator, (a, _b) => a !== null, Js_null_undefined.fromOption(actual), null);
}

let baseTier_whenToUse = [];

let baseTier = {
  model: "test/model",
  description: "test tier",
  whenToUse: baseTier_whenToUse
};

let newrecord = {...baseTier};

newrecord.variant = "thinking";

let newrecord$1 = {...baseTier};

newrecord$1.reasoning = {
  effort: "high"
};

let newrecord$2 = {...baseTier};

newrecord$2.thinking = {
  budgetTokens: 4096
};

let staticPolicy = {
  mode: "static",
  defaultLevel: undefined,
  surfaceLimits: undefined,
  adaptive: undefined
};

let manualPolicy = {
  mode: "manual",
  defaultLevel: undefined,
  surfaceLimits: undefined,
  adaptive: undefined
};

function manualPolicyWithDefault(dl) {
  return {
    mode: "manual",
    defaultLevel: dl,
    surfaceLimits: undefined,
    adaptive: undefined
  };
}

function unknownPolicy(mode) {
  return {
    mode: mode,
    defaultLevel: undefined,
    surfaceLimits: undefined,
    adaptive: undefined
  };
}

let emptySignals = {
  prompt: "",
  description: "",
  tierName: "",
  isTrivial: false
};

Test.test("resolveReasoningOverride: static returns null for every level", () => {
  assertionNull("minimal", ReasoningPolicy.resolveReasoningOverride(newrecord, staticPolicy, "minimal", emptySignals));
  assertionNull("elevated", ReasoningPolicy.resolveReasoningOverride(newrecord, staticPolicy, "elevated", emptySignals));
  assertionNull("max", ReasoningPolicy.resolveReasoningOverride(newrecord, staticPolicy, "max", emptySignals));
});

Test.test("resolveReasoningOverride: static ignores session override", () => assertionNull("with-override", ReasoningPolicy.resolveReasoningOverride(newrecord, staticPolicy, "elevated", emptySignals)));

Test.test("resolveReasoningOverride: static when policy is undefined", () => assertionNull("no-policy", ReasoningPolicy.resolveReasoningOverride(newrecord, undefined, "elevated", emptySignals)));

Test.test("resolveReasoningOverride: manual translates session override (binary)", () => {
  assertionNotNull("elevated", ReasoningPolicy.resolveReasoningOverride(newrecord, manualPolicy, "elevated", emptySignals));
  assertionNotNull("max", ReasoningPolicy.resolveReasoningOverride(newrecord, manualPolicy, "max", emptySignals));
});

Test.test("resolveReasoningOverride: manual uses defaultLevel when no override", () => assertionNotNull("with-default", ReasoningPolicy.resolveReasoningOverride(newrecord, {
  mode: "manual",
  defaultLevel: "elevated",
  surfaceLimits: undefined,
  adaptive: undefined
}, undefined, emptySignals)));

Test.test("resolveReasoningOverride: manual returns null when no override and no defaultLevel", () => assertionNull("no-override", ReasoningPolicy.resolveReasoningOverride(newrecord, manualPolicy, undefined, emptySignals)));

Test.test("resolveReasoningOverride: manual session override wins over defaultLevel", () => assertionNotNull("override-wins", ReasoningPolicy.resolveReasoningOverride(newrecord, {
  mode: "manual",
  defaultLevel: "minimal",
  surfaceLimits: undefined,
  adaptive: undefined
}, "max", emptySignals)));

Test.test("resolveReasoningOverride: manual with discrete tier (reasoning.effort)", () => assertionNotNull("discrete", ReasoningPolicy.resolveReasoningOverride(newrecord$1, manualPolicy, "elevated", emptySignals)));

Test.test("resolveReasoningOverride: manual with budgeted tier", () => assertionNotNull("budgeted", ReasoningPolicy.resolveReasoningOverride(newrecord$2, manualPolicy, "max", emptySignals)));

Test.test("resolveReasoningOverride: manual with none-capability tier returns null", () => {
  assertionNull("none-cap", ReasoningPolicy.resolveReasoningOverride(baseTier, manualPolicy, "elevated", emptySignals));
  assertionNull("none-cap-max", ReasoningPolicy.resolveReasoningOverride(baseTier, manualPolicy, "max", emptySignals));
});

Test.test("resolveReasoningOverride: explicit capability wins over inference", () => {
  let newrecord$3 = {...newrecord};
  newrecord$3.capability = {
    kind: "binary",
    field: "variant",
    elevated: "max"
  };
  assertionNotNull("explicit-cap", ReasoningPolicy.resolveReasoningOverride(newrecord$3, manualPolicy, "elevated", emptySignals));
});

Test.test("resolveReasoningOverride: unknown mode returns null", () => {
  assertionNull("typo-mode", ReasoningPolicy.resolveReasoningOverride(newrecord, {
    mode: "adaptive-typo",
    defaultLevel: undefined,
    surfaceLimits: undefined,
    adaptive: undefined
  }, "elevated", emptySignals));
  assertionNull("auto-mode", ReasoningPolicy.resolveReasoningOverride(newrecord, {
    mode: "auto",
    defaultLevel: undefined,
    surfaceLimits: undefined,
    adaptive: undefined
  }, "elevated", emptySignals));
  assertionNull("empty-mode", ReasoningPolicy.resolveReasoningOverride(newrecord, {
    mode: "",
    defaultLevel: undefined,
    surfaceLimits: undefined,
    adaptive: undefined
  }, "elevated", emptySignals));
});

Test.test("resolveReasoningOverride: unknown mode ignores session override", () => assertionNull("override-ignored", ReasoningPolicy.resolveReasoningOverride(newrecord, {
  mode: "adaptive-typo",
  defaultLevel: undefined,
  surfaceLimits: undefined,
  adaptive: undefined
}, "max", emptySignals)));

Test.test("resolveReasoningOverride: unknown mode ignores adaptive block", () => assertionNull("adaptive-block-ignored", ReasoningPolicy.resolveReasoningOverride(newrecord, {
  mode: "foo",
  defaultLevel: undefined,
  surfaceLimits: undefined,
  adaptive: undefined
}, undefined, emptySignals)));

Test.test("resolveReasoningOverride: adaptive mode returns null (Phase 1 stub)", () => assertionNull("adaptive-stub", ReasoningPolicy.resolveReasoningOverride(newrecord$1, {
  mode: "adaptive",
  defaultLevel: undefined,
  surfaceLimits: undefined,
  adaptive: undefined
}, undefined, emptySignals)));

let binaryTier = newrecord;

let discreteTier = newrecord$1;

let budgetedTier = newrecord$2;

let noneTier = baseTier;

export {
  assertionNull,
  assertionNotNull,
  baseTier,
  binaryTier,
  discreteTier,
  budgetedTier,
  noneTier,
  staticPolicy,
  manualPolicy,
  manualPolicyWithDefault,
  unknownPolicy,
  emptySignals,
}
/*  Not a pure module */
